/* sysdefs.h -- #defines for your system created by ./support/mksysdefs.
   Do NOT EDIT this file, since any changes will disappear.
   Instead, edit ./support/mksysdefs, or config.h, or machines.h. */

#if !defined (_SYSDEFS_H_)
#  define _SYSDEFS_H_

#if !defined (MAINTAINER)
#  define MAINTAINER adam@yggdrasil.com
#endif /* MAINTAINER */

#if !defined (RANLIB_LOCATION)
#  define RANLIB_LOCATION /usr/bin/ranlib
#endif /* RANLIB_LOCATION */

#if !defined (HAVE_UNISTD_H)
#  define HAVE_UNISTD_H
#endif /* HAVE_UNISTD_H */

#if !defined (HAVE_WAIT_H)
#  define HAVE_WAIT_H
#endif /* HAVE_WAIT_H */

#if !defined (HAVE_ALLOCA_H)
#  define HAVE_ALLOCA_H
#endif /* HAVE_ALLOCA_H */

#if !defined (HAVE_RESOURCE)
#  define HAVE_RESOURCE
#endif /* HAVE_RESOURCE */

#endif /* _SYSDEFS_H_ */
