MAN1=grog.n
CLEANADD=grog

all: grog

grog: grog.pl grog.sh
	if test -n "$(PERLPATH)" && test -f "$(PERLPATH)"; then \
	  rm -f $@; \
	  sed -e 's;/usr/bin/perl;$(PERLPATH);' $(srcdir)/grog.pl >$@; \
	else \
	  cp $(srcdir)/grog.sh grog; \
	fi
	chmod +x grog;

install_data: grog
	-test -d $(bindir) || mkdir $(bindir)
	-rm -f $(bindir)/grog
	$(INSTALL_PROGRAM) grog $(bindir)/grog
