.TH pbmtoicon 1 "31 August 1988"
.IX pbmtoicon
.SH NAME
pbmtoicon - convert a portable bitmap into a Sun icon
.SH SYNOPSIS
.B pbmtoicon
.RI [ pbmfile ]
.SH DESCRIPTION
Reads a portable bitmap as input.
Produces a Sun icon as output.
.IX Sun
.IX "Sun icon format"
.SH "SEE ALSO"
icontopbm(1), pbm(5)
.SH AUTHOR
Copyright (C) 1988 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
