.TH pbmtozinc l "02 November 1990"
.IX pbmtozinc
.SH NAME
pbmtozinc - convert a portable bitmap into a Zinc bitmap
.SH SYNOPSIS
.B pbmtozinc
.RI [ pbmfile ]
.SH DESCRIPTION
Reads a portable bitmap as input.
Produces a bitmap in the format used by the Zinc Interface Library
(ZIL) Version 1.0 as output.
.IX "Zinc Interface Library"
.SH "SEE ALSO"
pbm(5)
.SH AUTHOR
Copyright (C) 1988 by James Darrell McCauley (jdm5548@diamond.tamu.edu) and Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
.\"
.\" Zinc and Zinc Interface Library are trademarks of
.\" Zinc Software Inc., Pleasant Grove, Utah.
