.TH pbmtoxbm 1 "31 August 1988"
.IX pbmtoxbm
.SH NAME
pbmtoxbm - convert a portable bitmap into an X11 bitmap
.SH SYNOPSIS
.B pbmtoxbm
.RI [ pbmfile ]
.SH DESCRIPTION
Reads a portable bitmap as input.
Produces an X11 bitmap as output.
.IX "X bitmap"
.IX "X window system"
.SH "SEE ALSO"
pbmtox10bm(1), xbmtopbm(1), pbm(5)
.SH AUTHOR
Copyright (C) 1988 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
