.TH xbmtopbm 1 "31 August 1988"
.IX xbmtopbm
.SH NAME
xbmtopbm - convert an X11 or X10 bitmap into a portable bitmap
.SH SYNOPSIS
.B xbmtopbm
.RI [ bitmapfile ]
.SH DESCRIPTION
Reads an X11 or X10 bitmap as input.
Produces a portable bitmap as output.
.IX "X bitmap"
.IX "X window system"
.SH "SEE ALSO"
pbmtoxbm(1), pbmtox10bm(1), pbm(5)
.SH AUTHOR
Copyright (C) 1988 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
