.TH ybmtopbm 1 "06 March 1990"
.IX ybmtopbm
.SH NAME
ybmtopbm - convert a Bennet Yee "face" file into a portable bitmap
.SH SYNOPSIS
.B ybmtopbm
.RI [ facefile ]
.SH DESCRIPTION
Reads a file acceptable to the
.I face
and
.I xbm
programs by Bennet Yee (bsy+@cs.cmu.edu).
.IX face
Writes a portable bitmap as output.
.SH "SEE ALSO"
pbmtoybm(1), pbm(5), face(1), face(5), xbm(1)
.SH AUTHOR
Copyright (C) 1991 by Jamie Zawinski and Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
