#define MENU 0  	/* TREE */
#define ABOUT 1  	/* TREE */
#define M_ABOUT 12  	/* OBJECT in TREE #0 */
#define M_QUIT 21  	/* OBJECT in TREE #0 */
#define M_FASTX 22  	/* OBJECT in TREE #0 */
#define M_READF 24  	/* OBJECT in TREE #0 */
#define M_WRITEF 25  	/* OBJECT in TREE #0 */
#define M_SAVE 26  	/* OBJECT in TREE #0 */
#define M_INSERT 27  	/* OBJECT in TREE #0 */
#define M_SHELL 29  	/* OBJECT in TREE #0 */
#define M_SHCMD 30  	/* OBJECT in TREE #0 */
#define M_DOUBLE 34  	/* OBJECT in TREE #0 */
#define M_MOVE 35  	/* OBJECT in TREE #0 */
#define M_PICK 37  	/* OBJECT in TREE #0 */
#define M_CPPICK 38  	/* OBJECT in TREE #0 */
#define M_PASTE 39  	/* OBJECT in TREE #0 */
#define M_DELLIN 41  	/* OBJECT in TREE #0 */
#define M_UNDLIN 42  	/* OBJECT in TREE #0 */
#define M_GOTOLI 45  	/* OBJECT in TREE #0 */
#define M_TOPFOL 46  	/* OBJECT in TREE #0 */
#define M_BOTFOL 47  	/* OBJECT in TREE #0 */
#define M_FIND 49  	/* OBJECT in TREE #0 */
#define M_FINDRE 50  	/* OBJECT in TREE #0 */
#define M_REPLAC 51  	/* OBJECT in TREE #0 */
#define M_QUREPL 52  	/* OBJECT in TREE #0 */
#define M_OPFOLD 56  	/* OBJECT in TREE #0 */
#define M_CLFOLD 57  	/* OBJECT in TREE #0 */
#define M_ENTERF 58  	/* OBJECT in TREE #0 */
#define M_EXITFO 59  	/* OBJECT in TREE #0 */
#define M_UNFOLD 61  	/* OBJECT in TREE #0 */
#define M_CREAFO 62  	/* OBJECT in TREE #0 */
#define M_CRAUFO 63  	/* OBJECT in TREE #0 */
#define M_AHEADR 65  	/* OBJECT in TREE #0 */
#define M_FILEFO 66  	/* OBJECT in TREE #0 */
#define M_ATTFIL 67  	/* OBJECT in TREE #0 */
#define M_DESFOL 68  	/* OBJECT in TREE #0 */
#define M_DEFMAC 71  	/* OBJECT in TREE #0 */
#define M_EXEMAC 72  	/* OBJECT in TREE #0 */
#define M_FIXMAC 73  	/* OBJECT in TREE #0 */
#define M_EXE1 75  	/* OBJECT in TREE #0 */
#define M_EXE2 76  	/* OBJECT in TREE #0 */
#define M_EXE3 77  	/* OBJECT in TREE #0 */
#define M_EXE4 78  	/* OBJECT in TREE #0 */
#define M_EXE5 79  	/* OBJECT in TREE #0 */
#define M_HELP 81  	/* OBJECT in TREE #0 */
#define M_DESBIN 82  	/* OBJECT in TREE #0 */
#define M_SETLAN 84  	/* OBJECT in TREE #0 */
