/*	ENGLISH.H:	English language text strings for
                        MicroEMACS 3.11

			(C)opyright 1988 by Daniel Lawrence
*/

#define	TEXT1	"[Starting new CLI]"
#define	TEXT2	"[Cannot write filter file]"
#define	TEXT3	"[Execution failed]"
#define	TEXT4	"Shell variable TERM not defined!"
#define	TEXT5	"Terminal type not 'vt100'!"
#define	TEXT6	"\r\n\n[End]"
#define	TEXT7	"Line to GOTO: "
#define	TEXT8	"[Aborted]"
#define	TEXT9	"[Mark %d set]"
#define	TEXT10	"[Mark %d removed]"
#define	TEXT11	"No mark %d in this window"
#define	TEXT12	"[Help file is not online]"
#define	TEXT13	": describe-key "
#define	TEXT14	"Not Bound"
#define	TEXT15	": bind-to-key "
#define	TEXT16	"[No such function]"
#define	TEXT17	"Binding table FULL!"
#define	TEXT18	": unbind-key "
#define	TEXT19	"[Key not bound]"
#define	TEXT20	"Apropos string: "
#define	TEXT21	"Binding list"
#define	TEXT22	"Can not display binding list"
#define	TEXT23	"[Building binding list]"
#define	TEXT24	"Use buffer"
#define	TEXT25	"Use buffer: "
#define	TEXT26	"Kill buffer"
#define	TEXT27	"Pop buffer"
#define	TEXT28	"Buffer is being displayed"
#define	TEXT29	"Change buffer name to: "
#define	TEXT30	"ACT   Modes      Size Buffer          File"
#define	TEXT31	"         Global Modes"
#define	TEXT32	"Discard changes"
#define	TEXT33	"Encryption String: "
#define	TEXT34	"File: "
#define	TEXT35	"another user"
#define	TEXT36	"LOCK ERROR -- "
#define	TEXT37	"checking for existence of %s\n"
#define	TEXT38	"making directory %s\n"
#define	TEXT39	"creating %s\n"
#define	TEXT40	"could not create lock file"
#define	TEXT41	"pid is %ld\n"
#define	TEXT42	"reading lock file %s\n"
#define	TEXT43	"could not read lock file"
#define	TEXT44	"pid in %s is %ld\n"
#define	TEXT45	"signaling process %ld\n"
#define	TEXT46	"process exists"
#define	TEXT47	"kill was bad"
#define	TEXT48	"kill was good; process exists"
#define	TEXT49	"attempting to unlink %s\n"
#define	TEXT50	"could not remove lock file"
#define	TEXT51	"Variable to set: "
#define	TEXT52	"%%No such variable as '%s'"
#define	TEXT53	"Value: "
#define	TEXT54	"[Macro aborted]"
#define	TEXT55	"Variable to display: "
#define	TEXT56	"Variable list"
#define	TEXT57	"Can not display variable list"
#define	TEXT58	"[Building variable list]"
#define	TEXT59	"[Fill column is %d]"
#define	TEXT60	"Line %d/%d Col %d/%d Char %D/%D (%d%%) char = 0x%x"
#define	TEXT61	"<Not Used>"
#define	TEXT62	"Global mode to "
#define	TEXT63	"Mode to "
#define	TEXT64	"add: "
#define	TEXT65	"delete: "
#define	TEXT66	"No such mode!"
#define	TEXT67	"Message to write: "
#define	TEXT68	"String to insert<META>: "
#define	TEXT69	"String to overwrite<META>: "
#define	TEXT70	"[region copied]"
#define	TEXT71	"%%This buffer is already narrowed"
#define	TEXT72	"%%Must narrow at least 1 full line"
#define	TEXT73	"[Buffer is narrowed]"
#define	TEXT74	"%%This buffer is not narrowed"
#define	TEXT75	"[Buffer is widened]"
#define	TEXT76	"No mark set in this window"
#define	TEXT77	"Bug: lost mark"
#define	TEXT78	"Search"
#define	TEXT79	"Not found"
#define	TEXT80	"No pattern set"
#define	TEXT81	"Reverse search"
#define	TEXT82	"Considering %d with jump %d"
#define	TEXT83	"Its other case is %d"
#define	TEXT84	"Replace"
#define	TEXT85	"Query replace"
#define	TEXT86	"with"
#define	TEXT87	"Replace '"
#define	TEXT88	"' with '"
#define	TEXT89	"Aborted!"
#define	TEXT90	"(Y)es, (N)o, (!)Do rest, (U)ndo last, (^G)Abort, (.)Abort back, (?)Help: "
#define	TEXT91	"Empty string replaced, stopping."
#define	TEXT92	"%d substitutions"
#define	TEXT93	"%%ERROR while deleting"
#define	TEXT94	"%%Out of memory"
#define	TEXT95	"%%mceq: what is %d?"
#define	TEXT96	"%%No characters in character class"
#define	TEXT97	"%%Character class not ended"
#define	TEXT98	"No fill column set"
#define	TEXT99	"[OUT OF MEMORY]"		/* UNUSED */
#define	TEXT100	"Words %D Chars %D Lines %d Avg chars/word %f"
#define	TEXT101	"[Can not search and goto at the same time!]"
#define	TEXT102	"[Bogus goto argument]"
#define	TEXT103	"[Saving %s]"
#define	TEXT104	"Modified buffers exist. Leave anyway"
#define	TEXT105	"%%Macro already active"
#define	TEXT106	"[Start macro]"
#define	TEXT107	"%%Macro not active"
#define	TEXT108	"[End macro]"
#define	TEXT109	"[Key illegal in VIEW mode]"
#define	TEXT110	"[That command is RESTRICTED]"
#define	TEXT111	"No macro specified"
#define	TEXT112	"Macro number out of range"
#define	TEXT113	"Can not create macro"
#define	TEXT114	"Procedure name: "
#define	TEXT115	"Execute procedure: "
#define	TEXT116	"No such procedure"
#define	TEXT117	"Execute buffer: "
#define	TEXT118	"No such buffer"
#define	TEXT119	"%%Out of memory during while scan"
#define	TEXT120	"%%!BREAK outside of any !WHILE loop"
#define	TEXT121	"%%!ENDWHILE with no preceding !WHILE"
#define	TEXT122	"%%!WHILE with no matching !ENDWHILE"
#define	TEXT123	"%%Out of Memory during macro execution"
#define	TEXT124	"%%Unknown Directive"
#define	TEXT125	"Out of memory while storing macro"
#define	TEXT126	"%%Internal While loop error"
#define	TEXT127	"%%No such label"
#define	TEXT128	"(e)val exp, (c/x)ommand, (t)rack exp, (^G)abort, <SP>exec, <META> stop debug"
#define	TEXT129	"File to execute: "
#define	TEXT130	"Macro not defined"
#define	TEXT131	"Read file"
#define	TEXT132	"Insert file"
#define	TEXT133	"Find file"
#define	TEXT134	"View file"
#define	TEXT135	"[Old buffer]"
#define	TEXT136	"Buffer name: "
#define	TEXT137	"Cannot create buffer"
#define	TEXT138	"[New file]"
#define	TEXT139	"[Reading file]"
#define	TEXT140	"Read "
#define	TEXT141	"I/O ERROR, "
#define	TEXT142	"OUT OF MEMORY, "
#define	TEXT143	" line"
#define	TEXT144	"Write file: "
#define	TEXT145	"No file name"
#define	TEXT146	"Truncated file..write it out"
#define	TEXT147	"Narrowed Buffer..write it out"
#define	TEXT148	"[Writing...]"
#define	TEXT149	"[Wrote "
#define	TEXT150	", saved as "
#define	TEXT151	"Name: "
#define	TEXT152	"[No such file]"
#define	TEXT153	"[Inserting file]"
#define	TEXT154	"Inserted "
#define	TEXT155	"Cannot open file for writing"
#define	TEXT156	"Error closing file"
#define	TEXT157	"Write I/O error"
#define	TEXT158	"File read error"
#define	TEXT159	"%Need function key number"
#define	TEXT160	"%Function key number out of range"
#define	TEXT161	"Label contents: "
#define	TEXT162	" [y/n]? "
#define	TEXT163	"no default"
#define	TEXT164	"[search failed]"
#define	TEXT165	"ISearch: "
#define	TEXT166	"? Search string too long"
#define	TEXT167	"? command too long"
#define	TEXT168	"%%Can not insert string"
#define	TEXT169	"Inserted"	/* this not used anymore */
#define	TEXT170	"bug: linsert"
#define	TEXT171	"Replaced"	/* this not used anymore */
#define	TEXT172	"%%Out of memory while overwriting"
#define	TEXT173	"LOCK ERROR: Lock table full"
#define	TEXT174	"Cannot lock, out of memory"
#define	TEXT175	"LOCK"
#define	TEXT176	"File in use by "
#define	TEXT177	", overide?"
#define	TEXT178	"[can not get system error message]"
#define	TEXT179	"  About MicroEmacs"
#define	TEXT180	"%%No such resolution"
#define	TEXT181	"%%Resolution illegal for this monitor"
#define	TEXT182	"Environment variable TERM not defined!"
#define	TEXT183	"Unknown terminal type %s!"
#define	TEXT184	"termcap entry incomplete (lines)"
#define	TEXT185	"Termcap entry incomplete (columns)"
#define	TEXT186	"Incomplete termcap entry\n"
#define	TEXT187	"Terminal description too big!\n"
#define	TEXT188	"[End]"
#define	TEXT189	"Cannot find entry for terminal type.\n"
#define	TEXT190	"Check terminal type with \"SHOW TERMINAL\" or\n"
#define	TEXT191	"try setting with \"SET TERMINAL/INQUIRE\"\n"
#define	TEXT192	"The terminal type does not have enough power to run\n"
#define	TEXT193	"MicroEMACS.  Try a different terminal or check\n"
#define	TEXT194	"type with \"SHOW TERMINAL\".\n"
#define	TEXT195	"Cannot open channel to terminal.\n"
#define	TEXT196	"Cannot obtain terminal settings.\n"
#define	TEXT197	"Cannot modify terminal settings.\n"
#define	TEXT198	"I/O error (%d,%d)\n"
#define	TEXT199	"[Starting DCL]\r\n"
#define	TEXT200	"[Calling DCL]\r\n"
#define	TEXT201	"[Not available yet under VMS]"
#define	TEXT202	"Terminal type not 'vt52'or 'z19' !"
#define	TEXT203	"Window number out of range"
#define	TEXT204	"Can not delete this window"
#define	TEXT205	"Cannot split a %d line window"
#define	TEXT206	"Only one window"
#define	TEXT207	"Impossible change"
#define	TEXT208	"[No such window exists]"
#define	TEXT209	"%%Screen size out of range"
#define	TEXT210	"%%Screen width out of range"
#define	TEXT211	"Function list"
#define	TEXT212	"Can not display function list"
#define	TEXT213	"[Building function list]"
#define	TEXT214 "%%No such file as %s"
#define	TEXT215	": macro-to-key "
#define TEXT216 "Cannot read/write directories!!!"
#define TEXT217 "[Not available yet under AOS/VS]"
#define	TEXT218	"Append file: "
#define TEXT219 "%%Macro Failed"
#define	TEXT220	"Line %d/%d Col %d/%d Char %D/%D (%d%%) char = 0x%x%x"
#define TEXT221 "Too many groups"
#define TEXT222 "Group not ended"
#define	TEXT223 "%%Column origin out of range"
#define	TEXT224 "%%Row origin out of range"
#define	TEXT225 "[Switched to screen %s]"
#define	TEXT226	"%%Can not kill an executing buffer"
#define	TEXT227 "\n--- Press any key to Continue ---"
#define TEXT228 "[Kill ring cleared]"
