/* LATIN.H: 	Latin language text strings for MicroEMACS 3.11
		(C)Copyright 1991 by Daniel M. Lawrence
 		translated 1991 by Anthony Appleyard	*/

#define TEXT1   "[incipio novum CLI]"
#define TEXT2   "[non possum scribere filum percolationis]"
#define TEXT3   "[executio cecidit]"
#define TEXT4   "involucri variabilis TERM non definitus est!"
#define TEXT5   "terminalis genus non est 'vt100'!"
#define TEXT6   "\r\n\n[finis]"
#define TEXT7   "linea adeunda: "
#define TEXT8   "[interrupistis]"
#define TEXT9   "[indicium %d locavi]"
#define TEXT10  "[indicium %d delevi]"
#define TEXT11  "non est indicium %d in hac fenestra"
#define TEXT12  "[non possum invenire filum adjuvationis]"
#define TEXT13  ": explicare-clavem "
#define TEXT14  "non ligata est"
#define TEXT15  ": ligare-ad-clavem "
#define TEXT16  "[non est ista functio]"
#define TEXT17  "ligationum tabula PLENA est!"
#define TEXT18  ": laxare-clavem "
#define TEXT19  "[ista clavis non ligata est]"
#define TEXT20  "verba 'apropos'-ica: "
#define TEXT21  "tabula ligationum"
#define TEXT22  "non possum ostendere tabulam ligationum"
#define TEXT23  "[struo tabulam ligationum]"
#define TEXT24  "apotheca utenda"
#define TEXT25  "apotheca utenda: "
#define TEXT26  "apotheca occidenda"
#define TEXT27  "apotheca occidenda: "
#define TEXT28  "apotheca ostenditur"
#define TEXT29  "mutare nomen apothecae ad: "
#define TEXT30  "ACT   Modi       Magn Apothec         Filum"
#define TEXT31  "         Modi Globales"
#define TEXT32  "reicere mutationes"
#define TEXT33  "linum encryptionis: "
#define TEXT34  "filum: "
#define TEXT35  "alius utor"
#define TEXT36  "CLAUSTRI ERROR -- "
#define TEXT37  "peto sietne %s\n"
#define TEXT38  "creo directorium %s\n"
#define TEXT39  "creo %s\n"
#define TEXT40  "non potui creare filum claustri"
#define TEXT41  "pid est %ld\n"
#define TEXT42  "lego filum claustri %s\n"
#define TEXT43  "non potui legere filum claustri"
#define TEXT44  "pid in %s est %ld\n"
#define TEXT45  "signum do de processu %ld\n"
#define TEXT46  "processus exsistet"
#define TEXT47  "occisio mala erat"
#define TEXT48  "occisio bona erat; processus exsistet"
#define TEXT49  "cono solvere %s\n"
#define TEXT50  "non potui removere filum claustri"
#define TEXT51  "variabilis definiendus: "
#define TEXT52  "%%non est variabilis '%s'"
#define TEXT53  "Valor: "
#define TEXT54  "[interrupistis macronem]"
#define TEXT55  "variabilis ostendendus: "
#define TEXT56  "tabula variabilium"
#define TEXT57  "non possum variabilium ostendere tabula"
#define TEXT58  "[struo tabula variabilium]"
#define TEXT59  "[columna impletionis est %d]"
#define TEXT60  "Linea %d/%d Col %d/%d Char %D/%D (%d%%) char = 0x%x"
#define TEXT61  "%%argumentum negativum occisionus nefas est"
#define TEXT62  "modus globalis "
#define TEXT63  "modus "
#define TEXT64  "addendus: "
#define TEXT65  "delendus: "
#define TEXT66  "non est iste modus!"
#define TEXT67  "nuntius scribendus: "
#define TEXT68  "linum inserendum<META>: "
#define TEXT69  "linum superscribendum<META>: "
#define TEXT70  "[duplicavi regionem]"
#define TEXT71  "%%hic apotheca jam contracta est"
#define TEXT72  "%%debes contrahere certe 1 integra linea"
#define TEXT73  "[contraxi apothecam]"
#define TEXT74  "%%hic apotheca non contracta est"
#define TEXT75  "[dilatavi apothecam]"
#define TEXT76  "Nullum indicium definitum est in hac fenestra"
#define TEXT77  "Emacs erravit: indicium perditum est"
#define TEXT78  "petere"
#define TEXT79  "non inveni"
#define TEXT80  "Nullum exemplar definitum est"
#define TEXT81  "petere retro"
#define TEXT82  "respicio %d cum saltu %d"
#define TEXT83  "ejus alius casus est %d" /* 'instance' vel ut A/a B/b etc? */
#define TEXT84  "in loco hujus:"
#define TEXT85  "quaerens, in loco hujus:"
#define TEXT86  "ponere hoc:"
#define TEXT87  "in loco hujus: '"
#define TEXT88  "' ponere hoc: '"
#define TEXT89  "interrupistis!"
#define TEXT90  "Y=ita,N=non,!=fac rest.,U=solve prec.,^G=exire,.=exire retro,?=adjuv.: "
#define TEXT91  "linum vacuum substitui, consisto igitur."
#define TEXT92  "%d substitutiones"
#define TEXT93  "%%ERROR dum delebam"
#define TEXT94  "%%memoria est plena"
#define TEXT95  "%%mceq: quid est %d?"
#define TEXT96  "%%nulli characteres in ordone characterum"
#define TEXT97  "%%ordo characterum non finitus est"
#define TEXT98  "columna impletionis non definita est"
#define TEXT99  "[MEMORIA EST PLENA]"
#define TEXT100  "Verba %D Char'es %D Lineae %d Medium char'um/verba %f"
#define TEXT101  "[non possum simul petere et adire!]"
#define TEXT102  "[argumentum falsum adeundum]"
#define TEXT103  "[conservo %s]"
#define TEXT104  "etsi apothecae mutatae sunt, exeo"
#define TEXT105  "%%macro jam currit"
#define TEXT106  "[macronis initium]"
#define TEXT107  "%%macro non currit"
#define TEXT108  "[macronis finis]"
#define TEXT109  "[clavis illegalis est in modo VIEW]"
#define TEXT110  "[istum jussum RESTRICTUS est]"
#define TEXT111  "non denotavistis macronem"
#define TEXT112  "macronis numerus non validus est"
#define TEXT113  "non possum creare macronem"
#define TEXT114  "Procedurae nomen: "
#define TEXT115  "oboedire proceduram "
#define TEXT116  "non est ista procedura"
#define TEXT117  "oboedire apothecam: "
#define TEXT118  "non est ista apotheca"
#define TEXT119  "%%memoria est plena dum petebam de WHILE"
#define TEXT120  "%%!BREAK sine circumdante circulo !WHILE"
#define TEXT121  "%%!ENDWHILE sine coeunde !WHILE in '%s'"
#define TEXT122  "%%!WHILE sine coeunde !ENDWHILE in '%s'"
#define TEXT123  "%%memoria est plena dum oboedio macronem"
#define TEXT124  "%%directivus incognitus"
#define TEXT125  "memoria est plena dum reponabam macronem"
#define TEXT126  "%%error internalis dum oboedio circulum WHILE"
#define TEXT127  "%%non est istum labellum"
#define TEXT128  "(e)val exp,(c/x)=jussum,(t)=sequi exp,(^G)exire,<SP>=oboed,<META>=sistere debug"
#define TEXT129  "filum oboediendum: "
#define TEXT130  "iste macro non definitus est"
#define TEXT131  "filum legendum"
#define TEXT132  "filum Inserendum"
#define TEXT133  "filum inveniendum"
#define TEXT134  "filum adspiciendum"
#define TEXT135  "[apotheca vetus]"
#define TEXT136  "nomen apothecae: "
#define TEXT137  "non possum creare apothecam"
#define TEXT138  "[filum novum]"
#define TEXT139  "[lego filum]"
#define TEXT140  "legere "
#define TEXT141  "ERROR LEGENDI VEL SCRIBENDI, "
#define TEXT142  "MEMORIA PLENA EST, "
#define TEXT143  " linea"
#define TEXT144  "scribere filum: "
#define TEXT145  "nullum fili nomen"
#define TEXT146  "truncavi filum..escribetur"
#define TEXT147  "contraxi apothecam..escribetur"
#define TEXT148  "[scribo...]"
#define TEXT149  "[scripsi "
#define TEXT150  ", reposui id ut "
#define TEXT151  "nomen: "
#define TEXT152  "[non est istud filum]"
#define TEXT153  "[Insero filum]"
#define TEXT154  "Insevi "
#define TEXT155  "non possum aperire filum scriptioni"
#define TEXT156  "erravi claudens filum"
#define TEXT157  "erravi scribens"
#define TEXT158  "errevi legens filum"
#define TEXT159  "%necesse est numerus clavis functionis"
#define TEXT160  "%numerus clavis functionis invalidus est"
#define TEXT161  "quod est in labello: " /* quid est 'label' Latine recte? */
#define TEXT162  " [y(ita)/n(non)]? "
#define TEXT163  "no default"
#define TEXT164  "[petens non inveni]"
#define TEXT165  "petere incrementaliter: "
#define TEXT166  "? linum petendum nimis longum est"
#define TEXT167  "? jussus nimis longus est"
#define TEXT168  "%%non possum inserere linum"
#define TEXT169  "insevi"  /* non nunc usum */
#define TEXT170  "Emacs erravit in 'linsert'"
#define TEXT171  "substitui"  /* non nunc usum*/
#define TEXT172  "%%memoria est plena dum superscribo"
#define TEXT173  "ERROR CLAUSTRI: claustri tabula plena est"
#define TEXT174  "non possum claustrare, memoria est plena"
#define TEXT175  "CLAUSTRUM"
#define TEXT176  "filum utitur "
#define TEXT177  ", eum superare?"
#define TEXT178  "[non possum capere nuntius erroris systemae]"
#define TEXT179  "  de systema MicroEmacs"
#define TEXT180  "%%non est ista resolutio"
#define TEXT181  "%%ista resolutio nefas est in hac monitore"
#define TEXT182  "variabilis conditionis systemae TERM non definitus est!"
#define TEXT183  "Non sapio terminalium genus %s!"
#define TEXT184  "inscriptio termcap non integra est (de lineis)"
#define TEXT185  "inscriptio termcap non integra est (de columnis)"
#define TEXT186  "inscriptio termcap non integra\n"
#define TEXT187  "terminalis descriptio nimis magna est!\n"
#define TEXT188  "[finis]"
#define TEXT189  "non possum invenire inscriptionem terminalis generis.\n"
#define TEXT190  "verifica terminalis genus scribens \"SHOW TERMINAL\" aut\n"
#define TEXT191  "cona definire scribens \"SET TERMINAL/INQUIRE\"\n"
#define TEXT192  "hoc terminalium genus non potest ferre MicroEMACS.\n"
#define TEXT193  "Cona uti aliud terminale, aut verifica terminalis genus\n"
#define TEXT194  "scribens \"SHOW TERMINAL\".\n"
#define TEXT195  "non possum aperire canalem ad terminale.\n"
#define TEXT196  "non possum capere terminalis positiones.\n"
#define TEXT197  "non possum mutare terminalis positiones.\n"
#define TEXT198  "erravi legens aut scribens (%d,%d)\n"
#define TEXT199  "[incipio DCL]\r\n"
#define TEXT200  "[advoco DCL]\r\n"
#define TEXT201  "[non jam possum istud facere sub VMS]"
#define TEXT202  "terminalis genus non est 'vt52' aut 'z19' !"
#define TEXT203  "fenestrae numerus invalidus est"
#define TEXT204  "non possum delere hanc fenestram"
#define TEXT205  "non possum scindere fenestram habentem solum %d lineas"
#define TEXT206  "est una sola fenestra"
#define TEXT207  "non possum sic mutare"
#define TEXT208  "[ista fenestra non est]"
#define TEXT209  "%%ostendaculum est nimis magnum" /* quid est 'screen'? */
#define TEXT210  "%%ostendaculum est nimis latum"  /* quid est 'screen'? */
#define TEXT211  "Functionum tabula"
#define TEXT212  "non possum ostendere functionum tabulam"
#define TEXT213  "[struo functionum tabulam]"
#define TEXT214 "%%non est filum %s"
#define TEXT215  ": macro-ad-clavem "
#define TEXT216 "non possum legere vel scribere directoria!!!"
#define TEXT217 "[non possum adhuc istud facere sub AOS/VS]"
#define	TEXT218	"Append file: "
#define TEXT219 "%%Macro Failed"
#define	TEXT220	"Linea %d/%d Col %d/%d Char %D/%D (%d%%) char = 0x%x%x"
#define TEXT221 "Too many groups"
#define TEXT222 "Group not ended"
#define	TEXT223 "%%Column origin out of range"
#define	TEXT224 "%%Row origin out of range"
#define	TEXT225 "[Switched to screen %s]"
#define	TEXT226	"%%Can not kill an executing buffer"
#define	TEXT227 "\n--- Press any key to Continue ---"
#define TEXT228 "[Kill ring cleared]"
