/*	PLATIN.H	Pig Latin Text strings for
                        MicroEMACS 3.11

			(C)opyright 1988 by Daniel Lawrence
			translated by Daniel Lawrence (and MicroEMACS)
*/

#define	TEXT1	"[Tartingsay ewnay LICAY]"
#define	TEXT2	"[Annotcay riteway ilterfay ilefay]"
#define	TEXT3	"[Executionway ailedfay]"
#define	TEXT4	"Hellsay ariablevay ERMTAY otnay efinedday!"
#define	TEXT5	"Erminaltay ypetay otnay 't100vay'!"
#define	TEXT6	"\r\n\n[Endway]"
#define	TEXT7	"Inelay otay OTOGAY: "
#define	TEXT8	"[Abortedway]"
#define	TEXT9	"[Arkmay %d etsay]"
#define	TEXT10	"[Arkmay %d emovedray]"
#define	TEXT11	"Onay arkmay %d inway histay indowway"
#define	TEXT12	"[Elphay ilefay isway otnay onlineway]"
#define	TEXT13	": escribeday-eykay "
#define	TEXT14	"Otnay Oundbay"
#define	TEXT15	": indbay-otay-eykay "
#define	TEXT16	"[Onay uchsay unctionfay]"
#define	TEXT17	"Indingbay abletay ULLFAY!"
#define	TEXT18	": unbindway-eykay "
#define	TEXT19	"[Eykay otnay oundbay]"
#define	TEXT20	"Aproposway tringsay: "
#define	TEXT21	"Indingbay istlay"
#define	TEXT22	"Ancay otnay isplayday indingbay istlay"
#define	TEXT23	"[Uildingbay indingbay istlay]"
#define	TEXT24	"Useway ufferbay"
#define	TEXT25	"Useway ufferbay: "
#define	TEXT26	"Illkay ufferbay"
#define	TEXT27	"Oppay ufferbay"
#define	TEXT28	"Ufferbay isway eingbay isplayedday"
#define	TEXT29	"Hangecay ufferbay amenay otay: "
#define	TEXT30	"ACT   Modes      Size Buffer          File"
#define	TEXT31	"         Global Modes"
#define	TEXT32	"Iscardday hangescay"
#define	TEXT33	"Encryptionway Tringsay: "
#define	TEXT34	"Ilefay: "
#define	TEXT35	"anotherway userway"
#define	TEXT36	"OCKLAY ERRORWAY -- "
#define	TEXT37	"heckingcay orfay existenceway ofway %s\n"
#define	TEXT38	"akingmay irectoryday %s\n"
#define	TEXT39	"reatingcay %s\n"
#define	TEXT40	"ouldcay otnay reatecay ocklay ilefay"
#define	TEXT41	"idpay isway %ld\n"
#define	TEXT42	"eadingray ocklay ilefay %s\n"
#define	TEXT43	"ouldcay otnay eadray ocklay ilefay"
#define	TEXT44	"idpay inway %s isway %ld\n"
#define	TEXT45	"ignalingsay rocesspay %ld\n"
#define	TEXT46	"rocesspay existsway"
#define	TEXT47	"illkay asway adbay"
#define	TEXT48	"illkay asway oodgay; rocesspay existsway"
#define	TEXT49	"attemptingway otay unlinkway %s\n"
#define	TEXT50	"ouldcay otnay emoveray ocklay ilefay"
#define	TEXT51	"Ariablevay otay etsay: "
#define	TEXT52	"%%Onay uchsay ariablevay asway '%s'"
#define	TEXT53	"Aluevay: "
#define	TEXT54	"[Acromay abortedway]"
#define	TEXT55	"Ariablevay otay isplayday: "
#define	TEXT56	"Ariablevay istlay"
#define	TEXT57	"Ancay otnay isplayday ariablevay istlay"
#define	TEXT58	"[Uildingbay ariablevay istlay]"
#define	TEXT59	"[Illfay olumncay isway %d]"
#define	TEXT60	"Inelay %d/%d Olcay %d/%d Archay %D/%D (%d%%) archay = 0x%x"
#define	TEXT61	"<OTNAY USEDWAY>"
#define	TEXT62	"Lobalgay odemay otay "
#define	TEXT63	"Odemay otay "
#define	TEXT64	"addway: "
#define	TEXT65	"eleteday: "
#define	TEXT66	"Onay uchsay odemay!"
#define	TEXT67	"Essagemay otay riteway: "
#define	TEXT68	"Tringsay otay insertway<META>: "
#define	TEXT69	"Tringsay otay overwriteway<META>: "
#define	TEXT70	"[egionray opiedcay]"
#define	TEXT71	"%%Histay ufferbay isway alreadyway arrowednay"
#define	TEXT72	"%%Ustmay arrownay atway eastlay 1 ullfay inelay"
#define	TEXT73	"[Ufferbay isway arrowednay]"
#define	TEXT74	"%%Histay ufferbay isway otnay arrowednay"
#define	TEXT75	"[Ufferbay isway idenedway]"
#define	TEXT76	"Onay arkmay etsay inway histay indowway"
#define	TEXT77	"Ugbay: ostlay arkmay"
#define	TEXT78	"Earchsay"
#define	TEXT79	"Otnay oundfay"
#define	TEXT80	"Onay atternpay etsay"
#define	TEXT81	"Everseray earchsay"
#define	TEXT82	"Onsideringcay %d ithway umpjay %d"
#define	TEXT83	"Itsway otherway asecay isway %d"
#define	TEXT84	"Eplaceray"
#define	TEXT85	"Ueryqay eplaceray"
#define	TEXT86	"ithway"
#define	TEXT87	"Eplaceray '"
#define	TEXT88	"' ithway '"
#define	TEXT89	"Abortedway!"
#define	TEXT90	"(Y)es, (N)o, (!)Do rest, (U)ndo last, (^G)Abort, (.)Abort back, (?)Help: "
#define	TEXT91	"Emptyway tringsay eplacedray, toppingsay."
#define	TEXT92	"%d ubstitutionssay"
#define	TEXT93	"%%ERRORWAY hileway eletingday"
#define	TEXT94	"%%Outway ofway emorymay"
#define	TEXT95	"%%mceq: hatway isway %d?"
#define	TEXT96	"%%Onay haracterscay inway haractercay lasscay"
#define	TEXT97	"%%Haractercay lasscay otnay endedway"
#define	TEXT98	"Onay illfay olumncay etsay"
#define	TEXT99	"[OUTWAY OFWAY EMORYMAY]"
#define	TEXT100	"Ordsway %D Harscay %D Ineslay %d Avgway harscay/ordway %f"
#define	TEXT101	"[Ancay otnay earchsay andway otogay atway hetay amesay imetay!]"
#define	TEXT102	"[Ogusbay otogay argumentway]"
#define	TEXT103	"[Avingsay %s]"
#define	TEXT104	"Odifiedmay uffersbay existway. Eavelay anywayway"
#define	TEXT105	"%%Acromay alreadyway activeway"
#define	TEXT106	"[Tartsay acromay]"
#define	TEXT107	"%%Acromay otnay activeway"
#define	TEXT108	"[Endway acromay]"
#define	TEXT109	"[Eykay illegalway inway Iewvay odemay]"
#define	TEXT110	"[Hattay ommandcay isway ESTRICTEDRAY]"
#define	TEXT111	"Onay acromay pecifiedsay"
#define	TEXT112	"Acromay umbernay outway ofway angeray"
#define	TEXT113	"Ancay otnay reatecay acromay"
#define	TEXT114	"Rocedurepay amenay: "
#define	TEXT115	"Executeway rocedurepay: "
#define	TEXT116	"Onay uchsay rocedurepay"
#define	TEXT117	"Executeway ufferbay: "
#define	TEXT118	"Onay uchsay ufferbay"
#define	TEXT119	"%%Outway ofway emorymay uringday hileway cansay"
#define	TEXT120	"%%!REAKBAY outsideway ofway anyway !HILEWAY ooplay"
#define	TEXT121	"%%!ENDWHILEWAY ithway onay recedingpay !HILEWAY"
#define	TEXT122	"%%!HILEWAY ithway onay atchingmay !ENDWHILEWAY"
#define	TEXT123	"%%Outway ofway Emorymay uringday acromay executionway"
#define	TEXT124	"%%Unknownway Irectiveday"
#define	TEXT125	"Outway ofway emorymay hileway toringsay acromay"
#define	TEXT126	"%%Internalway Hileway ooplay errorway"
#define	TEXT127	"%%Onay uchsay abellay"
#define	TEXT128	"(e)val exp, (c/x)ommand, (t)rack exp, (^G)abort, <SP>exec, <META> stop debug"
#define	TEXT129	"Ilefay otay executeway: "
#define	TEXT130	"Acromay otnay efinedday"
#define	TEXT131	"Eadray ilefay"
#define	TEXT132	"Insertway ilefay"
#define	TEXT133	"Indfay ilefay"
#define	TEXT134	"Iewvay ilefay"
#define	TEXT135	"[Oldway ufferbay]"
#define	TEXT136	"Ufferbay amenay: "
#define	TEXT137	"Annotcay reatecay ufferbay"
#define	TEXT138	"[Ewnay ilefay]"
#define	TEXT139	"[Eadingray ilefay]"
#define	TEXT140	"Eadray "
#define	TEXT141	"I/O ERRORWAY, "
#define	TEXT142	"OUTWAY OFWAY EMORYMAY, "
#define	TEXT143	" inelay"
#define	TEXT144	"Riteway ilefay: "
#define	TEXT145	"Onay ilefay amenay"
#define	TEXT146	"Runcatedtay ilefay..riteway itway outway"
#define	TEXT147	"Arrowednay Ufferbay..riteway itway outway"
#define	TEXT148	"[Ritingway...]"
#define	TEXT149	"[Roteway "
#define	TEXT150	", avedsay asway "
#define	TEXT151	"Amenay: "
#define	TEXT152	"[Onay uchsay ilefay]"
#define	TEXT153	"[Insertingway ilefay]"
#define	TEXT154	"Insertedway "
#define	TEXT155	"Annotcay openway ilefay orfay ritingway"
#define	TEXT156	"Errorway losingcay ilefay"
#define	TEXT157	"Riteway I/O errorway"
#define	TEXT158	"Ilefay eadray errorway"
#define	TEXT159	"%Eednay unctionfay eykay umbernay"
#define	TEXT160	"%Unctionfay eykay umbernay outway ofway angeray"
#define	TEXT161	"Abellay ontentscay: "
#define	TEXT162	" [y/n]? "
#define	TEXT163	"onay efaultday"
#define	TEXT164	"[earchsay ailedfay]"
#define	TEXT165	"Isearchway: "
#define TEXT166	"? Earchsay tringsay ootay onglay"
#define	TEXT167	"? ommandcay ootay onglay"
#define	TEXT168	"%%Ancay otnay insertway tringsay"
#define	TEXT169	"Insertedway"	/* this not used anymore */
#define	TEXT170	"ugbay: insertlay"
#define	TEXT171	"Eplacedray"	/* this not used anymore */
#define	TEXT172	"%%Outway ofway emorymay hileway overwritingway"
#define	TEXT173	"OCKLAY ERRORWAY: Ocklay abletay ullfay"
#define	TEXT174	"Annotcay ocklay, outway ofway emorymay"
#define TEXT175	"OCKLAY"
#define	TEXT176	"Ilefay inway useway ybay "
#define	TEXT177	", overideway?"
#define	TEXT178	"[ancay otnay etgay ystemsay errorway essagemay]"
#define	TEXT179	"  Aboutway Icroemacsmay"
#define	TEXT180	"%%Onay uchsay esolutionray"
#define	TEXT181	"%%Esolutionray illegalway orfay histay onitormay"
#define	TEXT182	"Environmentway ariablevay ERMTAY otnay efinedday!"
#define TEXT183	"Unknownway erminaltay ypetay %s!"
#define	TEXT184	"ermcaptay entryway incompleteway (ineslay)"
#define	TEXT185	"Ermcaptay entryway incompleteway (olumnscay)"
#define	TEXT186	"Incompleteway ermcaptay entryway\n"
#define	TEXT187	"Erminaltay escriptionday ootay igbay!\n"
#define	TEXT188	"[Endway]"
#define	TEXT189	"Annotcay indfay entryway orfay erminaltay ypetay.\n"
#define	TEXT190	"Heckcay erminaltay ypetay ithway \"SHOW TERMINAL\" orway\n"
#define	TEXT191	"rytay ettingsay ithway \"SET TERMINAL/INQUIRE\"\n"
#define	TEXT192	"Hetay erminaltay ypetay oesday otnay avehay enoughway owerpay otay unray\n"
#define	TEXT193	"IcroEMACSMAY.  Rytay away ifferentday erminaltay orway heckcay\n"
#define	TEXT194	"ypetay ithway \"SHOW TERMINAL\".\n"
#define	TEXT195	"Annotcay openway hannelcay otay erminaltay.\n"
#define	TEXT196	"Annotcay obtainway erminaltay ettingssay.\n"
#define	TEXT197	"Annotcay odifymay erminaltay ettingssay.\n"
#define	TEXT198	"I/O errorway (%d,%d)\n"
#define	TEXT199	"[Tartingsay DCL]\r\n"
#define	TEXT200	"[Allingcay DCL]\r\n"
#define	TEXT201	"[Otnay availableway etyay underway VMS]"
#define	TEXT202	"Erminaltay ypetay otnay 'vt52'orway 'z19' !"
#define	TEXT203	"Indowway umbernay outway ofway angeray"
#define	TEXT204	"Ancay otnay eleteday histay indowway"
#define	TEXT205	"Annotcay plitsay away %d inelay indowway"
#define	TEXT206	"Onlyway oneway indowway"
#define	TEXT207	"Impossibleway hangecay"
#define	TEXT208	"[Onay uchsay indowway existsway]"
#define	TEXT209	"%%Creensay izesay outway ofway angeray"
#define	TEXT210	"%%Creensay idthway outway ofway angeray"
#define	TEXT211	"Unctionfay istlay"
#define	TEXT212	"Ancay otnay isplayday unctionfay istlay"
#define	TEXT213	"[Uildingbay unctionfay istlay]"
#define	TEXT214 "%%Onay uchsay ilefay asway %s"
#define	TEXT215	": acromay-otay-eykay "
#define TEXT216 "Annotcay eadray/riteway irectoriesday!!!"
#define TEXT217 "[Otnay availableway et yay underway AOS/VS]"
#define	TEXT218	"Appendway ilefay: "
#define TEXT219 "%%Acromay Ailedfay"
#define	TEXT220	"Inelay %d/%d Olcay %d/%d Archay %D/%D (%d%%) archay = 0x%x%x"
#define TEXT221 "Ootay anymay oupsgray"
#define TEXT222 "Oupgray otnay endedway"
#define	TEXT223 "%%Column origin out of range"
#define	TEXT224 "%%Row origin out of range"
#define	TEXT225 "[Switched to screen %s]"
#define	TEXT226	"%%Can not kill an executing buffer"
#define	TEXT227 "\n--- Press any key to Continue ---"
#define TEXT228 "[Illkay ingray earedclay]"

