/*	SPANISH.H:	Spanish language text strings for
                        MicroEMACS 3.11

			(C)opyright 1988 by Daniel Lawrence
			Translated by Jose Berrios
*/

#define	TEXT1	"[Empezando un nuevo CLI]"
#define	TEXT2	"[No puedo escribir el filtro de los archivos]"
#define	TEXT3	"[Execution failed]"
#define	TEXT4	"Variable TERM del caracol indefinido!"
#define	TEXT5	"Tipo de terminal no 'vt100'!"
#define	TEXT6	"\r\n\n[Fin]"
#define	TEXT7	"Ir a que linea: "
#define	TEXT8	"[Aborted]"
#define	TEXT9	"[Marka %d puesta]"
#define	TEXT10	"[Marka %d removida]"
#define	TEXT11	"En esta ventana no hay una marka %d"
#define	TEXT12	"[Archivo para ayuda de sesion no esta presente]"
#define	TEXT13	": describe-la tecla "
#define	TEXT14	"No esta declarada"
#define	TEXT15	": declara a esta tecla"
#define	TEXT16	"[Esa funccion no la hay!]"
#define	TEXT17	"Tabla de declaraciones esta llena!" 
#define	TEXT18	": unbind-key "
#define	TEXT19	"[Tecla no declarada]"
#define	TEXT20	"Apropos string: "
#define	TEXT21	"Lista de declaraciones"
#define	TEXT22	"No puedo presentar la lista de declaraciones"
#define	TEXT23	"[Construyendo la lista de declaraciones]"
#define	TEXT24	"Use buffer"
#define	TEXT25	"Use buffer: "
#define	TEXT26	"Kill buffer"
#define	TEXT27	"Pop buffer"
#define	TEXT28	"Buffer is being displayed"
#define	TEXT29	"Change buffer name to: "
#define	TEXT30	"ACT   Modes      Size Buffer          File"
#define	TEXT31	"         Global Modes"
#define	TEXT32	"Discard changes"
#define	TEXT33	"Encryption String: "
#define	TEXT34	"Archivo: "
#define	TEXT35	"otro usador"
#define	TEXT36	"LOCK ERROR -- "
#define	TEXT37	"chequeando la existencia de %s\n"
#define	TEXT38	"creando un directorio %s\n"
#define	TEXT39	"creando %s\n"
#define	TEXT40	"could not create lock file"
#define	TEXT41	"pid is %ld\n"
#define	TEXT42	"reading lock file %s\n"
#define	TEXT43	"could not read lock file"
#define	TEXT44	"pid in %s is %ld\n"
#define	TEXT45	"senalando el proceso %ld\n"
#define	TEXT46	"proceso existe"
#define	TEXT47	"kill was bad"
#define	TEXT48	"kill was good; process exists"
#define	TEXT49	"attempting to unlink %s\n"
#define	TEXT50	"could not remove lock file"
#define	TEXT51	"Variable to set: "
#define	TEXT52	"%%No such variable as '%s'"
#define	TEXT53	"Value: "
#define	TEXT54	"[Macro aborted]"
#define	TEXT55	"Ensenar que variable: "
#define	TEXT56	"Lista de variables"
#define	TEXT57	"No puedo ensenar la lista de variables"
#define	TEXT58	"[Creando lista de variables]"
#define	TEXT59	"[La columna para llenar es %d]"
#define	TEXT60	"Linea %d/%d Columna %d/%d Letra %D/%D (%d%%) Letra = 0x%x"
#define	TEXT61	"<NOT USED>"
#define	TEXT62	"Modo global a"
#define	TEXT63	"Modo a"
#define	TEXT64	"anade: "
#define	TEXT65	"borra: "
#define	TEXT66	"No hay esa clase de modo!"
#define	TEXT67	"Mensaje para escribir: "
#define	TEXT68	"String to insert<META>: "
#define	TEXT69	"String to overwrite<META>: "
#define	TEXT70	"[region copied]"
#define	TEXT71	"%%This buffer is already narrowed"
#define	TEXT72	"%%Must narrow at least 1 full line"
#define	TEXT73	"[Buffer is narrowed]"
#define	TEXT74	"%%This buffer is not narrowed"
#define	TEXT75	"[Buffer is widened]"
#define	TEXT76	"No hay una marka puesta en esta ventana"
#define	TEXT77	"Bug: lost mark"
#define	TEXT78	"Busca"
#define	TEXT79	"No aparece"
#define	TEXT80	"No pattern set"
#define	TEXT81	"Buscar en reversa"
#define	TEXT82	"Considerar %d con un brinco %d"
#define	TEXT83	"Su otro caso es %d"
#define	TEXT84	"Renplasa"
#define	TEXT85	"Query replace"
#define	TEXT86	"con"
#define	TEXT87	"Renplasa '"
#define	TEXT88	"' con '"
#define	TEXT89	"Aborted!"
#define	TEXT90	"(Y)es, (N)o, (!)Do rest, (U)ndo last, (^G)Abort, (.)Abort back, (?)Help: "
#define	TEXT91	"Empty string replaced, stopping."
#define	TEXT92	"%d substituciones"
#define	TEXT93	"%%ERROR mientras borrando"
#define	TEXT94	"%%Fuera de memoria"
#define	TEXT95	"%%mceq: que es %d?"
#define	TEXT96	"%%No characters in character class"
#define	TEXT97	"%%Character class not ended"
#define	TEXT98	"No fill column set"
#define	TEXT99	"[OUT OF MEMORY]"
#define	TEXT100	"Words %D Chars %D Lines %d Avg chars/word %f"
#define	TEXT101	"[No pueado buscar y ir a la misma vez!]"
#define	TEXT102	"[Confuso argumento]"
#define	TEXT103	"[Guardando %s]"
#define	TEXT104	"Modified buffers exist. Leave anyway"
#define	TEXT105	"%%Macro already active"
#define	TEXT106	"[Start macro]"
#define	TEXT107	"%%Macro not active"
#define	TEXT108	"[End macro]"
#define	TEXT109	"[Key illegal in VIEW mode]"
#define	TEXT110	"[That command is RESTRICTED]"
#define	TEXT111	"No macro specified"
#define	TEXT112	"Macro number out of range"
#define	TEXT113	"Can not create macro"
#define	TEXT114	"Nompre del procedimiento: "
#define	TEXT115	"Procedimiento a ejecutar: "
#define	TEXT116	"No hay ese procedimiento"
#define	TEXT117	"Execute buffer: "
#define	TEXT118	"No such buffer"
#define	TEXT119	"%%Out of memory during while scan"
#define	TEXT120	"%%!BREAK outside of any !WHILE loop"
#define	TEXT121	"%%!ENDWHILE with no preceding !WHILE"
#define	TEXT122	"%%!WHILE with no matching !ENDWHILE"
#define	TEXT123	"%%Out of Memory during macro execution"
#define	TEXT124	"%%Directivo desconocido"
#define	TEXT125	"Out of memory while storing macro"
#define	TEXT126	"%%Internal While loop error"
#define	TEXT127	"%%No such label"
#define	TEXT128	"(e)val exp, (c/x)ommand, (t)rack exp, (^G)abort, <SP>exec, <META> stop debug"
#define	TEXT129	"Ejecutar que archivo: "
#define	TEXT130	"Macro not defined"
#define	TEXT131	"Leer que archivo"
#define	TEXT132	"Insertar que archivo"
#define	TEXT133	"Buscar archivo"
#define	TEXT134	"Mirrar que archivo"
#define	TEXT135	"[Old buffer]"
#define	TEXT136	"Buffer name: "
#define	TEXT137	"Cannot create buffer"
#define	TEXT138	"[Nuevo archivo]"
#define	TEXT139	"[Leyendo archivo]"
#define	TEXT140	"Leyendo "
#define	TEXT141	"I/O ERROR, "
#define	TEXT142	"Fueara de memoria, "
#define	TEXT143	" linea"
#define	TEXT144	"Escribir a que archivo: "
#define	TEXT145	"No tengo el nombre del archivo"
#define	TEXT146	"Truncated file..write it out"
#define	TEXT147	"Narrowed Buffer..write it out"
#define	TEXT148	"[Escribiendo...]"
#define	TEXT149	"[Escribi "
#define	TEXT150	", guarde como "
#define	TEXT151	"Nombre: "
#define	TEXT152	"[No hay ese archivo]"
#define	TEXT153	"[Insertando archivo]"
#define	TEXT154	"Indertando "
#define	TEXT155	"No puedo abrir el archivo para escribir"
#define	TEXT156	"Error cerrando el archivo"
#define	TEXT157	"Write I/O error"
#define	TEXT158	"File read error"
#define	TEXT159	"%Necesito el numera de la tecla de funcion"
#define	TEXT160	"%Tecla de funcion esta fuera de los limites"
#define	TEXT161	"Label contents: "
#define	TEXT162	" [y/n]? "
#define	TEXT163	"no default"
#define	TEXT164	"[search failed]"
#define	TEXT165	"ISearch: "
#define	TEXT166	"? Search string too long"
#define	TEXT167	"? command too long"
#define	TEXT168	"%%Can not insert string"
#define	TEXT169	"Inserted"	/* this not used anymore */
#define	TEXT170	"bug: linsert"
#define	TEXT171	"Replaced"	/* this not used anymore */
#define	TEXT172	"%%Out of memory while overwriting"
#define	TEXT173	"LOCK ERROR: Lock table full"
#define	TEXT174	"Cannot lock, out of memory"
#define	TEXT175	"LOCK"
#define	TEXT176	"File in use by "
#define	TEXT177	", overide?"
#define	TEXT178	"[can not get system error message]"
#define	TEXT179	"  Acerca de MicroEmacs"
#define	TEXT180	"%%No such resolution"
#define	TEXT181	"%%Resolution illegal for this monitor"
#define	TEXT182	"Environment variable TERM not defined!"
#define	TEXT183	"Unknown terminal type %s!"
#define	TEXT184	"termcap entry incomplete (lines)"
#define	TEXT185	"Termcap entry incomplete (columns)"
#define	TEXT186	"Incomplete termcap entry\n"
#define	TEXT187	"Terminal description too big!\n"
#define	TEXT188	"[End]"
#define	TEXT189	"Cannot find entry for terminal type.\n"
#define	TEXT190	"Check terminal type with \"SHOW TERMINAL\" or\n"
#define	TEXT191	"try setting with \"SET TERMINAL/INQUIRE\"\n"
#define	TEXT192	"The terminal type does not have enough power to run\n"
#define	TEXT193	"MicroEMACS.  Try a different terminal or check\n"
#define	TEXT194	"type with \"SHOW TERMINAL\".\n"
#define	TEXT195	"No puedo abrir un cannal hacia la terminal.\n"
#define	TEXT196	"No puedo obtener los terminal settings.\n"
#define	TEXT197	"Cannot modify terminal settings.\n"
#define	TEXT198	"I/O error (%d,%d)\n"
#define	TEXT199	"[Starting DCL]\r\n"
#define	TEXT200	"[Calling DCL]\r\n"
#define	TEXT201	"[Not available yet under VMS]"
#define	TEXT202	"Tipo de terminal no 'vt52'o 'z19' !"
#define	TEXT203	"Numero de ventana fuera de los limites"
#define	TEXT204	"No puedo borrar esta ventana"
#define	TEXT205	"Cannot split a %d line window"
#define	TEXT206	"Solo una ventana"
#define	TEXT207	"Cambio imposible"
#define	TEXT208	"[No such window exists]"
#define	TEXT209	"%%El tamano de la ventana esta fuera de los limites"
#define	TEXT210	"%%El ancho de la pantalla esta fuera de los limites"
#define	TEXT211	"Lista de funccions"
#define	TEXT212	"No puedo ensenar la lista de funccions"
#define	TEXT213	"[Creando lista de funccions]"
#define	TEXT214 "%%No such file as %s"
#define	TEXT215	": declara a esta macro"
#define TEXT216 "Cannot read/write directories!!!"
#define TEXT217 "[Not available yet under AOS/VS]"
#define	TEXT218	"Append file: "
#define TEXT219 "%%Macro Failed"
#define	TEXT220	"Linea %d/%d Columna %d/%d Letra %D/%D (%d%%) Letra = 0x%x%x"
#define TEXT221 "Too many groups"
#define TEXT222 "Group not ended"
#define	TEXT223 "%%Column origin out of range"
#define	TEXT224 "%%Row origin out of range"
#define	TEXT225 "[Switched to screen %s]"
#define	TEXT226	"%%Can not kill an executing buffer"
#define	TEXT227 "\n--- Press any key to Continue ---"
#define TEXT228 "[Kill ring cleared]"

