.TH giftoppm 1 "21 December 1990"
.IX giftoppm
.SH NAME
giftoppm - convert a GIF file into a portable pixmap
.SH SYNOPSIS
.B giftoppm
.RB [ -verbose ]
.RB [ -comments ]
.RB [ -image
.IR N ]
.RI [ GIFfile ]
.SH DESCRIPTION
Reads a GIF file for input, and outputs portable pixmap.
.IX GIF
.SH OPTIONS
.TP
.B -verbose
Produces verbose output about the GIF file input.
.TP
.B -comments
Only outputs GIF89 comment fields.
.TP
.B -image
Output the specified gif image from the
input gif archive (where
.I N
is '1', '2', '20'...).
Normally there is only one image per file, so this option
is not needed.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH BUGS
This does not correctly handle the Plain Text Extension of the GIF89
standard, since I did not have any example input files containing them.
.SH "SEE ALSO"
ppmtogif(1), ppm(5)
.SH AUTHOR
Copyright (c) 1990 by David Koblas (koblas@mips.com)
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and that
.\" both that copyright notice and this permission notice appear in
.\" supporting documentation.
