.TH imgtoppm 1 "05 September 1989"
.IX imgtoppm
.SH NAME
imgtoppm - convert an Img-whatnot file into a portable pixmap
.SH SYNOPSIS
.B imgtoppm
.RI [ imgfile ]
.SH DESCRIPTION
Reads an Img-whatnot file as input.
Produces a portable pixmap as output.
The Img-whatnot toolkit is available for FTP on venera.isi.edu,
along with numerous images in this format.
.IX Img-whatnot
.SH "SEE ALSO"
ppm(5)
.SH AUTHOR
Based on a simple conversion program posted to comp.graphics by Ed Falk.

Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
