.TH mtvtoppm 1 "02 February 1989"
.IX mtvtoppm
.SH NAME
mtvtoppm - convert output from the MTV or PRT ray tracers into a portable pixmap
.SH SYNOPSIS
.B mtvtoppm
.RI [ mtvfile ]
.SH DESCRIPTION
Reads an input file from Mark VanDeWettering's MTV ray tracer.
.IX "MTV raytracer"
Produces a portable pixmap as output.
.PP
The PRT raytracer also produces this format.
.IX "PRT raytracer"
.SH "SEE ALSO"
ppm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
