.TH ppmdither 1 "14 July 1991"
.IX ppmdither
.SH NAME
ppmdither - ordered dither for color images
.SH SYNOPSIS
.B ppmdither
.RB [ -dim
.IR dimension ]
.RB [ -red
.IR shades ]
.RB [ -green
.IR shades ]
.RB [ -blue
.IR shades ]
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap as input, and applies dithering to it to reduce
the number of colors used down to the specified number of shades for
each primary.
The default number of shades is red=5, green=9, blue=5, for
a total of 225 colors.
To convert the image to a binary rgb format 
suitable for color printers, use -red 2 -green 2 -blue 2.
The maximum
number of colors that can be used is 256 and can be computed as the 
product of the number of red, green and blue shades.
.SH OPTIONS
.TP 14
.BI -dim " dimension"
The size of the dithering matrix.
Must be a power of 2.
.TP 14
.BI -red " shades"
The number of red shades to be used; minimum of 2.
.TP 14
.BI -green " shades"
The number of green shades to be used; minimum of 2.
.TP 14
.BI -blue " shades"
The number of blue shades to be used; minimum of 2.
.SH "SEE ALSO"
pnmdepth(1), ppmquant(1), ppm(5)
.SH AUTHOR
Copyright (C) 1991 by Christos Zoulas.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
