.TH ppmmake 1 "24 September 1991"
.IX ppmmake
.SH NAME
ppmmake - create a pixmap of a specified size and color
.SH SYNOPSIS
.B ppmmake
.I color width height
.SH DESCRIPTION
Produces a portable pixmap of the specified color, width, and height.
.IX "generating pixmaps"
.PP
The color can be specified in five ways:
.IX "specifying colors"
.TP 
o
A name, assuming
that a pointer to an X11-style color names file was compiled in.
.TP 
o
An X11-style hexadecimal specifier: rgb:r/g/b, where r g and b are
each 1- to 4-digit hexadecimal numbers.
.TP 
o
An X11-style decimal specifier: rgbi:r/g/b, where r g and b are
floating point numbers between 0 and 1.
.TP 
o
For backwards compatibility, an old-X11-style hexadecimal
number: #rgb, #rrggbb, #rrrgggbbb, or #rrrrggggbbbb.
.TP 
o
For backwards compatibility, a triplet of numbers
separated by commas: r,g,b, where r g and b are
floating point numbers between 0 and 1.
(This style was added before MIT came up with the similar rgbi style.)
.SH "SEE ALSO"
ppm(5), pbmmake(1)
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
