.TH ppmpat 1 "04 September 1989"
.IX ppmpat
.SH NAME
ppmpat - make a pretty pixmap
.SH SYNOPSIS
.B ppmpat
.BR -gingham2 | -g2 | -gingham3 |
.BR -g3 | -madras | -tartan |
.BR -poles | -squig | -camo |
.BR -anticamo
.I width height
.SH DESCRIPTION
Produces a portable pixmap of the specified width and height,
with a pattern in it.
.IX "generating pixmaps"
.PP
This program is mainly to demonstrate use of the ppmdraw routines, a
simple but powerful drawing library.
See the ppmdraw.h include file for more info on using these routines.
Still, some of the patterns can be rather pretty.
If you have a color workstation, something like
.B "ppmpat -squig 300 300" | "ppmquant 128"
should generate a nice background.
.SH OPTIONS
.PP
The different flags specify various different pattern types:
.TP
.B -gingham2
A gingham check pattern.  Can be tiled.
.TP
.B -gingham3
A slightly more complicated gingham.  Can be tiled.
.TP
.B -madras
A madras plaid.  Can be tiled.
.TP
.B -tartan
A tartan plaid.  Can be tiled.
.TP
.B -poles
Color gradients centered on randomly-placed poles.
May need to be run through
.IR ppmquant .
.TP
.B -squig
Squiggley tubular pattern.  Can be tiled.
May need to be run through
.IR ppmquant .
.TP
.B -camo
Camouflage pattern.
May need to be run through
.IR ppmquant .
.TP
.B -anticamo
Anti-camouflage pattern - like -camo, but ultra-bright colors.
May need to be run through
.IR ppmquant .
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH REFERENCES
Some of the patterns are from "Designer's Guide to Color 3" by Jeanne Allen.
.SH "SEE ALSO"
pnmtile(1), ppmquant(1), ppm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
