.TH ppmtouil 1 "31 August 1990"
.IX ppmtouil
.SH NAME
ppmtouil - convert a portable pixmap into a Motif UIL icon file
.SH SYNOPSIS
.B ppmtouil
.RB [ -name
.IR uilname ]
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap as input.
Produces a Motif UIL icon file as output.
.IX Motif
.IX UIL
.IX "X window system"
.PP
If the program was compiled with an rgb database specified, and
a RGB value from the ppm input matches a RGB value from the database,
then the corresponding color name mnemonic is printed in the UIL's colormap.
If no rgb database was compiled in, or if the RGB values don't match,
then the color
will be printed with the #RGB, #RRGGBB, #RRRGGGBBB, or #RRRRGGGGBBBB
hexadecimal format.
.SH OPTIONS
.TP
.B -name
Allows you to specify the prefix string which is printed
in the resulting UIL output.  If not specified, will default to the
filename (without extension) of the ppmfile argument.
If
.B -name
is not specified and no ppmfile
is specified (i.e. piped input), the prefix string will default to
the string "noname".
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
ppm(5)
.SH AUTHOR
Converted by Jef Poskanzer from ppmtoxpm.c, which is
Copyright (C) 1990 by Mark W. Snitily
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
