.TH ppmtopuzz 1 "22 August 1990"
.IX ppmtopuzz
.SH NAME
ppmtopuzz - convert a portable pixmap into an X11 "puzzle" file
.SH SYNOPSIS
.B ppmtopuzz
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap as input.
Produces an X11 "puzzle" file as output.
A "puzzle" file is for use with the
.I puzzle
.IX puzzle
.IX "X window system"
program included with the X11 distribution -
.IR puzzle 's
.B -picture
flag lets you specify an image file.
.SH "SEE ALSO"
ppm(5), puzzle(1)
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
