.TH ppmtogif 1 "01 September 1989"
.IX ppmtogif
.SH NAME
ppmtogif - convert a portable pixmap into a GIF file
.SH SYNOPSIS
.B ppmtogif
.RB [ -interlace ]
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap as input.
Produces a GIF file as output.
.IX GIF
.SH OPTIONS
.TP
.B -interlace
Tells the program to produce an interlaced GIF file.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
giftoppm(1), ppm(5)
.SH AUTHOR
Based on GIFENCOD by David Rowley <mgardi@watdcsu.waterloo.edu>.
Lempel-Ziv compression based on "compress".

Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
.\"
.\" The Graphics Interchange Format(c) is the Copyright property of
.\" CompuServe Incorporated.  GIF(sm) is a Service Mark property of
.\" CompuServe Incorporated.
