.TH ppmtoicr 1 "30 July 1990"
.IX ppmtoicr
.SH NAME
ppmtoicr - convert a portable pixmap into NCSA ICR format 
.SH SYNOPSIS
.B ppmtoicr
.RB [ -windowname
.IR name ]
.RB [ -expand
.IR expand ]
.RB [ -display
.IR display ]
.RB [ -rle ]
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap file as input.
Produces an NCSA Telnet Interactive Color Raster graphic file as output.
.IX "NCSA ICR"
If
.I ppmfile
is not supplied, 
.I ppmtoicr
will read from standard input.
.PP
Interactive Color Raster (ICR) is a protocol for displaying raster
graphics on workstation screens. The protocol is implemented in NCSA
Telnet for the Macintosh version 2.3.
.IX Macintosh
The ICR protocol shares
characteristics of the Tektronix graphics terminal emulation protocol.
.IX Tektronix
For example, escape sequences are used to control the display.
.PP
.I ppmtoicr
will output the appropriate sequences to create a window of the
dimensions of the input pixmap,
create a colormap of up to 256
colors on the display, then load the picture data into the window.
.PP
Note that there is no icrtoppm tool - this transformation is one way.
.SH OPTIONS
.TP 14
.BI -windowname name
Output will be displayed in
.I name
(Default is to use
.I ppmfile
or "untitled" if standard input is read.)
.TP
.BI -expand expand
Output will be expanded on display by factor 
.I expand
(For example, a value of 2 will cause four pixels to be displayed for
every input pixel.)
.TP
.BI -display display
Output will be displayed on screen numbered 
.I display
.TP
.B -rle
Use run-length encoded format for display. (This will nearly always
result in a quicker display, but may skew the colormap.)
.SH EXAMPLES
To display a
.I ppm
file using the protocol:
.nf
    ppmtoicr ppmfile
.fi
This will create a window named 
.I ppmfile
on the display with the correct dimensions for
.I ppmfile,
create and download a colormap of up
to 256 colors, and download the picture into the window. The same effect
may be achieved by the following sequence:
.nf
    ppmtoicr ppmfile > filename
    cat filename
.fi
To display a GIF 
file using the protocol in a window titled after the input file, zoom
the displayed image by a factor of 2, and
run-length encode the data:
.nf
    giftoppm giffile | ppmtoicr -w giffile -r -e 2
.fi
.SH BUGS
.PP
The protocol uses frequent 
.I fflush
calls to speed up display. If the
output is saved to a file for later display via
.I cat,
drawing will be
much slower. In either case, increasing the Blocksize limit on the
display will speed up transmission substantially.
.SH SEE ALSO
.BR ppm(5)
.LP
.IR "NCSA Telnet for the Macintosh" ,
University of Illinois at Urbana-Champaign (1989)
.SH AUTHOR
Copyright (C) 1990 by Kanthan Pillay (svpillay@Princeton.EDU),
Princeton University Computing and Information Technology.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
