.TH ppmtorgb3 1 "10 January 1991"
.IX ppmtorgb3
.SH NAME
ppmtorgb3 - separate a portable pixmap into three portable graymaps
.SH SYNOPSIS
.B ppmtorgb3
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap as input.
Writes three portable graymaps as output, one each for red, green, and blue.
.IX "color separation"
.PP
The output filenames are constructed by taking the input filename,
stripping off any extension, and appending ".red", ".grn", and ".blu".
For example, separating lenna.ppm would result in lenna.red, lenna.grn,
and lenna.blu.
If the input comes from stdin, the names are noname.red, noname.grn,
and noname.blu.
.SH "SEE ALSO"
rgb3toppm(1), ppmtopgm(1), pgmtoppm(1), ppm(5), pgm(5)
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
