.TH ppmtoxpm 1 "26 June 1990"
.IX ppmtoxpm
.SH NAME
ppmtoxpm - convert a portable pixmap into an X11 pixmap
.SH SYNOPSIS
.B ppmtoxpm
.RB [ -name
.IR xpmname ]
.RI [ ppmfile ]
.SH DESCRIPTION
Reads a portable pixmap as input.
Produces X11 pixmap (XPM) as output.
.IX XPM
.IX "X window system"
.PP
If the program was compiled with an rgb database specified, and
a RGB value from the ppm input matches a RGB value from the database,
then the corresponding color name mnemonic is printed in the XPM's colormap.
If no rgb database was compiled in, or if the RGB values don't match,
then the color
will be printed with the #RGB, #RRGGBB, #RRRGGGBBB, or #RRRRGGGGBBBB
hexadecimal format.
.SH OPTIONS
.TP
.B -name
Allows you to specify the prefix string which is printed
in the resulting XPM output.  If not specified, will default to the
filename (without extension) of the ppmfile argument.
If
.B -name
is not specified and no ppmfile
is specified (i.e. piped input), the prefix string will default to
the string "noname".
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH EXAMPLE
To convert the file "dot" (found in /usr/include/X11/bitmaps),
from xbm to xpm one could specify
.IP
xbmtopbm dot | ppmtoxpm -name dot
.SH BUGS
An option to match the closest (rather than exact) color name mnemonic
from the rgb text would be a desirable enhancement.
.PP
Truncation of the least significant bits of a RGB value may result in
nonexact matches when performing color name mnemonic lookups.
.SH "SEE ALSO"
xpmtoppm(1), ppm(5)
.SH AUTHOR
Copyright (C) 1990 by Mark W. Snitily.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
.\" 
.\" This tool was developed for Schlumberger Technologies, ATE Division, and
.\" with their permission is being made available to the public with the above
.\" copyright notice and permission notice.
