.TH qrttoppm 1 "25 August 1989"
.IX qrttoppm
.SH NAME
qrttoppm - convert output from the QRT ray tracer into a portable pixmap
.SH SYNOPSIS
.B qrttoppm
.RI [ qrtfile ]
.SH DESCRIPTION
Reads a QRT file as input.
.IX "QRT raytracer"
Produces a portable pixmap as output.
.SH "SEE ALSO"
ppm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
