.TH sldtoppm 1 "10 October 1991"
.IX sldtoppm
.IX AutoCAD
.SH NAME
sldtoppm - convert an AutoCAD slide file into a portable pixmap
.SH SYNOPSIS
.na
.B sldtoppm
'in 14n
.RB [ -adjust ]
.RB [ -dir ]
.RB [ -height | -ysize
.IR s ]
.RB [ -info ]
.RB [ -lib | -Lib
.IR name ]
.RB [ -scale
.IR s ]
.RB [ -verbose ]
.RB [ -width | -xsize
.IR s ]
.RI [ slidefile ]
.in -14n
.ad
.SH DESCRIPTION
Reads an AutoCAD\*R slide file and outputs a portable pixmap.
If no
.I slidefile
is specified, input is read from standard input.
The ppmdraw library is used to convert the vector and polygon
information in the slide file to a pixmap; see the file ppmdraw.h for
details on this package.
.SH OPTIONS
.TP
.B -adjust
If the display on which the slide file was created had non-square
pixels, when the slide is processed with
.B sldtoppm
and the
.B -adjust
option is not present, the following warning will appear:
.in +.2i
Warning - pixels on source screen were non-square.
.br
Specifying
.B -adjust
will correct image width to compensate.
.in -.2i
Specifying the
.B -adjust
option causes
.B sldtoppm
to scale the width of the image so that pixels in the resulting
portable pixmap are square (and hence circles appear as true circles,
not ellipses).  The scaling is performed in the vector domain, before
scan converting the objects.  The results are, therefore, superior in
appearance to what you'd obtain were you to perform the equivalent
scaling with
.B pnmscale
after the bitmap had been created.
.TP
.B -dir
The input is assumed to be an AutoCAD slide library file.  A directory
listing each slide in the library is printed on standard error.
.TP
.BI -height " size"
Scales the image in the vector domain so it is
.I size
pixels in height.  If no
.B -width
or
.B -xsize
option is specified, the width will be adjusted to preserve the
pixel aspect ratio. 
.TP
.B -info
Dump the slide file header on standard error, displaying the original
screen size and aspect ratio among other information.
.TP
.BI -lib " name"
Extracts the slide with the given
.I name
from the slide library given as input.  The specified
.I name
is converted to upper case.
.TP
.BI -Lib " name"
Extracts the slide with the given
.I name
from the slide library given as input.  The
.I name
is used exactly as specified; it is not converted to upper case.
.TP
.BI -scale " s"
Scales the image by factor
.IR s ,
which may be any floating point value greater than zero.  Scaling is
done after aspect ratio adjustment, if any.  Since scaling is
performed in the vector domain, before rasterisation, the results look
much better than running the output of
.B sldtoppm
through
.BR pnmscale .
.TP
.B -verbose
Dumps the slide file header and lists every vector and polygon in the
file on standard error.
.TP
.BI -width " size"
Scales the image in the vector domain so it is
.I size
pixels wide.  If no
.B -height
or
.B -ysize
option is specified, the height will be adjusted to preserve the
pixel aspect ratio. 
.TP
.BI -xsize " size"
Scales the image in the vector domain so it is
.I size
pixels wide.  If no
.B -height
or
.B -ysize
option is specified, the height will be adjusted to preserve the
pixel aspect ratio. 
.TP
.BI -ysize " size"
Scales the image in the vector domain so it is
.I size
pixels in height.  If no
.B -width
or
.B -xsize
option is specified, the width will be adjusted to preserve the
pixel aspect ratio. 
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH BUGS
Only Level 2 slides are converted.  Level 1 format has been obsolete
since the advent of AutoCAD Release 9 in 1987, and was not portable
across machine architectures.
.PP
Slide library items with names containing 8 bit (such as ISO) or 16
bit (Kanji, for example) characters may not be found when chosen with the
.B -lib
option unless
.B sldtoppm
has been built with character set conversion functions appropriate to
the locale.  You can always retrieve slides from libraries regardless
of the character set by using the
.B -Lib
option and specifying the precise name of library member.  Use the
.B -dir
option to list the slides in a library if you're unsure of the
exact name.
.SH "SEE ALSO"
AutoCAD Reference Manual:
.IR "Slide File Format" ,
.BR pnmscale (1),
.BR ppm (5)
.SH AUTHOR
.RS 5
.nf
John Walker
Autodesk SA
Avenue des Champs-Montants 14b
CH-2074 MARIN
Suisse/Schweiz/Svizzera/Svizra/Switzerland
.PD 0
.TP 9
Usenet:
kelvin@Autodesk.com
.TP
Fax:
038/33 88 15
.TP
Voice:
038/33 76 33
.fi
.RE
.PD
.PP
Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
without any conditions or restrictions.  This software is provided ``as
is'' without express or implied warranty.
.PP
AutoCAD and Autodesk are registered trademarks of Autodesk, Inc.
