.TH tgatoppm 1 "26 August 1989"
.IX tgatoppm
.SH NAME
tgatoppm - convert TrueVision Targa file into a portable pixmap
.SH SYNOPSIS
.B tgatoppm
.RB [ -debug ]
.RI [ tgafile ]
.SH DESCRIPTION
Reads a TrueVision Targa file as input.
.IX TrueVision
.IX Targa
Produces a portable pixmap as output.
.SH OPTIONS
.TP
.B -debug
Causes the header information to be dumped to stderr.
.PP
All flags can be abbreviated to their shortest unique prefix.
.BUGS
Should really be in PNM, not PPM.
.SH "SEE ALSO"
ppmtotga(1), ppm(5)
.SH AUTHOR
Partially based on tga2rast, version 1.0, by Ian J. MacPhedran.

Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
