.TH ximtoppm 1 "25 March 1990"
.IX ximtoppm
.SH NAME
ximtoppm - convert an Xim file into a portable pixmap
.SH SYNOPSIS
.B ximtoppm
.RI [ ximfile ]
.SH DESCRIPTION
Reads an Xim file as input.
.IX Xim
.IX "X window system"
Produces a portable pixmap as output.
The Xim toolkit is included in the contrib tree of the X.V11R4 release.
.SH "SEE ALSO"
ppm(5)
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
