.TH xpmtoppm 1 "16 August 1990"
.IX xpmtoppm
.SH NAME
xpmtoppm - convert an X11 pixmap into a portable pixmap
.SH SYNOPSIS
.B xpmtoppm
.RI [ xpmfile ]
.SH DESCRIPTION
Reads an X11 pixmap (XPM) as input.
.IX XPM
.IX "X window system"
Produces a portable pixmap as output.
.SH "SEE ALSO"
ppmtoxpm(1), ppm(5)
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
