.TH yuvtoppm 1 "25 March 91"
.IX yuvtoppm
.SH NAME
yuvtoppm - convert Abekas YUV bytes into a portable pixmap
.SH SYNOPSIS
.B yuvtoppm
.I width height
.RI [ imagedata ]
.SH DESCRIPTION
Reads raw Abekas YUV bytes as input.
.IX Abekas
Produces a portable pixmap as output.
The input file is just YUV bytes.
You have to specify the width and height on the command line,
since the program obviously can't get them from the file.
The maxval is assumed to be 255.
.SH "SEE ALSO"
ppmtoyuv(1), ppm(5)
.SH AUTHOR
Marc Boucher <marc@PostImage.COM>,
based on Example Conversion Program, A60/A64 Digital Video Interface
Manual, page 69.
.PP
Copyright (C) 1991 by DHD PostImage Inc.
.PP
Copyright (C) 1987 by Abekas Video Systems Inc.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
