.TH CLOSE 2
.UC 4
.SH NAME
close \- close an open file descriptor
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.B int close (int filedes);
.fi
.SH DESCRIPTION
.B close()
closes an open file descriptor.  0 is returned on success,
a negative value on error.
.SH ERRORS
.B -EINVAL
is returned if 
.B close()
is used on an invalid file descriptor.  
.SH SEE ALSO
fopen(3), open(2)
.SH FILES
linux/fs/open.c, /usr/include/linux/sys.h, /usr/include/unistd.h 
