.TH EXIT 2
.UC 4
.SH NAME
_exit, exit \- exit a process
.SH SYNOPSIS
.B #include <unistd.h>
.br
.B volatile void _exit (int status)
.br
.B volatile void exit (int status)
.SH DESCRIPTION
.B _exit
(
.I status
) 
exits with
.I status
, but does not run any 
.B atexit()
specified functions, where as 
.B exit
(
.I status
)
exits  with 
.I status
and runs any
.B atexit() 
specified exit functions.
.SH FILES
linux/kernel/exit.c
.br
/usr/include/linux/sys.h
.br
/usr/include/unistd.h
.SH SEE ALSO
.B atexit(2)
.SH BUGS
There may be a limited number of 
.B atexit()
functions  available.
exit belongs in section 3.
