.TH REBOOT 2
.UC 4
.SH NAME
reboot \- reboot or disable CNTRL - ALT - DEL
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.B int reboot (int magic, int magic_too, int flag);
.fi
.SH DESCRIPTION
.B reboot()
reboots the system, or enables / disables CAD.
.PP
If  
.I magic 
== 0xfee1dead && 
.I magictoo 
== 672274793, then the action performed will 
be based on 
.I flag.
.br
If flag = 0x1234567, then a hard reset is performed.
.br
If flag = 0x89abcdef, then CAD is enabled.
.br
If flag = 0, then CAD is disabled.
.PP 
0 is returned on success, a negative value on failure.
.PP
Note that 
.B reboot() 
does NOT
.B sync()!
.PP
Also, for obvious reasons, only root may call this function.
.SH ERRORS
.B -EINVAL 
is returned for  bad magic numbers.
.PP
.B -EPERM
is returned if a non-root user attempts to call
.B reboot().
.SH FILES
linux/sys.c
.br
/usr/include/linux/sys.h
.br
/usr/include/unistd.h
.SH SEE ALSO
sync(2)
