.TH SETUP 2
.UC 4
.SH NAME
setup \- initialize the ST506 hd driver drive and partition parameters
.SH SYNOPSIS
.nf 
.B #include <linux/sys.h>
.B #include <linux/config.h>
.fi
.PP
.B void setup(void *BIOS);
.PP
.SH DESCRIPTION
.B setup(const void *BIOS)  
may be called once from within
.I linux/init/main.c.
Its purpose is to initialize the  
.B hd_info[] 
table for the hard disk driver.  If 
.B HD_TYPE 
is defined, from within
.I linux/include/linux/config.h
, the value provided by 
.I BIOS
is overided.  Otherwise, The structure pointed to by
.I BIOS  
is assumed to be a one or two element array of 
.B  hd_i_struct 
structures defined as follows (in 
.I linux/kernel/blk_drv/hd.c
) :
.PP
struct hd_i_struct {
unsigned int head,sect,cyl,wpcom,lzone,ctl;
};
.PP
Normal, and extended partitions are detected.
Disk manager partitions are accounted for as well.
.SH FILES
linux/include/linux/config.h
.br
linux/init/main.c
.br
linux/kernel/blk_drv/hd.c 

