.TH TIMES 2
.UC 4
.SH NAME
times \- return elapsed process times.
.SH SYNOPSIS
.nf
.B #include <sys/times.h>
.B #include <unistd.h>
.B time_t times (struct tms *buf);
.fi
.SH DESCRIPTION
.B times()
stores the current utime, stime, cutime, cstime, of the current process into 
.I buf.  
.PP
struct tms is as defined in /usr/include/sys/times.h:
.br
.nf
struct  tms  {
.in 20
time_t tms_utime;
time_t tms_stime;
time_t tms_cutime;
time_t tms_cstime;
};
.in 10
.fi
.PP
.B times()
returns the number of clock ticks that have elapsed since the system has been up.
.SH FILES
linux/kernel/sys.c
.br
/usr/include/linux/sys.h
.br
/usr/include/unistd.h
.SH SEE ALSO
time(2)
