.TH USELIB  2
.UC 4
.SH NAME
uselib \- select shared library.
.SH SYNOPSIS
.nf
.B #include <unistd.h>
.B int uselib (char *library);
.fi
.SH DESCRIPTION
.B uselib()
selects the shared library binary that will be used by this processes.
0 is returned on success,  a negative value  on failure.
.SH ERRORS
.B -ENOENT
is returned if 
.I library
does not exist.
.PP
.B -EINVAL
is returned if the limits are insufficient.         
.SH FILES
linux/fs/exec.c
.br
/usr/include/linux/sys.h
.br
/usr/include/unistd.h
.br
user built shared libraries 
.SH SEE ALSO
swapon(2), gcc(1), ar(1), ld(1) 
.SH BUGS
No validation is performed on the file type of 
.I library.
