.TH AT 1
.SH NAME
at, atrun \- execute commands at a later time
.SH SYNOPSIS
\fBat \fItime\fR [\fImonth day\fR] [\fIfile\fR]\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "at 2315 Jan 31 myfile" "Myfile executed Jan 31 at 11:15 pm"
.EX "at 0900" "Job input read from \fIstdin\fR"
.EX "at 0711 4 29 " "Read from \fIstdin\fR, exec on April 29"
.SH DESCRIPTION
.PP
\fIAt\fR prepares a file to be executed later at the specified time by 
creating a special entry in \fI/usr/spool/at\fR.  
The program \fIatrun\fR should be started 
periodically, for example, every minute by \fIcron\fR.  \fIAtrun\fR 
checks to see if any
files in \fI/usr/spool/at\fR should now be run, and if so, it runs them 
and then puts them in \fI/usr/spool/at/past\fR.
The name of the file created in \fI/usr/spool/at\fR by 
\fIat\fR is YY.DDD.HHMM.UU (where YY, DDD, HH, and MM give the time to execute and 
UU is a unique number).  Note that when the command runs, it will not be able 
to use \fIstdin\fR or \fIstdout\fR unless specifically redirected.  In 
the first example above, it might be necessary to put \fI>/dev/log\fR
on some lines in the shell script \fImyfile\fR.  
The same holds for the commands typed directly to \fIat\fR.
.SH "SEE ALSO"
.BR cron (8).
