.TH CLR 1
.SH NAME
clr \- clear the screen
.SH SYNOPSIS
\fBclr        \fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "clr	 " "Clear the screen"
.SH DESCRIPTION
.PP
All text is removed from the screen, resulting in an empty screen with the
cursor positioned in the upper left-hand corner.
