.TH DF 1
.SH NAME
df \- report on free disk space and i-nodes
.SH SYNOPSIS
\fBdf \fIspecial ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "df /dev/ram" "Report on free RAM disk space"
.EX "df /dev/fd0 /dev/fd1" "Report on diskette space"
.EX "df   " "Report on all mounted devices"
.SH DESCRIPTION
.PP
The amount of disk space and number of i-nodes, both free and used is
reported.
If no argument is given, \fIdf\fR reports on the root device and all mounted
file systems.
.SH "SEE ALSO"
.BR du (1),
.BR fstab (5).
