.TH LAST 1
.SH NAME
last \- display recent on-line session records
.SH SYNOPSIS
\fBlast\fR [\fB\-f \fIfile\fR]\fR [\fB\-r\fR] [\fB\-\fIn\fR] [\fIname\fR] [\fItty\fR] ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-f" "Use \fIfile\fR instead of /usr/adm/wtmp"
.FL "\-r" "Search backwards only to last reboot"
.FL "\-\fIn\fP" "Print a maximum of \fIn\fR lines"
.SH EXAMPLES
.EX "last reboot" "When was the system last rebooted?"
.EX "last ast" "When was the last login for ast?"
.EX "last \-10 tty00 tty01" "Display last 10 logins on tty00 or tty01"
.SH DESCRIPTION
.PP
.I Last
Searches backward through the login administration file (default is
\fI/usr/adm/wtmp\fR), printing information about previous logins and
reboots.
During a long search, the SIGQUIT signal (CTRL-\\) causes \fIlast\fR to 
display how far back it has gone; it then continues. 
.SH "SEE ALSO"
.BR login (1).
