.TH MAIL 1
.SH NAME
mail \- send and receive electronic mail
.SH SYNOPSIS
\fBmail\fR [\fB\-dpqrv\fR]\fR [\fB\-f \fIfile\fR] [\fIuser\fR]\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-d" "Force use of the shell variable \fIMAILER\fR"
.FL "\-f" "Use \fIfile\fR instead of \fI/usr/spool/mail/user\fR as mailbox"
.FL "\-p" "Print all mail and then exit"
.FL "\-q" "Quit program if SIGINT received"
.FL "\-r" "Reverse print order, i.e., print oldest first"
.FL "\-v" "Verbose mode"
.SH EXAMPLES
.EX "mail ast" "Send a message to \fIast\fR"
.EX "mail" "Read your mail"
.SH DESCRIPTION
.PP
\fIMail\fR is an extremely simple electronic mail program.  It can be used
to send or receive email on a single 
\s-2MINIX\s+2
system, in which case it functions
as user agent and local delivery agent.  
If the flag \fIMAILER\fR is defined in \fImail.c\fR,
it can also call a trans\%port agent to handle remote mail as well.
No such agent is supplied with
\s-2MINIX\s+2.
.PP
When called by \fIuser\fR with no arguments, it examines the mailbox
\fI/usr/spool/mail/user\fR, prints one message (depending on the \fB\-r\fR
flag), and waits for one of the following commands:
.PP
.nf
.ta 0.25i 1.25i
	<newline>	Go to the next message
	\-	Print the previous message
	!command	Fork off a shell and execute \fIcommand\fR
	CTRL-D	Update the mailbox and quit (same as q)
	d	Delete the current message and go to the next one
	q	Update the mailbox and quit (same as CTRL-D)
	p	Print the current message again
	s [\fIfile\fR]	Save message in the named file
	x	Exit without updating the mailbox
.PP
.PP
To send mail, the program is called with the name of the recipient as an
argument.  The mail is sent, along with a postmark line containing the date.
For local delivery, a file named after the recipient in the directory
\fI/usr/spool/mail\fR must be writable.
.PP
If the directory \fI/usr/spool/mail\fR does not exist then the mail is
dumped on the console, so that system programs have a way to notify
a user on a system that does not have a mail spool.
