.TH MREF 1
.SH NAME
mref \- make listing and cross reference map of MINIX
.SH SYNOPSIS
\fBmref\fR [\fB\-dlmstx\fR] [\fB\-p \fIn\fR] [\fB\-\fIn\fR] \fIfile ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-d" "Do not produce definition file (global symbol table)"
.FL "\-l" "Do not produce listing"
.FL "\-m" "Multiple references on one line are cited only once"
.FL "\-p" "Set initial page number to \fIn\fR"
.FL "\-s" "Suppress line numbering between procedures"
.FL "\-t" "Generate output for \fItroff\fR"
.FL "\-x" "Do not produce the cross reference map"
.FL "\-\fIn" "Number of lines to print per page, default = 50"
.SH EXAMPLES
.EX "mref *.[\fIhc\fR]" "List and cross reference files \fI.h\fR and \fI.c\fR"
.EX "mref \-60 \-t *.c" "Produce \fItroff\fR input at 60 lines/page"
.EX "mref \-dx \-p 100 *.c" "Listing only, first page is numbered 100"
.SH DESCRIPTION
.PP
In default mode, 
.I mref
produces three output files: a numbered listing of the input files
(on standard output), a global symbol table (on \fIsymbol.out\fR),
and a cross reference map to the global symbols (on \fIxref.out\fR).
A global symbol in this context is one present in a #define, PUBLIC,
PRIVATE, or SYMBOL statement (the latter being introduced to allow users
to explicitly declare certain symbols as global).
Any of the three outputs can be suppressed, or alternatively, be made
suitable for input to \fItroff\fR for typesetting.
