.TH MV 1
.SH NAME
mv \- move or rename a file
.SH SYNOPSIS
\fBmv [\fB\-ifsmvx\fR] \fIfile1 file2\fR
.br
\fBmv [\fB\-ifsvx\fR] \fIfile\fR ... \fIdirectory\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-i" "Prompt before removing existing files"
.FL "\-f" "Do not prompt before removing existing files"
.FL "\-s" "Do not clear any mode bits if owner can't be set"
.FL "\-m" "Merge directory trees"
.FL "\-v" "Tell what mv is doing"
.FL "\-x" "Do not cross device boundaries"
.SH EXAMPLES
.EX "mv oldname newname" "Move \fIoldname\fP to \fInewname\fP"
.EX "mv file1 file2 /user/ast" "Move two files to \fI/user/ast\fP"
.SH DESCRIPTION
.PP
.I Mv
moves one or more files from one place in the file system to another.
If the old path and new path are on the same device, it is done by renaming
otherwise by copying. If you're not superuser, the copy will destroy the
file's owner, group and setuid/setgid bits.
.I mv
will prompt before removing non-writable files if \fBstdin\fR is a terminal
or the \fB\-i\fR flag was specified.
.SH "SEE ALSO"
.BR cp (1),
.BR rename (2).
