.TH PATHCHK 1
.SH NAME
pathchk \- check pathname
.SH SYNOPSIS
\fBpathchk [\fB\-p\fR] \fIpath\fR ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-p" "Check against POSIX rules"
.SH EXAMPLES
.EX "pathchk /usr/src/file.c" "Check the accessibility of \fIfile.c\fP"
.EX "pathchk \-p file" "Check posix compliance of \fIfile\fR"
.SH DESCRIPTION
.PP
.I Pathchk
verifies path names and display error if paths are too long, contain names
that are too long, go thru a non-searchable directory or contain an
invalid character in names. If the \fB\-p\fR flag is specified, the POSIX
rules apply instead of the rules of the current file system.
