.TH PRETTY 1
.SH NAME
pretty \- MINIX pretty printer
.SH SYNOPSIS
\fBpretty \fIfile ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "pretty file1 file2" "Convert two files to \s-2MINIX\s0 layout"
.SH DESCRIPTION
.PP
\fIPretty\fR converts one or more C source files to 
\s-2MINIX\s+2
format by changing 
their layout.  Running this program does not affect the resulting binary
programs.  Actually, \fIpretty\fR is a postprocessor for \fIindent\fR, which
must be installed in \fI/bin\fR or \fI/usr/bin\fR.  Although the output is
not bad, it is not entirely consistent with the book or even with itself.
