.TH PRINTENV 1
.SH NAME
printenv \- print out the current environment
.SH SYNOPSIS
\fBprintenv\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "printenv" "Print the environment"
.SH DESCRIPTION
.PP
\fIPrintenv\fR prints out the current environment strings, one per line.
.SH "SEE ALSO"
.BR environ (7).
