.TH RECOVER 1
.SH NAME
recover \- recover files that have been removed.
.SH SYNOPSIS
\fBrecover \fIfile ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "rm x; recover x" "Unremove x"
.EX "recover a b c" "Recover three files"
.SH DESCRIPTION
.PP
MINIX allows files that have been deleted (e.g., with \fIrm\fR) to be
restored (in \fI/tmp\fR).
The trick is that when a file is unlinked, its i-node number is kept in
the directory entry.
As long as the directory entry and disk blocks are not reused, the file
can be recovered.
This program is actually just a little front end for \fIde\fR, which must be
installed as a set-uid root executable.
.SH "SEE ALSO"
.BR de (9).
