.TH REV 1
.SH NAME
rev \- reverse the characters on each line of a file
.SH SYNOPSIS
\fBrev\fR [\fIfile\fR] ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "rev file" "Reverse each line"
.SH DESCRIPTION
.PP
Each file is copied to standard output with all the characters of each line
reversed, last one first and first one last.
.SH "SEE ALSO"
.BR rev (1).
