.TH RM 1
.SH NAME
rm \- remove a file
.SH SYNOPSIS
\fBrm\fR [\fB\-ifrRvx\fR] \fIname\fR ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-i" "Interactive remove: ask before removing"
.FL "\-f" "Forced remove: no questions asked"
.FL "\-rR" "Remove directories and their contents"
.FL "\-v" "Tell what rm is removing"
.FL "\-x" "Do not cross device boundaries"
.SH EXAMPLES
.EX "rm file" "Remove \fIfile\fR"
.EX "rm \-i *.c" "Remove \fI.c\fP files, asking about each"
.SH DESCRIPTION
.PP
.I Rm
removes one or more files.
If a file has no write permission,
.I rm
asks for permission (type \&'y\&' or \&'n\&') unless \fB\-f\fR
is specified.
If the file is a directory, it will be recursively descended and removed
if and only if the \fB\-R\fR flag is present.
.SH "SEE ALSO"
.BR cp (1),
.BR mv (1),
.BR rmdir (1),
.BR unlink (2),
.BR rmdir (2).
