.TH SED 1
.SH NAME
sed \- stream editor
.SH SYNOPSIS
\fBsed\fR [\fB\-egn\fR]\fR [\fB\-f \fIscript_file\fR]\fR [\fIedit_script\fR] [\fIfile\fR]\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-e" "Accept multiple commands commands on the commands line"
.FL "\-f" "The following argument contains the edit script"
.FL "\-g" "Set the global flag on all substitute commands"
.FL "\-n" "Only output selected lines"
.SH EXAMPLES
.EX "sed \-f script <file" "Run a sed script on \fIfile\fR"
.EX "sed \(fm/pig/s//hog/g\(fm <file" "Replace \fIpig\fR by \fIhog\fR in the file"
.SH DESCRIPTION
.PP
\fISed\fR is a stream editor.
It takes an edit script either from its argument or a file, and performs
an edit session on a named file or \fIstdin\fR, producing output 
on \fIstdout\fR.
.SH "SEE ALSO"
.BR cgrep (1),
.BR fgrep (1),
.BR grep (1),
.BR awk (9).
