.TH SU 1
.SH NAME
su \- temporarily log in as superuser or another user
.SH SYNOPSIS
\fBsu\fR [\fIname\fR]\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "su    " "Become superuser"
.EX "su ast" "Become \fIast\fR"
.SH DESCRIPTION
.PP
.I Su
can be used to temporarily login as another user.
It prompts for the superuser password.
If the correct password is entered,
.I su
creates a shell with the desired uid.
If no name is specified, \fIroot\fR is assumed.
To exit the temporary shell, type CTRL-D.
When memory is tight, it is better to become superuser by logging out and
then logging in again as \fIroot\fR, rather than using \fIsu\fR since the
latter creates an extra shell in memory.  Any user with a zero group id need
not type a password.  This makes life easier for the system administrator.
.SH "SEE ALSO"
.BR login (1).
