.TH TEST 1
.SH NAME
test, [ \- test for a condition
.SH SYNOPSIS
\fBtest \fIexpr\fR
.br
\fB[ \fIexpr \fB]\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
(none)
.SH EXAMPLES
.EX "test \-r file" "See if file is readable"
.SH DESCRIPTION
.PP
\fITest\fR checks to see if files exist, are readable, etc. and returns
an exit status of zero if true and nonzero if false.  The legal operators are
.sp
.nf
.ta 0.5i 1.5i
	\-r file	true if the file is readable
	\-w file	true if the file is writable
	\-x file	true if the file is executable
	\-f file	true if the file is not a directory
	\-d file	true if the file is a directory
	\-s file	true if the file exists and has a size > 0
	\-t fd	true if file descriptor fd (default 1) is a terminal
	\-z s	true if the string s has zero length
	\-n s	true if the string s has nonzero length
	s1 = s2	true if the strings s1 and s2 are identical
	s1 != s2	true if the strings s1 and s2 are different
	m \-eq m	true if the integers m and n are numerically equal
.fi
The operators \fB\-gt\fR, \fB\-ge\fR, \fB\-ne\fR, \fB\-le\fR, and
\fB\-lt\fR may be used as well.
These operands may be combined with \fB\-a\fR (Boolean and), 
\fB\-o\fR (Boolean or), !
(negation).  
The priority of \fB\-a\fR is higher than that of \fB\-o\fR.  
Parentheses are permitted, but must be escaped to keep the shell from trying 
to interpret them.
.SH "SEE ALSO"
.BR expr (1),
.BR sh (1).
