.TH TRAVERSE 1
.SH NAME
traverse \- print directory tree under the named directory
.SH SYNOPSIS
\fBtraverse \fIdir\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "traverse ." "Print tree starting at working dir"
.SH DESCRIPTION
.PP
\fITraverse\fR prints the tree structure starting at the named directory. 
All the subdirectories are listed, with the depth shown by indentation.
.SH "SEE ALSO"
.BR find (1),
.BR ls (1).
