.TH WIDTH 1
.SH NAME
width \- force all the lines of a file to a given width
.SH SYNOPSIS
\fBwidth\fR [\fB\-\fIn\fR [ \fIinfile\fR [\fIoutfile\fR]\fR\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-\fIn\fR" "Outline line size"
.SH EXAMPLES
.EX "width \-60 x y" "Copy \fIx\fR to \fIy\fR, force lines to 60 cols"
.EX "width x" "Copy default (80) column lines to \fIstdout\fR"
.SH DESCRIPTION
.PP
The input file is copied to the output file.
All lines are forced to a given size (default: 80 columns) by padding with
spaces or truncating.
Tabs are expanded to spaces.
.SH "SEE ALSO"
.BR fold (1).
