.TH LPD 8 "Line Printer Daemon"
.SH NAME
/usr/bin/lpd 
.SH SYNOPSIS
/usr/bin/lpd -d device name [ -r run level ]
.SH DESCRIPTION
LPD(3) is invoked by the rc script upon startup of the system and reads the
file /etc/printcap to determine its configuration. LPD(3) monitors its spool
directory for print jobs and queues for printing files that it finds there.
It runs setuid root and setgid lp so that it may read and write in the spool
directory.
.SH CAVEATS
The daemon only monitors for one printer device at a time. 
.SH EXAMPLES
/bin/lpd -d lp
.br
.in 15
invokes the daemon for device "lp" which is defined in
/etc/printcap.
.br 
.in 10

/bin/lpd -d lp -r 2
.br
.in 15
invokes the daemon as above but with a run level of 2.
Log files will be written to the log directory in the file [device name].log.
Run levels available are 1, 2, and 3, from terse to verbose. If the -r option
is not specified the daemon will run silently EXCEPT for device error messages.
.br
.in 10
.SH FILES
/etc/printcap
.br
/usr/spool/lp/*
.br
/usr/spool/lp/*/.daemon (lock file)
.SH "RETURN VALUE"
If
.bo
lpd
returns a non-zero value, installation has
.bo
failed.
.SH "SEE ALSO"
lp(1), lpq(1)
.SH WARNINGS
Print jobs are deleted without warning after they are sent to the printer
device. This does not mean they were printed.
.SH BUGS
Files will be discarded even if the print device was busy or off-line.
The daemon will complain to the standard output.
Currently the run level is stuck at verbose.
.SH MISCELLANEOUS
The print daemon will regard any files in its directory that it can read as
printable, even if they do not have queue control files associated with them.
.bp
.SH NOTES
This print daemon is loosely based on the BSD 4.3 lpd and the public domain
PLP print daemon. 
