
.\"     Man page file for the unprotoize  program.
.\"     This is badly out of date, especially concerning
.\"     the way of deciding which files to convert.
.\"     Really all this information should be updated and put in gcc.texinfo.
.\"  
.\"     Written by Ron Guilmette (rfg@mcc.com).
.\"  
.\"     Copyright (C) 1989, 1990 Free Software Foundation, Inc.
.\"  
.\"  This file is part of GNU CC.
.\"  
.\"  GNU CC is free software; you can redistribute it and/or modify
.\"  it under the terms of the GNU General Public License as published by
.\"  the Free Software Foundation; either version 1, or (at your option)
.\"  any later version.
.\"  
.\"  GNU CC is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU General Public License for more details.
.\"  
.\"  You should have received a copy of the GNU General Public License
.\"  along with GNU CC; see the file COPYING.  If not, write to
.\"  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH UNPROTOIZE  1 "21 January 1990" ""
.SH NAME



unprotoize  \- convert ANSI C source code to K&R C (unprototyped) format

.SH SYNOPSIS
.B unprotoize 
[
.B -VqfnkN
] [
.B -i
.I <str>
] [
.B -c
.I <cc opts>
] [
.I file\c
\&... ]
.SH DESCRIPTION
.fi
.ad b
.I Unprotoize 
aids in the conversion of ANSI C source code files to K&R C 
source code files without function prototypes.
This conversion is useful for porting ANSI C programs to
machines for which no ANSI C compiler is available.

.PP
.I Unprotoize 
is designed to be used in conjunction
with the GNU C compiler.  The GNU C compiler does preliminary
.I "information gathering"
about functions by analyzing the files to be converted.
The GNU C compiler may be invoked automatically as a result of
running
.I unprotoize 
so it is important to have it properly installed before attempting
to convert source files via
.I unprotoize .

.PP
.I Unprotoize 
supports the conversion of both large and small systems of C source
code to unprototyped form.
.I Unprotoize 
can perform the conversion of an
entire program in one (batch) step.

.PP
Each conversion of a system of source code to unprototyped
format consists of two major steps.  First, there is an
.I "information gathering"
step.  In this step,
all of the source files that make up a given
executable program are recompiled using the GNU C compiler and using the
.B -fgen-aux-info
option.
These recompilations will be performed automatically by
.I unprotoize 
on an
.I as needed
basis.
.PP
As individual compilation steps are performed, you may notice
that a side-effect of these compilations is to create files with a
.B .X
suffix in the same directory with the original
.I base
source files being compiled.
During compilation with
.B -fgen-aux-info,
one such
.B .X
file is created for
each
.I base
source file compiled.  These files contain
information about function definitions and declarations and
additional coded information which can be used by
.I unprotoize 
to convert your source code
automatically to unprototyped format.
.PP
After a full set of
.B .X
files corresponding to all of the
.B .c
(i.e.
.I base
source) files for an individual
program
have been created,
.I unprotoize 
performs the actual conversion step.
.PP
Execution of the
.I unprotoize 
program causes your original source files to be converted such that both
their function declarations and their function definitions are in 
unprototyped format.
After the conversion of your system, you will be
left with a set of similar (but converted) source files
with the same names as your original files.
.PP
Before it writes each converted file back to disk,
.I unprotoize 
attempts to rename the original file, giving it a
.B .save
suffix.
It then creates a new output file
with the same name that the original file had.
This ensures that if there were any hard links to the original
input files, these will not be altered by the conversion process.
.PP
WARNING!  If for any given original file, a save file already exists,
.I unprotoize 
will assume that the existing save file contains a backup of the
original file as it existed before any conversions were applied.
Thus, if there is an existing save file,
.I unprotoize 
will not overwrite this existing save file, and no new backup of
that particular original file will be made during that run of
.I unprotoize .
.PP
An important safety feature of
.I unprotoize 
is that it normally only tries to convert files for which you have both
read and write permissions.  Also,
.I unprotoize 
will normally only convert files located in directories that you
have both search and write permissions for.
.PP
Another safety feature is that
.I unprotoize 
will not normally convert files which
are located in
.I system
include directories.
A
.I system
include directory is defined by
.I unprotoize 
as either
.B /usr/include
(or any of its subdirectories)
or a directory whose full absolute pathname includes
either
.B gcc-include
or
.B g++-include.
.PP
Most of the above safety features can be overridden by using the
.B \-f
(force) option (see below),
but even when
.B \-f
is used, you cannot force the conversion of files for which you
do not at least have read permission, or files in directories that you do not
at least have write permission for.
.PP
Note that
.I unprotoize 
will make no attempt to convert definitions
of functions which accept a variable number of arguments
and which are written using the
.I stdarg 
conventions.
All such function definitions
must be converted manually to the
.I varargs 
conventions.
Warnings are automatically issued for
.I stdarg 
function definitions which are left unconverted by
.I unprotoize .
.SH OPTIONS
.I Unprotoize 
recognizes the following options:
.TP
.B \-V
Version number.  Causes the current version number to be
printed on stderr.
.TP
.B \-q
Quiet mode.
Normally,
.I unprotoize 
may issue many verbose warnings concerning noteworthy conditions.
These warnings can often be helpful to the overall conversion effort.
Users who prefer not to see such messages can use the
.B \-q
option which suppresses most such warnings.
.TP
.B \-f
Force mode.
Use of this option overrides the normal safety
features of
.I unprotoize .
It allows for attempts to convert system include files,
and files not writable by you.
These conversions are still subject to all normal
file protections provided by the operating system.
This option should be used only with extreme caution.
It can be especially dangerous to use this option when logged on as
.I root.
Note that when this option is used, you are allowed to convert even files
that you do not have write access to.  So long as you have write access
to the containing directory, conversion may occur.
.TP
.B \-n
No convert mode.  Do not actually perform any conversions on base source files
or on include files.  Rather, simply do all steps leading up to conversion
and then print a list (to stdout) of the names of all files which would
actually be modified if the conversions were actually performed.  This option
may be useful to you if you are converting a system of source files
that you are unfamiliar with.  In such cases, you may need to verify
ahead of time that include files which belong to other people or to
other projects will not be modified by running
.I unprotoize .
Use of this option also implicitly enables
.I keep mode.
(See the
.B \-k
option below.)
.TP
.B \-k
Keep mode.  Normally,
.I unprotoize 
reads the information in the
.B .X
files created by the GNU C compiler, and then
immediately deletes these files (since they will no longer be
valid or useful after conversion).  When the
.B \-k
option is used however, the
.B .X
files are not deleted during conversion.
.TP
.B -N
No save mode.  When this option is used, no attempt is made to
make backups of original files (by renaming them such that they have
an added
.B .save
suffix).
Use this option with extreme caution, and
only when you have previously backed up
all of the files that might be converted
by running
.I unprotoize .
(See the
.B -n
option above.)
.TP
.B \-c <cc opts>
Specify compile options.  The
.B \-c
option can be used as a means of passing on important compilation
options to the C compiler.  It may often be necessary to use this option
to pass command line preprocessor definitions on to the compilation step.
Note that The compile options must be given as a single argument to
.I unprotoize .
If you have more than one
compilation option, you will have to quote the entire set of
compilation options in order to keep the shell from treating
them as separate arguments to
.I unprotoize .
Note also that certain options are automatically suppressed by
.I unprotoize 
and cannot be passed on to the compiler (i.e.
.B "-g, -O, -c, -S,"
and
.B "-o"
are suppressed).

.TP
.B \-i <str>
Indent string option.
This option can be used to specify a string to use when indenting
lines containing declarations for formal parameter variables.
The default indentation string for such lines is a sequence of five spaces
(i.e.\ GNU style indentation) but you may use this option to specify
any other string that you like (e.g.\ a tab character).
Note that
the shell has its own interpretations for blanks and tabs, so you
will generally have to quotes the argument given in the
.B -i
option.

.SH EXAMPLES
Assume that you have
a directory with
all of the files for your system in it.  Also
assume that your system consists of two
executable programs, one built from the files
.B s1.c, s2.c,
and
.B s3.c,
and the other built from the files
.B s4.c
and
.B s5.c.
Finally, assume that these source files share some common include files.
.PP
In order to properly convert such a system of programs, you
would need to perform the steps shown below.
.sp 1
.in +0.5i
.ft B
unprotoize  s1.c s2.c s3.c
.br
unprotoize  s4.c s5.c
.sp 1
.ft R
.in -0.5i
.PP
In the example above, the first invocation of
.I unprotoize 
causes three
.B .X
files (called
.B s1.c.X, s2.c.X,
and
.B s3.c.X)
to be created.
These files are generated automatically by
.I unprotoize 
(which invokes the GNU C compiler to create them).
These files contain information about function definitions and declarations
.I both
for their corresponding
.B .c
files and for any files
which are included by these
.I base
.B .c
files.
.PP
After
.I unprotoize 
has invoked the compiler for each of the files which make up
.I prog1,
it performs the actual conversion of these base files (and
may perform some conversion of their include files
depending upon the information available in the
.B .X
files).
Finally, after performing all necessary conversions,
.I unprotoize 
automatically deletes the files
.B s1.c.X, s2.c.X,
and
.B s3.c.X.
.PP
After performing the conversion for
.I prog1,
(as illustrated above)
you would then
request
.I unprotoize 
to convert all of the files which make up
.I prog2
in a similar fashion.
This step would create two more
.B .X
files (called
.B s4.c.X
and
.B s5.c.X).
As with the conversion of
.I prog1,
.I unprotoize 
will automatically generate any needed
.B .X
files (by invoking the GNU C compiler),
will perform the conversion of all of the given
.I base
source files (and possibly do some conversion on include files),
and will finish up by
automatically deleting the
.B .X
files that were generated during this run.
.PP
You may occasionally find that you need to convert a
particular program which
consists of several
.I base
source files, some of which must be compiled
with unusual options.
In such cases, you can still convert the program via
a special mechanism.
For each
.I base
source file which requires special compilation options,
you can create a corresponding
.B .X
file for the
.I base
file
.I (before
invoking
.I unprotoize ).
You would do this by invoking the GNU C compiler directly
with the required special options, and with the
.B -fgen-aux-info
option.
.I Unprotoize 
is smart enough to use existing
.B .X
files (when they are available and when they are up to date) so creating
.B .X
files ahead of time with the GNU C compiler
is an easy way to accommodate unusual compilation options for individual
.I base
files.
.PP
Note that
.I unprotoize 
checks each preexisting
.B .X
file before it tries to use it in order
to insure that it is up-to-date
with respect to all of the source files
that it contains information about.
If this check fails,
.I unprotoize 
will automatically
invoke the GNU C compiler (with default options) to recreate the needed
.B .X file.
.SH CAVEATS
It is naive to assume that the conversions performed by
.I unprotoize 
are sufficient to make your source code completely compatible with
K&R C.
The automatic conversion of your source files via
.I unprotoize 
is only one step (albeit a big one) towards
full conversion.  A full conversion may also require
lots of editing "by hand".
.PP
.I Unprotoize 
only converts function declarations and definitions.  No conversion of
.I types
(such as function types and pointer-to-function types)
contained in
.B typedef
statements is attempted.  These must be converted manually.

.PP
Naive conversion of source code via
.I unprotoize 
may introduce bugs into the resulting (converted) code unless you are very
careful.  The reason for this is rather subtle.
Basically, when a call is made to a prototyped function, the types of
some of the parameter values in the call may be implicitly converted
to the types of the corresponding formal parameters (as declared in the
function prototype).  These implicit conversions can (occasionally) involve
changes of representation for the passed values (for instance from int
to float).  Unfortunately, once your code has been converted via
.I unprotoize ,
these implicit conversions will no longer take place within the function
calls which require them.
.PP
The only remedy for this problem (currently) is for users of
.I unprotoize 
to make sure that explicit casts are inserted into calls which will force
these type conversions to occur even in the absence of function
prototypes.  Users can determine the exact set of places where such explicit
casts may be required by compiling all code to be converted using the
.B -Wconversion
option to GCC prior to conversion.  The warnings produced by
.B -Wconversion
will indicate those places in the original source code where explicit
casts must be inserted.  Once these explicit casts have been manually
inserted (and the warnings from
.B -Wconversion
eliminated), conversion may be performed without any possibility of
generating code which is incorrect due to missed type conversions.

.SH WARNINGS
There are numerous possible warning and error messages which
.I unprotoize 
may issue for strange circumstances (e.g.\ missing input
files, etc.) or for noteworthy conditions in the source code being converted.
These should all be self-explanatory.
If any message is not self-explanatory, it\'s a bug.  Please report it.
.SH FILES
.ta 3.0i
/usr/local/bin/gcc	GNU C compiler
.br
/usr/local/bin/unprotoize 	the unprotoize  program




.SH "SEE ALSO"
gcc(1), g++(1), protoize (1)
.SH BUGS
.I Unprotoize 
can easily be confused by
source code which has
macro calls in the
vicinity of something which it has to convert.
Fortunately, such cases seem to be rare in practice.
This is an inherent problem with the compiler
based approach to information gathering and will likely never be fixed.
When it does become confused,
.I unprotoize 
will still proceed to convert the file it is working on as much as
possible.  Only the particularly confusing function definitions and
declarations will fail to be converted.  These can subsequently be converted
manually.
.PP
Due to the method currently used to gather information,
.I unprotoize 
will fail to convert function declarations and definitions which
are located in conditional compilation sections which were
.I "preprocessed out"
during the creation of the
.B .X
files used for conversion.
You can generally work around this problem by doing
repeated conversion steps using
.I unprotoize ,
each with a different set of compilation options (i.e.\ preprocessor
symbol definitions) but assuring complete conversion can
currently only be done by visual inspection.
Currently,
.I unprotoize 
attempts to find function definitions which were
.I "preprocessed out"
and to issues warnings for such cases.
A later revision of
.I unprotoize 






may be able to convert both function declarations and function
definitions which have been
.I "preprocessed out."

.PP
Currently,
.I unprotoize 
makes no attempt to convert declarations of
.I "pointer to function"
types, variables, or fields.

A later version of
.I unprotoize 
may attempt to perform conversions of these 
declarative items also.

.PP
Currently,
.I stdarg 
functions definitions



must be converted by hand to use the
.I varargs 
convention.
It is possible that a subsequent version of
.I unprotoize 
will make some attempt to do these conversions automatically.
.PP
.I Unprotoize 
may get confused if it finds that it has to convert a function
declaration or definition in a region of source code where
there is more than one formal parameter list present.
Thus, attempts to convert code containing
multiple (conditionally compiled) versions of a single
function header (in the same vicinity) may not produce
the desired (or expected) results.
If you plan on converting source files which contain
such code, it is recommended that you first make sure
that each conditionally compiled region of source
code which contains an alternative function header
also contains at least one additional follower token
(past the final right parenthesis of the function header).
This should circumvent the problem.

.PP
.I Unprotoize 
can become confused when trying to convert a function
definition or declaration
which contains a declaration for a
.I pointer-to-function
formal argument
which has the same name as the function being defined or
declared.
Such unfortunate choices of formal parameter names are discouraged.

.PP
Bugs (and requests for reasonable enhancements) should be reported to
bug-gcc@prep.ai.mit.edu.  Bugs may actually be fixed if they can be easily
reproduced, so it is in your interest to report them
in such a way that reproduction is easy.
.SH COPYING
Copyright (c) 1989, 1990 Free Software Foundation, Inc.
.sp 1
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.sp 1
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.sp 1
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
.SH AUTHORS
Written by Ronald F.\ Guilmette at the Microelectronics and Computer Technology
Corporation (MCC).  Generously donated by MCC to the Free Software
Foundation.
.sp 1
See the GNU C Compiler Manual for a list of contributors to GNU C.
