#ifdef SHORT_NAMES
#define M_NO_BACK_FOLDING M_N_B_F
#define M_NO_ENTER_LIST_FF M_N_L_FF
#define M_NO_INPIPE M_N_I_P
#define M_NO_OUTFILE M_N_O_F
#define M_NO_SHELL_VAR M_N_S_V
#define M_NO_TERM MNTERM
#define M_NO_TERMCAP MNTC
#define M_NO_TEXT MNTXT
#define M_NO_TOP_AUTO_SAVE M_NTAS
#define M_CHANGED_SAVE M_C_S
#define M_CHANGED_LEAVE M_C_L
#define M_WHICH_MODE M_W_M
#define M_WHICH_FIX M_W_F
#define M_MAIL_S M_MAILS
#define M_MAIL_1 M_MAIL1
#define M_MAIL_2 M_MAIL2
#define M_NO_PREV M_NOPREV
#define M_NO_NEXT M_NONEXT
#define close_fold_at cse_f_at
#define create_node crt_node
#define current curt
#define current_dsp_line curt_dsp_line
#define current_ind curt_ind
#define delete__ dlt__
#define delete_dsp_line dtl_dsp_line
#define delete_under dlt_under
#define deleted_ch dlt_ch
#define dialect_end dilct_end
#define dialect_start dilct_start
#define dispose_head dios_head
#define dispose_size dios_size
#define dispose_tail dios_tail
#define disable_sig_abort dis_sa
#define enable_echo enbl_echo
#define enable_sig_abort enb_s_a
#define enter_depth et_dth
#define enter_depth_spaces et_d_spaces
#define enter_fold en_fold
#define enter_folds_to en_f_to
#define insert_ ist_
#define insert_file ist_file
#define insert_indent_of ist_indent_of
#define macro_string mac_string
#define write_fold wit_fold
#define move_on mo_on
#define move_on_full mo_o_full
#define on_screen_line o_sc_line
#define remove_fold rm_fold
#define remove_line rm_line
#define replace_item repl_item
#define restore_cursor rst_cursor
#define restore_element rst_element
#define restore_from rst_from
#define restore_or_restore_to_end rst_or_rst_to_end
#define restore_to_end rst_to_end
#define screen_end sc_end
#define screen_end_level sc_e_level
#define screen_lines sc_lines
#define screen_message sc_message
#define screen_start sc_start
#define select_backward sct_backward
#define select_forward sct_forward
#define select_on sct_on
#define select_ptr sct_ptr
#define set_key_top s_key_top
#define sub_move_down s_mv_down
#define sub_move_up s_mv_up
#define tstorefile_NAME tst_f_name
#define undelete_after un_after
#define undelete_before un_before
#define undelete_pick_before un_pick_before
#define whole_screen_down w_scr_down
#define whole_screen_up w_scr_up
#define write_tag wit_tag
#define write_tds wit_tds
#endif
