# LaTeX2HTML 95.1 (Fri Jan 20 1995)
# Associate image original text (scrambled) with physical files.

$key = q/{}cparamclock{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img272.gif">'; 
$key = q/{}cparamremote-name{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img311.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowritesincelastchange(;SPM_quot;:edit!;SPM_quot;overrides)minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img235.gif">'; 
$key = q/{}cparamfile3{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img174.gif">'; 
$key = q/{}keyctrl-D{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img183.gif">'; 
$key = q/{}cparamfilename{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img204.gif">'; 
$key = q/{}cparamname{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img282.gif">'; 
$key = q/{}cparamfileN{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img260.gif">'; 
$key = q/{}cparamnameofauthor{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img317.gif">'; 
$key = q/{}cparamwarning-message{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img251.gif">'; 
$key = q/{_inline}$Diamond${_inline}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img9.gif">'; 
$key = q/{}cparamkernel-name{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img240.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallgoodunderlinementocometotheaidoftheparty.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img210.gif">'; 
$key = q/{}cparamonelinetogivetheprogram'snameandabriefideaofwhatitdoes.{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img316.gif">'; 
$key = q/{}cparamsectors{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img84.gif">'; 
$key = q/{}fboxminipage0.8textwidthCOWISTHETIMEFORALLWOMENTOCOMETOTHEAIDOFTHEHUNGRY.~~~~~:efoounderlineminipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img234.gif">'; 
$key = q/{}keyx{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img217.gif">'; 
$key = q/{}cparamoptions{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img258.gif">'; 
$key = q/{}cparampattern{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img166.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallgoodwomentocometotheaidoftheparty.Afterwards,we'llgooutforpizzaandbeerunderline.~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img215.gif">'; 
$key = q/{}cparamslanted{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img4.gif">'; 
$key = q/{}LaTeX{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img12.gif">'; 
$key = q/{}keyctrl-F{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img230.gif">'; 
$key = q/{}cparamlocal-name{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img312.gif">'; 
$key = q/{}cparamarg1{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img157.gif">'; 
$key = q/{}cparamcommand{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img308.gif">'; 
$key = q/{}fboxminipage0.8textwidthCOWISTHETIMEFORALLWOMENTOCOMETOTHEAIDOFTHEHUNGRYunderline.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img229.gif">'; 
$key = q/{}keya{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img211.gif">'; 
$key = q/{}keyctrl-Z{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img198.gif">'; 
$key = q/{}cparamdma{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img49.gif">'; 
$key = q/{}fboxminipage0.8textwidthunderlineCowisthetimeforallwomentocometotheaidofthehungry.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img227.gif">'; 
$key = q/{}fboxminipage0.8textwidthCOWISTHETIMEFORALLWOMENTOCOMETOTHEAIDOFTHEHUNGRY.~~~~~:e!foounderlineminipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img236.gif">'; 
$key = q/{}cparamhoriz-values{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img277.gif">'; 
$key = q/{}fboxminipage0.8textwidthunderlineNowisthetimeforallgoodwomentocometotheaidoftheparty.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img223.gif">'; 
$key = q/{}cparamdot-clock{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img276.gif">'; 
$key = q/{}cparamdrive{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img55.gif">'; 
$key = q/{}cparamfile2{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img131.gif">'; 
$key = q/{}keyb{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img105.gif">'; 
$key = q/{}cparamfilenames{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img189.gif">'; 
$key = q/{}cparamfoo{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img5.gif">'; 
$key = q/{}keybackspace{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img294.gif">'; 
$key = q/{tabular}lllhlineFile;SPM_amp;DescriptionhlinettXF86-3.1-ctrb.tar.gz;SPM_amp;Selectedcontribprograms.ttXF86-3.1-extra.tar.gz;SPM_amp;ExtraXFree86serversandbinaries.ttXF86-3.1-lkit.tar.gz;SPM_amp;Serverlinkkitforcustomization.ttXF86-3.1-fnt75.tar.gz;SPM_amp;75-dpiscreenfonts.ttXF86-3.1-fnt100.tar.gz;SPM_amp;100-dpiscreenfonts.ttXF86-3.1-fntbig.tar.gz;SPM_amp;LargeKanjiandotherfonts.ttXF86-3.1-fntscl.tar.gz;SPM_amp;Scaledfonts(Speedo,Type1).ttXF86-3.1-man.tar.gz;SPM_amp;Manualpages.ttXF86-3.1-pex.tar.gz;SPM_amp;PEXbinaries,includesandlibraries.ttXF86-3.1-slib.tar.gz;SPM_amp;StaticXlibrariesandsupportfiles.ttXF86-3.1-usrbin.tar.gz;SPM_amp;Daemonswhichresideinusrbin.ttXF86-3.1-xdmshdw.tar.gz;SPM_amp;Shadowpasswordversionofxdm.hline{tabular}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img268.gif">'; 
$key = q/{tabular}lllhlineFile;SPM_amp;DescriptionhlinettXF86-3.1-bin.tar.gz;SPM_amp;TherestoftheX11R6binaries.ttXF86-3.1-cfg.tar.gz;SPM_amp;Configfilesforttxdm,ttxinitandttfs.ttXF86-3.1-doc.tar.gz;SPM_amp;Documentationandmanpages.ttXF86-3.1-inc.tar.gz;SPM_amp;Includefiles.ttXF86-3.1-lib.tar.gz;SPM_amp;SharedXlibrariesandsupportfiles.ttXF86-3.1-fnt.tar.gz;SPM_amp;Basicfonts.hline{tabular}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img267.gif">'; 
$key = q/{}keyesc{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img212.gif">'; 
$key = q/{}cparammemory-address{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img79.gif">'; 
$key = q/{}fboxminipage0.8textwidthCOWISTHETIMEFORALLWOMENTOCOMETOTHEAIDOFTHEHUNGRY.~~~~~:underlineminipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img232.gif">'; 
$key = q/{}cparampartition{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img59.gif">'; 
$key = q/{}keyd{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img222.gif">'; 
$key = q/{}key~{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img228.gif">'; 
$key = q/{tabular}llFirstMS-DOSpartition(ttC:);SPM_amp;ttdevhda1SecondMS-DOSpartition(ttD:);SPM_amp;ttdevhda2Extedpartition;SPM_amp;ttdevhda3FirstLinuxlogicalpartition;SPM_amp;ttdevhda5SecondLinuxlogicalpartition;SPM_amp;ttdevhda6{tabular}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img54.gif">'; 
$key = q/{}cparamcylinders{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img75.gif">'; 
$key = q/{table}[ht]centersmalltabularlllhlineSitename;SPM_amp;IPAddress;SPM_amp;Directoryhlinetsx-11.mit.edu;SPM_amp;18.172.1.2;SPM_amp;publinuxsunsite.unc.edu;SPM_amp;152.2.22.81;SPM_amp;pubLinuxnic.funet.fi;SPM_amp;128.214.6.100;SPM_amp;pubOSLinuxftp.mcc.ac.uk;SPM_amp;130.88.200.7;SPM_amp;publinuxfgb1.fgb.mw.tu-muenchen.de;SPM_amp;129.187.200.1;SPM_amp;publinuxftp.informatik.tu-muenchen.de;SPM_amp;131.159.0.110;SPM_amp;pubLinuxftp.dfv.rwth-aachen.de;SPM_amp;137.226.4.105;SPM_amp;publinuxftp.informatik.rwth-aachen.de;SPM_amp;137.226.112.172;SPM_amp;pubLinuxftp.ibp.fr;SPM_amp;132.227.60.2;SPM_amp;publinuxkirk.bu.oz.au;SPM_amp;131.244.1.1;SPM_amp;pubOSLinuxftp.uu.net;SPM_amp;137.39.1.9;SPM_amp;systemsunixlinuxwuarchive.wustl.edu;SPM_amp;128.252.135.4;SPM_amp;systemslinuxftp.win.tue.nl;SPM_amp;131.155.70.100;SPM_amp;publinuxftp.ibr.cs.tu-bs.de;SPM_amp;134.169.34.15;SPM_amp;puboslinuxftp.denet.dk;SPM_amp;129.142.6.74;SPM_amp;pubOSlinuxtabularnormalsizermlabeltable-ftp-sitescenter{table}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img315.gif">'; 
$key = q/{}TeX{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img30.gif">'; 
$key = q/{}cparamscsi_id{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img52.gif">'; 
$key = q/{}cparamargN{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img159.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallgoodwomentocometotheaidoftheparty.Afterwards,we'llgooutforpizzaandunderline~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img218.gif">'; 
$key = q/{}keyspacebar{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img67.gif">'; 
$key = q/{}keyctrl-C{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img192.gif">'; 
$key = q/{}cparamdir2{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img136.gif">'; 
$key = q/{}keyReturn{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img96.gif">'; 
$key = q/{_inline}$mid${_inline}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=MIDDLE ALT="" SRC="img261.gif">'; 
$key = q/{}keyalt{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img287.gif">'; 
$key = q/{}cparamsignatureofTyCoon{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img318.gif">'; 
$key = q/{}cparamirq{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img44.gif">'; 
$key = q/{}keynumeric+{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img297.gif">'; 
$key = q/{}cparamtime{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img250.gif">'; 
$key = q/{}keyalt-F2{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img170.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallgoodwomentocometotheaidoftheparty.Afterwards,we'llgooutforpizzaandDietCokeunderline.~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img221.gif">'; 
$key = q/{}fboxminipage0.8textwidthunderline~~~~~~;SPM_quot;test;SPM_quot;[Newfile]minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img205.gif">'; 
$key = q/{}cparamhostname{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img302.gif">'; 
$key = q/{}keyshift{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img90.gif">'; 
$key = q/{table}[ht]centersmalltabularllhlineDevice;SPM_amp;NamehlineFirstfloppy(ttA:);SPM_amp;ttdevfd0Secondfloppy(ttB:);SPM_amp;ttdevfd1Firstharddrive(entiredrive);SPM_amp;ttdevhdaFirstharddrive,primarypartition1;SPM_amp;ttdevhda1Firstharddrive,primarypartition2;SPM_amp;ttdevhda2Firstharddrive,primarypartition3;SPM_amp;ttdevhda3Firstharddrive,primarypartition4;SPM_amp;ttdevhda4Firstharddrive,logicalpartition1;SPM_amp;ttdevhda5Firstharddrive,logicalpartition2;SPM_amp;ttdevhda6_inline$vdots$_inline;SPM_amp;Secondharddrive(entiredrive);SPM_amp;ttdevhdbSecondharddrive,primarypartition1;SPM_amp;ttdevhdb1_inline$vdots$_inline;SPM_amp;FirstSCSIharddrive(entiredrive);SPM_amp;ttdevsdaFirstSCSIharddrive,primarypartition1;SPM_amp;ttdevsda1_inline$vdots$_inline;SPM_amp;SecondSCSIharddrive(entiredrive);SPM_amp;ttdevsdbSecondSCSIharddrive,primarypartition1;SPM_amp;ttdevsdb1_inline$vdots$_inline;SPM_amp;tabularnormalsizermlabeltable-part-namescenter{table}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img53.gif">'; 
$key = q/{}cparamfile1{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img133.gif">'; 
$key = q/{}cparamsize{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img58.gif">'; 
$key = q/{}cparamheads{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img83.gif">'; 
$key = q/{}ret{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img8.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallwomentocometotheaidofthehungryunderline.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img226.gif">'; 
$key = q/{}cparamdestination{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img126.gif">'; 
$key = q/{}keyi{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img206.gif">'; 
$key = q/{}cparaminterrupt{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img80.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallunderlinewomentocometotheaidoftheparty.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img224.gif">'; 
$key = q/{}keySpace{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img104.gif">'; 
$key = q/{}keyR{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img225.gif">'; 
$key = q/{}keyKey{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img7.gif">'; 
$key = q/{}keyreturn{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img238.gif">'; 
$key = q/{}keyalt-F4{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img100.gif">'; 
$key = q/{}cparammemaddr{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img43.gif">'; 
$key = q/{figure}[tb]picture(148.00,365.00)(0.00,450.00)put(9.00,805.00)line(1,0)29.00%put(26.00,805.00)line(0,-1)112.00%put(26.00,791.00)line(1,0)12.00%put(26.00,777.00)line(1,0)12.00%put(26.00,763.00)line(1,0)12.00%put(64.50,763.00)line(1,0)29.00%put(81.50,763.00)line(0,-1)14.00%put(81.50,749.00)line(1,0)12.00%put(26.00,735.00)line(1,0)12.00%put(26.00,721.00)line(1,0)12.00%put(26.00,707.00)line(1,0)12.00%put(26.00,693.00)line(1,0)12.00%put(55.50,693.00)line(1,0)29.00%put(72.50,693.00)line(0,-1)238.00%put(72.50,676.00)line(1,0)12.00%put(72.50,659.00)line(1,0)12.00%put(72.50,642.00)line(1,0)12.00%put(72.50,625.00)line(1,0)12.00%put(72.50,608.00)line(1,0)12.00%put(72.50,591.00)line(1,0)12.00%put(72.50,574.00)line(1,0)12.00%put(107.00,574.00)line(1,0)29.00%put(124.00,574.00)line(0,-1)51.00%put(124.00,557.00)line(1,0)12.00%put(124.00,540.00)line(1,0)12.00%put(124.00,523.00)line(1,0)12.00%put(72.50,506.00)line(1,0)12.00%put(72.50,489.00)line(1,0)12.00%put(72.50,472.00)line(1,0)12.00%put(100.50,472.00)line(1,0)29.00%put(72.50,455.00)line(1,0)12.00%put(8.50,805.00)makebox(0,0)[rc]put(39.50,805.00)makebox(0,0)[lc]binput(39.50,791.00)makebox(0,0)[lc]devput(39.50,777.00)makebox(0,0)[lc]etcput(39.50,763.00)makebox(0,0)[lc]homeput(95.00,763.00)makebox(0,0)[lc]larryput(95.00,749.00)makebox(0,0)[lc]samput(39.50,735.00)makebox(0,0)[lc]libput(39.50,721.00)makebox(0,0)[lc]procput(39.50,707.00)makebox(0,0)[lc]tmpput(39.50,693.00)makebox(0,0)[lc]usr%put(86.00,693.00)makebox(0,0)[lc]X386%put(86.00,676.00)makebox(0,0)[lc]binput(86.00,659.00)makebox(0,0)[lc]emacs%put(86.00,642.00)makebox(0,0)[lc]etcput(86.00,625.00)makebox(0,0)[lc]g++-includeput(86.00,608.00)makebox(0,0)[lc]includeput(86.00,591.00)makebox(0,0)[lc]libput(86.00,574.00)makebox(0,0)[lc]localput(137.50,574.00)makebox(0,0)[lc]bin%put(137.50,557.00)makebox(0,0)[lc]emacsput(137.50,540.00)makebox(0,0)[lc]etcput(137.50,523.00)makebox(0,0)[lc]libput(86.00,506.00)makebox(0,0)[lc]manput(86.00,489.00)makebox(0,0)[lc]spoolput(86.00,472.00)makebox(0,0)[lc]srcput(130.50,472.00)makebox(0,0)[lc]linuxput(86.00,455.00)makebox(0,0)[lc]tmppicturelabeldirtree{figure}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img101.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallgoodmentocometotheaidofthepartyunderline.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img207.gif">'; 
$key = q/{}cparamdir1{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img138.gif">'; 
$key = q/{tabular}lllhlineFile;SPM_amp;DescriptionhlinettXF86-3.1-8514.tar.gz;SPM_amp;Serverfor8514-basedboards.ttXF86-3.1-AGX.tar.gz;SPM_amp;ServerforAGX-basedboards.ttXF86-3.1-Mach32.tar.gz;SPM_amp;ServerforMach32-basedboards.ttXF86-3.1-Mach8.tar.gz;SPM_amp;ServerforMach8-basedboards.ttXF86-3.1-Mono.tar.gz;SPM_amp;Serverformonochromevideomodes.ttXF86-3.1-P9000.tar.gz;SPM_amp;ServerforP9000-basedboards.ttXF86-3.1-S3.tar.gz;SPM_amp;ServerforS3-basedboards.ttXF86-3.1-SVGA.tar.gz;SPM_amp;ServerforSuperVGA-basedboards.ttXF86-3.1-VGA16.tar.gz;SPM_amp;ServerforVGAEGA-basedboards.ttXF86-3.1-W32.tar.gz;SPM_amp;ServerforET4000W32-basedboards.hline{tabular}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img266.gif">'; 
$key = q/{}keytab{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img247.gif">'; 
$key = q/{}cparamsection-name{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img270.gif">'; 
$key = q/{}keyo{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img214.gif">'; 
$key = q/{table}[ht]centersmalltabularllllhlineDevice;SPM_amp;IOaddress;SPM_amp;IRQ;SPM_amp;DMAhlinettttyS0(ttCOM1);SPM_amp;3f8;SPM_amp;4;SPM_amp;nattttyS1(ttCOM2);SPM_amp;2f8;SPM_amp;3;SPM_amp;nattttyS2(ttCOM3);SPM_amp;3e8;SPM_amp;4;SPM_amp;nattttyS3(ttCOM4);SPM_amp;2e8;SPM_amp;3;SPM_amp;nattlp0(ttLPT1);SPM_amp;378-37f;SPM_amp;7;SPM_amp;nattlp1(ttLPT2);SPM_amp;278-27f;SPM_amp;5;SPM_amp;nattfd0,ttfd1(floppies1and2);SPM_amp;3f0-3f7;SPM_amp;6;SPM_amp;2ttfd2,ttfd3(floppies3and4);SPM_amp;370-377;SPM_amp;10;SPM_amp;3tabularnormalsizermlabeltable-dev-settingscenter{table}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img71.gif">'; 
$key = q/{}keyctrl-alt-del{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img70.gif">'; 
$key = q/{}fboxminipage0.8textwidthCOWISTHETIMEFORALLWOMENTOCOMETOTHEAIDOFTHEHUNGRY.lettersmiscpapersunderline~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img237.gif">'; 
$key = q/{}cparamlocal-filename{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img314.gif">'; 
$key = q/{}keyctrl-B{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img231.gif">'; 
$key = q/{}fboxminipage0.8textwidthNowisthetimeforallgoodwounderlinementocometotheaidoftheparty.~~~~~minipage{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img213.gif">'; 
$key = q/{}cparamdirectory{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img103.gif">'; 
$key = q/{}keyq{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img106.gif">'; 
$key = q/{}keyalt-F1{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img99.gif">'; 
$key = q/{}cparamdirN{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img137.gif">'; 
$key = q/{}cparamparametersldots{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img37.gif">'; 
$key = q/{}cparamfile{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img305.gif">'; 
$key = q/{}cparamport{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img47.gif">'; 
$key = q/{}cparamarg2{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img158.gif">'; 
$key = q/{}keyctrl{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img298.gif">'; 
$key = q/{}keynumeric-{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img300.gif">'; 
$key = q/{}tm{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img3.gif">'; 
$key = q/{}cparamvert-values{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img274.gif">'; 
$key = q/{}cparamroot-device{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img241.gif">'; 
$key = q/{}keyenter{}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img233.gif">'; 
$key = q/{table}[ht]centersmalltabularlllhlineFilesystem;SPM_amp;Typename;SPM_amp;CommenthlineSecondExtedFilesystem;SPM_amp;ttext2;SPM_amp;MostcommonLinuxfilesystem.ExtedFilesystem;SPM_amp;ttext;SPM_amp;Supersededbyttext2.MinixFilesystem;SPM_amp;ttminix;SPM_amp;OriginalMinixfilesystem;rarelyused.XiaFilesystem;SPM_amp;ttxia;SPM_amp;Likettext2,butrarelyused.UMSDOSFilesystem;SPM_amp;ttumsdos;SPM_amp;UsedtoinstallLinuxonanMS-DOSpartition.MS-DOSFilesystem;SPM_amp;ttmsdos;SPM_amp;UsedtoaccessMS-DOSfiles.ttprocFilesystem;SPM_amp;ttproc;SPM_amp;Providesprocessinformationforttps,etc.ISO9660Filesystem;SPM_amp;ttiso9660;SPM_amp;FormatusedbymostCD-ROMs.XenixFilesystem;SPM_amp;ttxenix;SPM_amp;UsedtoaccessfilesfromXenix.SystemVFilesystem;SPM_amp;ttsysv;SPM_amp;UsedtoaccessfilesfromSystemVvariantsforthex86.CoherentFilesystem;SPM_amp;ttcoherent;SPM_amp;UsedtoaccessfilesfromCoherent.HPFSFilesystem;SPM_amp;tthpfs;SPM_amp;Read-onlyaccessforHPFSpartitions(DoubleSpace).tabularnormalsizermlabeltable-fs-typescenter{table}/;
$cached_env_img{$key} ='<IMG BORDER=0 ALIGN=BOTTOM ALT="" SRC="img263.gif">'; 

1;

