./" ztar.man	by Dennis T. Flaherty (dflahert@chekov.helios.nd.edu)
./"	January 1991
./" ftar.man added May 1992
./"
.TH FTAR 1 "May 19, 1991"
.SH NAME
ftar \- wrap/unwrap frozen or compressed tarchives
.SH SYNOPSIS
.B ftar
.RB [ \-d ]
.RB [ \-t ]
.RB [ \-b\fIbits ]
.IR file " ..."
.br
.B ztar
.RB [ \-d ]
.RB [ \-t ]
.RB [ \-b\fIbits ]
.IR file " ..."
.SH DESCRIPTION
.PP
.I Ftar
wraps and unwraps frozen
.IR tarchives , 
archives made with
.IR tar (1).
These archives end in the characters
.B .tar.F
and are commonly used
sending and receiving directories over the
internet with 
.IR ftp (1).
If invoked as 
.IR ztar ,
.I compress
is used instead of 
.I freeze
and the archive names end in
.BR .tar.Z .
.PP
With no options, 
.I ftar
assumes that the specified files are directories, and invokes
tar and freeze (compress) on each of them to produce individual
frozen (compressed) tarchives.
.PP
The
.B \-d
option, when tarchives are specified, will cause
.I ftar
to invoke melt (uncompress) and tar in order to
.I unwrap
an archive.  If this option is specified and no files are listed,
.I ftar
will unwrap from 
.B stdin.
.PP
The maximum number of bits can be specified with
.BR \-b ,
for the benefit of 16-bit cpu's.  
.PP
When finished wrapping or unwrapping, the user will be asked 
whether the source directory or tarchive should be removed.
.PP
If the
.B \-t
option is used, a verbose table of contents of the specified
frozen (compressed)
tarchives is listed with
.IR "tar\ -tv" .
.SH "SEE ALSO"
ftp(1), compress(1), freeze(1), tar(1)
.SH AUTHOR
.nf
Dennis T. Flaherty,
U of Notre Dame
dflahert@chekov.helios.nd.edu
