.TH FIG2PS2TEX 1 "14 Mar 1991"
.SH NAME
fig2ps2tex - generate a TeX file for including a PostScript file

.SH SYNOPSIS
.B fig2ps2tex
.I file

.SH DESCRIPTION
.PP
.I Fig2ps2tex
generates a TeX file for including a PostScript file in a TeX document.
This involves calculating the bounding box from the Postscript document.
The TeX inclusion file is written to stdout.
.PP
Note that the
.I psfig
macro package provides a more sophisticated approach to including
Postscript files in LaTeX docuements.
.I Fig2ps2tex
works with plain TeX however.

.SH USAGE
.PP
Assume the Postscript file is called
.I foo.ps .
The command

.ce
% fig2ps2tex foo.ps >foo.tex

will create the inclusion file with bounding information.
Then include this file in your TeX document with the command

.ce
\einput{foo}

.SH "SEE ALSO"
psfig(1),
latex(1),
f2ps(1),
fig2dev(1),
transfig(1).

.SH AUTHOR
Micah Beck
.br
Cornell University

Man page by George Ferguson, ferguson@cs.rochester.edu.

