.TH PIC2TPIC 1 "14 Mar 1991"
.SH NAME
pic2tpic - Convert pic files to tpic format

.SH SYNOPSIS
.B pic2tpic
[ files ]

.SH DESCRIPTION
.PP
.B Pic2tpic
reads the
.B pic
files given on the command line (or stdin if none are given) and
writes their 
.B tpic
equivalent to stdout.

.SH "SEE ALSO"
tpic(1),
fig2dev(1),
transfig(1).

.SH AUTHOR
Micah Beck
.br
Cornell University

Man page by George Ferguson, ferguson@cs.rochester.edu.
