	.file	"stdstrbufs.cc"
gcc2_compiled.:
	.data
.globl _not_open_filebuf
	.align 2
_not_open_filebuf:
	.long -72499060
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.long 0
	.word 0
	.space 2
	.long __vt$filebuf
	.word -1
	.space 10
	.space	0x100		# For future use
.globl __9streambuf$_list_all
	.align 2
__9streambuf$_list_all:
	.long __cerr_sbuf
