.TH ADDUSER 1 \" -*- nroff -*-
.SH NAME
adduser \- create a new user account
.SH SYNOPSIS
.B adduser
<username> [-f] [-p] [-u \fIuid\fP] [-g \fIgid\fP] [-n \fIname\fP] 
[-d \fIdir\fP] [-s \fIshell\fP].
.SH DESCRIPTION
.B adduser
is a shell script which puts a new entry in the passwd file, and then
sets up the rest of the files and directories required.
.PP
With no options, defaults are assumed for everything.  The options are
the same as for the add mode of \fIpwdutil\fP(1), except for \fI-g\fP.
When specifying a gid, the uid is automatically set to \fI+<gid>\fP.
.SH SEE ALSO
pwdutil(1)

