.TH PWDUTIL 1 \" -*- nroff -*-
.SH NAME
pwdutil \- manipulate /etc/passwd entries
.SH SYNOPSIS
.B pwdutil
{a,r,d,e,c} [-f] <username> [parameters]
.SH DESCRIPTION
.B pwdutil
is a tool for manipulating entries in the passwd file.
The first argument on the command line is the function to be performed.
There are five modes of operation:
.IP "\fIa\fP"
adds a new entry.  After the username, the parameters
\fIuid gid name dir shell\fP must be given on the command line; the password
will be read from standard input.
Here, \fIname\fP refers to the gecos information field, 
and \fIdir\fP is the home directory.
The entry will be added where it belongs ordered by uid, but no rearranging
of previous entries is done.
.IP "\fIr\fP"
removes a passwd entry.  The only parameter required is the username to
remove.
.IP "\fId\fP"
disables a user by prepending a '*' to the password field.
.IP "\fIe\fP"
enables a user by removing the '*' from the beginning of the password.
.IP "\fIc\fP"
change one or more fields of an entry.  
The entries to be changed are specified as options after the username:
[-p] [-u \fIuid\fP] [-g \fIgid\fP] [-n \fIname\fP] [-d \fIdir\fP] 
[-s \fIshell\fP].
A new password will be read from standard input.
.PP
When adding an entry with
.B pwdutil
the following checks are performed.  First the username must be non-null,
and unique, as must be the uid.  If the path given for a home directory
exists, it must be a directory, with the proper uid and gid, and must have
rwx permissions for the owner.  
Finally, the shell must exist, and be a regular executable file.
.PP
If the entry is being changed, the checks for unique username, uid and gid
are skipped.
.PP
If the '-f' flag (force) is given, \fIno\fP checks are performed.
.SH FORMAT OF UID AND GID
The gid can be specified either numerically, or symbolically by using a
group name found in /etc/group.
.PP
The uid can be specified in three ways:
.IP numeric
Decimal only, please.
.IP \fI+\fP
This specifies a uid of one more than the last entry in the passwd file.
.IP \fI+<gid>\fP
This form specifies one greater than the uid of the last entry with the
specified gid.  The gid can be given in symbolic format.
.SH FILES
.IP /etc/passwd
the file being modified
.IP /etc/passwd.OLD
backup of passwd before being modified
.IP /etc/ptmp
temporary file for copying passwd, which must not exist
.IP /etc/group
file of groups searched for symbolic gids
