

                              DRIVE CONTROLLER DIRECTORY

                              THEREF(tm)     Version 4.2             10/01/91
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд

      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  1
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      ADAPTEC            ISA-ST412(MFM)   2HD
      ACB-2010           PC,XT                          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(RLL)   2HD
      ACB-2070           PC,XT                          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(RLL)   1HD
      ACB-2071           XT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(RLL)   2HD  2048 B  1/2
      ACB-2072           PC,XT      2:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(MFM)   2HD
      ACB-2310           AT         1:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(MFM)   2HD
      ACB-2312           AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ESDI         2HD  4096 B  3/4    A-C:16K, D:64K
      ACB-2320(A-D)      AT         1:1         16      XT    CACHE, 20Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ESDI         2HD  4096 B  FULL   64K CACHE
      ACB-2322(B-D)      AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(RLL)   2HD  4096 B  3/4
      ACB-2370           AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-ST412(RLL)   2HD  4096 B  FULL
      ACB-2372C          AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            MCA-ST412(MFM)   2HD  4096    FULL   BUFFER OPTION
      ACB-2610           MCA        1:1         16      MC    CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            MCA-ST412(RLL)   2HD  4096 *  FULL   BUFFER OPTION
      ACB-2670           MCA        1:1         16      MC    CACHE,*BIOS OPT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            MCA-ESDI         2HD  4096 B  FULL   CACHE, BUFFER
      ACB-26M20          MCA        1:1         16      MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-QIC36                           (TAPE) DOES NOT
      ACB-3530           NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-QIC120                          (TAPE) DOES NOT
      ACB-3540           NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд

      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  2
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      ADAPTEC            SCSI-ST412(MFM)  2HD       B         DOES NOT
      ACB-4000A          NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-ST412(MFM)  2HD                 MACINTOSH SCSI
      ACB-4010           NONE       1:1         16
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-ST412(RLL)  2HD                 DOES NOT
      ACB-4070           NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-ESDI        2HD                 DOES NOT
      ACB-4520           NONE       1:1                       PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-ESDI        2HD       B         DOES NOT
      ACB-4525Z          NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-ST412(MFM)  4HD       B         DOES NOT
      ACB-5500           NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-SMD         4HD       B         DOES NOT
      ACB-5580A          NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI(DIF.)-SMD   4HD       B         DOES NOT
      ACB-5580D          NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI-ESMD        4HD       B         DOES NOT
      ACB-5585A          NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            SCSI(DIF.)-ESMD  4HD                 DOES NOT
      ACB-5585D          NONE       1:1         16            PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  1/2    HOST ADAPTER
      AHA-1020           PC,XT,AT                   C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  1/2    PROG'D I/O
      AHA-1520           AT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  1/2    PROG'D I/O
      AHA-1522           AT               2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  FULL   BUS MASTERING
      AHA-1540A          AT                         C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  3/4    BUS MASTERING
      AHA-1540B          AT                         C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  FULL   BUS MASTERING
      AHA-1542A          AT               2FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            ISA-SCSI         7HD       B  3/4    BUS MASTERING
      AHA-1542B          AT               2FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  3
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      ADAPTEC            MCA-SCSI         7HD          FULL   BUS MASTERING
      AHA-1640           MCA                            MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            EISA-SCSI2       7HD       B  FULL   BUS MASTERING
      AHA-1740           EISA                       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADAPTEC            EIAS-SCSI2(DIF)  7HD       B  FULL   BUS MASTERING
      AHA-1744           EISA                       C   XT    DIFFERENTIAL
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADVANCED INFO.     MCA-SCSI                             DMA
      MCA                MCA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADVANCED INFO.     ISA-SCSI                             PROG'D I/O
      PC/AT              XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADVANCED STOR.     ISA-SCSI                             16 BYTE BUFFER
      ASC-86             AT                                   DMA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADVANCED STOR.     ISA-SCSI                             DMA
      ASC-88             XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ADVANCED STOR.     MCA-SCSI                             16 BYTE BUFFER
      ASC-PS2            MCA                                  DMA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ALWAYS TECH.       EISA-SCSI        7HD       B  1/2    0-32MB CACHE
      AL-4000            EISA                       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ALWAYS TECH.       ISA-SCSI         7HD       B  1/2    PROG'D I/O
      IN-2000            AT               2FD       C   XT    OR DMA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      AMS                ISA-ST412(MFM)   2HD
      1100S              AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      AMS                ISA-ST412(MFM)   2HD
      1100SM             AT         1:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      AMS                ISA-ST412(MFM)   2HD
      1100SM4            AT         1:1   4FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      AMS                ISA-ST412(RLL)   2HD                 SHORT CARD
      1100SR4            AT         1:1   4FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ATD                ISA-ST412(MFM)   2HD  2048 B  1/2
      220-000            AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ATD                ISA-ST412(MFM)   2HD  2048 B  1/2
      220-001            AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ATD                ISA-ST412(RLL)   2HD  2048 B
      221-000            AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  4
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      ATD                ISA-ST412(RLL)   2HD  2048 B
      221-001            AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ATD                ISA-ESDI         2HD  2048 B
      222-000            AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ATD                ISA-ESDI         2HD       B         24Mbps
      222-001            AT         1:1                 XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      AXES TECHNOLOHY    ISA-SCSI         7HD                 1-4MB CACHE
      SOFI-16            AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      BUSTEK             ISA-SCSI         7HD                 DMA
      BT-542             AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      BUSTEK             MCA-SCSI         7HD                 DMA
      BT-640             MCA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      BUSTEK             EISA-SCSI        7HD                 BUS MASTERING
      BT-742A            EISA             2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      C & C TECHNOLOGY   ISA-SCSI                             DIFF.SCSI, DMA
      CC-THDC            AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      C.S.C.             ISA-SCSI         7HD       B  FULL   256K-8MB CACHE
      FASTCACHE 32       AT               4FD       C   AT    (STANDARD SIMMS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      CHICONY            ISA-IDE(AT)      2HD                 1-SERIAL,
      C101B              AT               2FD                 1-PAR. PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      CIPRICO            ISA-SCSI         7HD
      RIMFIRE 5500       AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      COGENT DATA        ISA-ST412/ESDI   4HD                 DISK MIRRORING
      DISKMASTER         AT         1:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      COMMAX TECH.       ISA-ST412(MFM)   2HD          3/4
      EXCELL-HDC6V       AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      COMPUADD           ISA-ESDI         2HD       B  FULL   .25-4MB CACHE
      HARDCACHE ESDI     AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      CORE INTL.         MCA-ESDI         2HD          FULL   .25-4MB CACHE
      CNT-IMC            MCA        1:1                 MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      CORE INTL.         MCA-ST412M/ESDI  2HD          FULL
      CNT-MCK            MCA        1:1                 MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      COREL SYSTEMS      ISA-SCSI         *         *  1/2    *OPTIONAL BIOS
      LS2000             XT,AT                          XT    PI/O,128B BUFF
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  5
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      D.P.T.             PROPRIETARY                          CACHING MODULE
      CM401x                                                  W/512K
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          DISK MIRRORING
      DM401x                                                  MODULE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          PLUG-IN 2MBYTE
      MM3011/2           NONE                                 MEMORY MODULE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          PLUG-IN 4MBYTE
      MM3011/4           NONE                                 MEMORY MODULE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          2MB MEMORY
      MM401x/2                                                MODULE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          4MB MEMORY
      MM401x/4                                                MODULE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          4MB MEM.CARD &
      MX3011/4           NONE                                 TAKES 2 MEM.MOD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             PROPRIETARY                          4MB EXPANSION
      MX401x/4                                                BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-SCSI         7HD       B  3/4    EATA-PIO SPEC.
      PM2001/90          AT                             AT    SmartConnex
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-SCSI         7HD       B  3/4    EATA-PIO SPEC.
      PM2001/95          AT               2FD           AT    SmartConnex
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             EISA-SCSI        7HD       B  FULL   EATA-DMA SPEC.
      PM2012/90          EISA                           AT    SmartConnex
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             EISA-SCSI        7HD       B  FULL   EATA-DMA SPEC.
      PM2012/95          EISA             2FD           AT    SmartConnex
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-ST412(MFM)   2HD       B  FULL   .5-4.5MB CACHE
      PM3011/50          AT         1:1                 AT    OPT. MEM.MODS.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-ST412(MFM)   2HD       B  FULL   .5-4.4MB CACHE
      PM3011/55          AT         1:1   2FD           AT    OPT. MEM.MODS.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-ST412(RLL)   2HD       B  FULL   .5-4.5MB CACHE
      PM3011/60          AT         1:1                 AT    OPT. MEM.MODS.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-ST412(RLL)   2HD       B  FULL   .5-4.5MB CACHE
      PM3011/65          AT         1:1   2FD           AT    OPT. MEM.MODS.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-ESDI         4HD       B  FULL   .5-4.5MB CACHE
      PM3011/70          AT         1:1                 AT    OPT. MEM.MODS.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  6
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      D.P.T.             ISA-ESDI         4HD       B  FULL   .5-4.5MB CACHE
      PM3011/75          AT         1:1   2FD           AT    OPT. MEM.MODS.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-FLOPPY                           NO LONGER AVAIL
      PX3011/05                           2FD                 50-70 ADD-ON
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-FLOPPY/SCSI  7HD                 NO LONGER AVAIL
      PX3011/059                          2FD                 50-70 ADD-ON
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      D.P.T.             ISA-SCSI         7HD                 NO LONGER AVAIL
      PX3011/09                                               50-70 ADD-ON
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-SCSI         7HD       B  1/2    PROG'D I/O
      DTC-3150           XT,AT                      C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-SCSI         7HD       B  1/2    PROG'D I/O
      DTC-3180           AT                         C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-SCSI         7HD       B  1/2    PROG'D I/O
      DTC-3250           XT,AT            3FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-SCSI         7HD       B  1/2    PROG'D I/O
      DTC-3280           AT               4FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    EISA-SCSI        7HD       B  FULL   BUS MASTERING
      DTC-3290E          EISA             4FD           AT    .5-4MB CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-FLOPPY                    1/2    FLOPPY ONLY
      DTC-5110           XT,AT            3FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(MFM)   2HD  2048 B  1/2
      DTC-5150X          XT         2:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(MFM)   2HD  2048 B  1/2
      DTC-5150XL         XT         2:1         16  C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(RLL)   2HD  2048 B  1/2
      DTC-5160X          XT         2:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(RLL)   2HD  2048 B  1/2
      DTC-5160XL         XT,AT      2:1         16  C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(MFM)   2HD  2048 B  1/2    POWER CONNECTOR
      DTC-5180i          AT                     16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(RLL)   2HD  2048 B  1/2    POWER CONNECTOR
      DTC-5187i          AT                     16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(MFM)   2HD  2048    FULL
      DTC-5280i          AT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  7
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      DATA TECHNOLOGY    ISA-ST412(RLL)   2HD  2048 B  FULL
      DTC-5287i          AT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ESDI         2HD  4096 B  FULL
      DTC-6180           AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ESDI         2HD  *    B  FULL   .5-4MB CACHE
      DTC-6180-15C       AT         1:1         16            *>1024 CYL SUPT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ESDI         2HD  *    B  3/4    TRACK BUFFER
      DTC-6180-15T       AT         1:1         16      XT    *>1024 CYL SUPT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ESDI         2HD  4096 B  FULL
      DTC-6280           AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ESDI         2HD  *    B  FULL   .5-4MB CACHE
      DTC-6280-15C       AT         1:1   4FD   16            *>1024 CYL SUPT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ESDI         2HD  *    B  3/4    TRACK BUFFER
      DTC-6280-15T       AT         1:1   4FD   16            *>1024 CYL SUPT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    EISA-ESDI        4HD       B  FULL   .5-4MB CACHE
      DTC-6280SE-15C     EISA       1:1                 AT    BUS MASTERING
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    EISA-ESDI                            .5-4MB CACHE
      DTC-6295           EISA       1:1                       BUS MASTERING
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(MFM)   2HD  2048 B  1/2    POWER CONNECTOR
      DTC-7180           AT         1:1         16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(RLL)   2HD  2048 B  1/2    POWER CONNECTOR
      DTC-7187           AT         1:1         16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(MFM)   2HD  2048 B  FULL
      DTC-7280           AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      DATA TECHNOLOGY    ISA-ST412(RLL)   2HD  2048 B  FULL
      DTC-7287           AT         1:1   2FD   16  C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EMULEX             ISA-SCSI         7HD                 HOST ADAPTER
      IB01               PC,XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EMULEX             ISA-SCSI         7HD                 HOST ADAPTER
      IB02               AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EMULEX             SCSI-ESDI                            DOES NOT PLUG
      MD21               NONE                                 INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EMULEX             SCSI2-ESDI       4HD                 DOES NOT PLUG
      MD25A              NONE       1:1                       INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  8
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      EMULEX             SCSI2/DIF-ESDI   4HD                 DIF.SCSI, DOES-
      MD26A              NONE       1:1                       NOT PLUG IN BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EMULEX             SCSI-QIC36                           TAPE,DOES NOT
      MT-02              NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EVEREX             ISA-ST412(MFM)   2HD
      EV-332             AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EVEREX             ISA-ST412(MFM)   2HD
      EV-346             AT         1:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EVEREX             ISA-ST412(MFM)   2HD  1024 B  3/4
      EV-390             XT         5:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EVEREX             ISA-ST412(MFM)   2HD  1024 B  3/4
      EV-391             XT         5:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      EVEREX             ISA-ST412(RLL)   2HD  1024 B  3/4
      EV-392             XT         5:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FARADAY            ISA-FLOPPY                    1/2    FLOPPY ONLY
      FE5140             PC,XT            4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(MFM)   2HD
      TNT-1000           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(RLL)   2HD
      TNT-1000R          AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(MFM)   2HD
      TNT-1050           AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(RLL)   2HD
      TNT-1050R          AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(MFM)   2HD                 FOR >10MHz BUS
      TNT-1250           AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(RLL)   2HD                 FOR >10MHz BUS
      TNT-1250R          AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ST412(MFM)   2HD                 1->16MB CACHE
      TNT-1610           AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ESDI         4HD       B  FULL   2-10MB CACHE,
      TNT-2210           AT         1:1   2FD           AT    BUS MASTERING
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-ESDI         4HD       B  FULL   2-10MB CACHE,
      TNT-2410           AT         1:1   2FD           AT    BUS MASTERING
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE  9
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      FAST TECHNOLOGY    ISA-ESDI         4HD       B  FULL   2-10MB CACHE,
      TNT-2610           AT         1:1   2FD           AT    BUS MASTERING
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-2x10 CARDS                       2MB CACHE EXP.
      TNT-3020                                                FOR 2x10 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-2x10 CARDS                       4MB CACHE EXP.
      TNT-3040                                                FOR 2x10 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-2x10 CARDS                       6MB CACHE EXP.
      TNT-3060                                                FOR 2x10 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-2x10 CARDS                       8MB CACHE EXP.
      TNT-3080                                                FOR 2x10 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       0MB CACHE EXP.
      TNT-3100                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       2MB CACHE EXP.
      TNT-3120                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       4MB CACHE EXP.
      TNT-3140                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       6MB CACHE EXP.
      TNT-3160                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       8MB CACHE EXP.
      TNT-3180                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       10MB CACHE EXP.
      TNT-3200                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    TNT-50x0 CARDS                       12MB CACHE EXP.
      TNT-3210                                                FOR 50x0 SERIES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI-1,2     7HD       B  3/4    E-P'd I/O
      TNT-4000           AT                         C   AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI-1,2     7HD       B  3/4    E-P'd I/O
      TNT-4050           AT               2FD       C   AT    4, 20MB FLOPPYS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI-1,2     7HD       B  3/4    E-P'd I/O
      TNT-4100           AT                         C   AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI-1,2     7HD       B  3/4    E-P'd I/O
      TNT-4150           AT               2FD       C   AT    4, 20MB FLOPPYS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-IDE(AT)      2HD       B  FULL   .5-4MB CACHE
      TNT-5000           AT         1:1   2FD           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 10
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      FAST TECHNOLOGY    ISA-IDE(AT)      2HD       B  FULL   .5-4MB CACHE
      TNT-5010           AT         1:1   2FD           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-IDE(AT)      2HD       B  FULL   .5-4MB CACHE
      TNT-5020           AT         1:1   2FD           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-IDE(AT)      2HD       B  FULL   .5-4MB CACHE
      TNT-5040           AT         1:1   2FD           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI         7HD       B         .5MB CACHE
      TNT-6000           AT                         C
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI         7HD       B         .5MB CACHE
      TNT-6100           AT               2FD       C
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI         7HD       B         2MB CACHE
      TNT-6120           AT               2FD       C
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FAST TECHNOLOGY    ISA-SCSI         7HD       B         4MB CACHE
      TNT-6140           AT               2FD       C
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      MCA-SCSI         7HD          FULL   HOST ADAPTER
      MCS-350            MCA                            MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      MCA-SCSI-2       7HD          FULL
      MCS-700            MCA                            MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI-2       7HD       B
      TMC-1660           AT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI-2       7HD       B
      TMC-1680           AT               4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD          1/2    PROG'D I/O
      TMC-830            PC,XT,AT                       XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD       B  1/2    PROG'D I/O
      TMC-841            PC,XT,AT                   C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD          1/2    PROG'D I/O
      TMC-841RL          PC,XT,AT                   C   XT    NO BOOT PROM
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD          1/2    PROG'D I/O
      TMC-845            PC,XT,AT                   C   XT    NO BOOT PROM
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD       B  1/2    PROG'D I/O
      TMC-850            PC,XT,AT                   C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD       B  1/2    PROG'D I/O
      TMC-860            AT                             XT    PWR CONN.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 11
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      FUTURE DOMAIN      ISA-SCSI         7HD          3/4    PROG'D I/O
      TMC-870            PC,XT,AT         4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD
      TMC-871            XT,AT            4FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD       B  3/4    PROG'D I/O
      TMC-875            XT,AT            4FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD          3/4    PROG'D I/O
      TMC-881            AT               4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      FUTURE DOMAIN      ISA-SCSI         7HD       B  3/4    PROG'D I/O
      TMC-885            AT               4FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                AT-ESDI          4HD  2046 B  3/4    R/S ECC, CACHE,
      1495-05            AT         1:1                 XT    DISKSHADOW
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                AT-ESDI          4HD  2046 B  3/4    R/S ECC, CACHE,
      1495-44            AT         1:1   4FD           XT    DISKSHADOW
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                AT-ESDI*         4HD  2046 B  3/4    R/S ECC, CACHE,
      1495-M4            AT         1:1                 XT    DISKSHADOW
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                ISA-EHD FLOPPY                1/2    2.88MB FLOPPYS
      EHD-10             AT               2FD       C   XT    PRI. or SEC.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                ISA-IDE(AT)      2HD          1/2    2.88MB FLOPPYS
      EHD-20             AT               2FD           XT    PRIMARY ONLY
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                ISA-IDE(AT)      2HD       B  1/2    2.88 FLOPPYS
      EHD-21             AT               4FD           XT    2.88 BOOT CAP.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      GSI                ISA-IDE(AT)      HD        B  1/2    2.88MB FLOPPYS
      EHD-2S             AT               4FD           XT    SECURITY MODEL
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      INTERPHASE         EISA-SCSI        7HD       B  FULL   128K BUFFER,2ND
      4810 BARRACUDA     EISA       1:1                       SCSI CHAN. OPTN
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JC INFO SYSTEMS    ISA-FLOPPY                    1/2    FLOPPY ONLY
      1100-000           XT,AT            2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JC INFO SYSTEMS    ISA-ST412(MFM)   2HD          1/2
      1110-000           AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JC INFO SYSTEMS    ISA-IDE(AT)      2HD          1/2
      1120-000           AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JC INFO SYSTEMS    ISA-IDE(AT)      2HD          1/2    1 PARALLEL
      1120-100           AT         1:1   2FD           XT    1 SERIAL PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 12
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      JC INFO SYSTEMS    ISA-IDE(AT)      2HD          1/2    1 PARALLEL
      1120-200           AT         1:1   2FD           XT    2 SERIAL PORTS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JC INFO SYSTEMS    ISA-ST412(MFM)   2HD          1/2
      2110-100           AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JC INFO SYSTEMS    ISA-ESDI         2HD
      2132-100           AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JETS CYBERNETICS   MCA-SCSI                             DIFF.SCSI, DMA
      SURFBOARD XPe      MCA                                  128K-1M CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      JETS CYBERNETICS   EISA-SCSI                            DIFF.SCSI, DMA
      SURFBOARD XPe      EISA                                 128K-1M CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KALOK              ISA-IDE(AT)      2HD          1/2
      KL-03              AT                         C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KALOK              ISA-IDE(AT)      2HD          1/2    2 FLOPPY ADDRS.
      KL-03F             AT               2FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KALOK              ISA-IDE(AT)      2HD          1/2    2 FLOPPY ADDRS.
      KL-03S             AT               2FD       C   XT    1-P, 1-S PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KIMPSION           ISA-ST412(MFM)   2HD  2048    3/4
      WA3-16             AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KIMPSION           ISA-ST412(MFM)   2HD  2048    3/4
      WA6-V              AT         2:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KONAN              ISA-ST412(MFM)   2HD
      DJ-210             PC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KONAN              ISA-ST412(MFM)   2HD
      TNT-1000           AT         1:1                 XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KONAN              ISA-ST412(MFM)   2HD
      TNT-1050           AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      KONAN              ISA-ESDI         2HD                 2-10MB CACHE
      TNT-ESDI           AT         1:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LARK ASSOCs.       ISA-ESDI         2HD       B         2-64KB CACHE
      LRK-330            AT         1:1                 XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LARK ASSOCs.       ISA-ESDI         2HD       B         2-64KB CACHE
      LRK-331            AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LOMAS DATA PROD.   ISA-SCSI         7HD       B  FULL   1-16MB CACHE
      LDP CACHE II       AT               2FD           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 13
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      LONGSHINE          ISA-ST412(MFM)   2HD  1024           11-BIT EC
      LCS-6210ASIC       XT                     16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD  1024           11-BIT EC
      LCS-6210D          XT                     16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD  1024           11-BIT EC
      LCS-6210W          XT                     16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(RLL)   2HD  1024
      LCS-6217           XT                      8      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD  1024           11-BIT EC
      LCS-6220           XT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD
      LCS-6220ASIC       AT         2:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-FLOPPY                           FLOPPY ONLY
      LCS-6610F          XT,AT            2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD  1024           WD1006-WAH
      LCS-6611           AT         1:1         16            COMPATIBLE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(RLL)   2HD
      LCS-6617           AT         2:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD
      LCS-6620ASIC       AT         2:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD  1024           WD1006-WA2
      LCS-6622           AT         1:1   2FD   16            COMPATIBLE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(MFM)   2HD
      LCS-6622NCL        AT         1:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-IDE(AT)      2HD
      LCS-6623           AT               2FD       C
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-IDE(AT)      2HD                 2-SER, 1-PAR.
      LCS-6624           AT               2FD       C         PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-IDE(AT)      2HD                 2-SER, 1-PAR,
      LCS-6624G          AT               2FD       C         1-GAME PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-ST412(RLL)   2HD
      LCS-6627           AT         2:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-SCSI         6HD       B
      LCS-6630           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 14
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      LONGSHINE          ISA-SCSI         6HD       B
      LCS-6630F          AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-SCSI         6HD       B         CD ROM BIOS
      LCS-6631           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-SCSI         6HD       B         CD ROM BIOS
      LCS-6631F          AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-SCSI/ST412M  6HD       B         INC. ST412(MFM)
      LCS-6632           AT                                   CD ROM BIOS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-FLOPPY                           SECONDARY
      LCS-6812F          XT,AT            2FD           XT    FLOPPY CTRL.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-FLOPPY                           FLOPPY ONLY
      LCS-6814F          XT,AT            4FD           XT    EXT.CONN.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-FLOPPY                           2.88MB CAPACITY
      LCS-6815F          XT,AT            4FD           XT    FLOPPY DRIVES
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-QIC-02                           QIC-02 TAPE
      LCS-6818EV1        XT,AT                          XT    INTERFACE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-SCSI         2HD       B
      LCS-6821N-H        XT,AT                      C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      LONGSHINE          ISA-SCSI(TAPE)   2HD       B         QIC-02 TAPE &
      LCS-6821N-T        XT,AT                          XT    SCSI HD INTERF.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MANZANTA MICROSYS  ISA-FLOPPY                    1/2    FLOPPY ONLY
      3RD INTN. MUX      PC,XT,AT         3FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MANZANTA MICROSYS  ISA-FLOPPY                    1/2    FLOPPY ONLY
      HI-DENS.CONTR.     PC,XT            4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MANZANTA MICROSYS  ISA-FLOPPY                    1/2    FLOPPY ONLY
      MUX ADAPT.CARD     PC,XT,AT         2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MAPLE SYSTEMS      ISA-ESDI         2HD  4096 B  3/4    25 MHz CHANNEL
      MC-1165A           AT         1:1   2FD   16      XT    64KB CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MAXTOR COLORADO    ISA-IDE(AT)      2HD          1/2
      AKF (AT-FIB)       AT               2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MAXTOR COLORADO    PS/2-IDE(AT)     1HD       B  1/2    PS/2 MODEL 30
      AKPS/2 (PS/2)      PS/2(30)                       XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MAXTOR COLORADO    ISA-IDE(AT)      2HD          1/2
      AKS (AT-SIB)       AT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 15
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      MICRO SOLUTIONS    ISA-FLOPPY                    1/2    FLOPPY ONLY
      COMPATICARD        PC,XT,AT         4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MICRO SOLUTIONS    ISA-FLOPPY                    1/2    FLOPPY ONLY
      COMPATICARD II     PC,XT,AT         2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MICRO SOLUTIONS    ISA-FLOPPY                    1/2    FLOPPY ONLY
      COMPATICARD IV     PC,XT,AT         4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MITSUBISHI         ESDI-SCSI                            FOR MW-5D1 CD
      MW-5C1             NONE                                 DRIVE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MYLEX              32BIT-SCSI       7HD          FULL   32BIT, DMA
      DC-376             32BIT AT   1:1                 XT    4MEG CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      MYLEX              EISA-SCSI        7HD       B  FULL   .5-8MB CACHE
      DCE-376            EISA       1:1   2FD           AT    BUS MASTERING
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        SCSI-ST412(MFM)  2HD  2048           DOES NOT
      NCL-3016           NONE                   16  C         PLUG-IN
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        SCSI-ST412(RLL)  2HD  2048           DOES NOT
      NCL-3026           NONE                   16  C         PLUG-IN
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-SCSI         7HD          1/2    HOST ADAPTER
      NCL-500            XT,AT                          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-FLOPPY                    1/2    FLOPPY ONLY
      NCL-5034           PC,XT,AT         2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(RLL)   2HD  2048    1/2
      NCL-5235           AT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(RLL)   2HD  2048    1/2
      NCL-5236           AT                     16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(RLL)   2HD  2048    1/2
      NCL-5255           AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(RLL)   2HD  2048    1/2
      NCL-5256           AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ESDI         2HD  2048    3/4
      NCL-5335           AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ESDI         2HD  2048    1/2
      NCL-5336           AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ESDI         2HD  2048    3/4    16-64KB CACHE
      NCL-5355           AT         1:1   2FD   16      XT    4096 CYLS ?
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 16
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      NCL AMERICA        ISA-ESDI         2HD  2048    1/2
      NCL-5356           AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-SCSI                             PROG'D I/O
      NCL-540            XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(MFM)   2HD  2048    1/2
      NCL-5425           AT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(MFM)   2HD  2048    1/2
      NCL-5426           AT                     16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(MFM)   2HD  2048    1/2
      NCL-5455           AT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(MFM)   2HD  2048    1/2
      NCL-5456           AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        ISA-ST412(MFM)   2HD  2048    1/2
      NCL-5525           AT               2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCL AMERICA        MCA-SCSI                             DMA
      NCL-600            MCA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCR                ISA-SCSI                             DMA
      ADP-31S            XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NCR                MCA-SCSI-2       7HD       B  FULL   BUS MASTERING
      ADP-37             MCA3                       C   MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NEC                ESDI-SMD         1HD  4096           FOR NEC 5600
      DA501              NONE                                 DRIVES ONLY
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NEC                ESDI-IPI-2       1HD                 FOR NEC 5600
      DA521              NONE                                 DRIVES ONLY
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      NOVELL             EISA-SCSI        7HD
      NE-3200
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERCEPTIVE SOLS.   PRO.-ESDI        2HD  2048 B         ADD-ON BOARD
      ESDI               AT         1:1         16  C         FOR SPU (4 MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERCEPTIVE SOLS.   ISA-PROPRIETARY               FULL   MAIN SPU BOARD
      HS16 / 1600SPU     AT         1:1                       4MB CACHE (MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERCEPTIVE SOLS.   ISA-PROPRIETARY               FULL   MAIN SPU BOARD
      HS8 / 816SPU       AT                                   4MB CACHE (MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERCEPTIVE SOLS.   PRO.-IDE(AT)     2HD                 ADD-ON BOARD
      IDE                AT         1:1                       FOR SPU (4 MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 17
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      PERCEPTIVE SOLS.   PRO.-ST412(MFM)  2HD  2048 B         ADD-ON BOARD
      MFM                AT         1:1         16  C         FOR SPU (4 MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERCEPTIVE SOLS.   PRO.-ST412(RLL)  2HD  2048 B         ADD-ON BOARD
      RLL                AT         1:1         16  C         FOR SPU (4 MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERCEPTIVE SOLS.   PRO.-SCSI        7HD                 ADD-ON BOARD
      SCSI               AT         1:1                       FOR SPU (4 MAX)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERFORM. TECHS.    SCSI-FLOPPY                          DOES NOT
      PT-SCS350          NONE             4FD       C         PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERSTOR SYSTEMS    ISA-ST412*       2HD  1024 B  1/2    *ADRT (ARLL)
      ADRC-9008          XT,AT      3:1         15      XT    (32 SECT/TRACK)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERSTOR SYSTEMS    ISA-ST412*       2HD  2048 B  FULL   *ADRT (ARLL)
      PS180-16FN         AT         3:1   2FD   15      AT    (31 SECT/TRACK)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERSTOR SYSTEMS    ISA-ST412*       2HD  1024 B  FULL   *ADRT (ARLL)
      PS180-8XT/AT       XT,AT      3:1         15      XT    (31 SECT/TRACK)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERSTOR SYSTEMS    ISA-ST412*       2HD  2048 B  FULL   *ADRT,LTD.PROD.
      PS200-16F          AT         3:1   2FD   15      AT    (34 SECT/TRACK)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PERSTOR SYSTEMS    ISA-ST412*       2HD       B  FULL   *ADRT,LTD.PROD.
      PS200-8            XT,AT      3:1                 XT    (34 SECT/TRACK)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PIONEER            SCSI-IDI (CD)                        SCSI->4 IDI CDs
      DD-C5001           NONE                                 DOESN'T PLUG IN
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PIONEER            ISA-SCSI & IDI   2HD       B  FULL   ISA->2 IDI CDs
      DD-C5002           AT                             XT    & 2 SCSI HDs
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PIONEER            ISA-SCSI         2HD          1/2    REQUIRES SFTWR:
      DDI-80AT           XT,AT                          XT    DDS-81AT, 51AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PROCOMP USA        ISA-SCSI         2HD       B  FULL   FOR NOVELL LAN
      M-DCB              AT                         C   AT    BIOS OPTIONS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PROCOMP USA        MCA-SCSI         2HD       B  FULL   FOR NOVELL LAN
      M-DCB/2            MCA                        C         BIOS OPTIONS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PTI                ISA-FLOPPY                           FLOPPY ONLY
      PTI-151            XT,AT            2HD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PTI                ISA-FLOPPY                           FLOPPY ONLY
      PTI-158            XT,AT            4FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      PTI                ISA-IDE(AT)      2HD
      PTI-215            AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 18
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      PTI                ISA-IDE(AT)      2HD                 2S,SP,1G PORTS
      PTI-217            AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RANCHO TECHNOLOGY  ISA-SCSI         7HD          FULL   BUS MASTERING
      RT-10-AT           AT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RANCHO TECHNOLOGY  ISA-SCSI         7HD          1/2    PROG'D I/O
      RT-10-XT           XT,AT                          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RANCHO TECHNOLOGY  ISA-SCSI         7HD          1/2    PROG'D I/O
      RT-100-XT          XT,AT            4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RANCHO TECHNOLOGY  MCA-SCSI         7HD                 PROG'D I/O
      RT-1000-MC         MCA                            MC    2K BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RANCHO TECHNOLOGY  ISA-SCSI         7HD          1/2
      RT-1000A           XT,AT                          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RANCHO TECHNOLOGY  ISA-SCSI         7HD          1/2    PROG'D I/O
      RT-1000A-4         XT,AT            4FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RELAX TECH.        ISA-SCSI                             PROG'D I/O
      T-100              PC,XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RELAX TECH.        ISA-SCSI                             DMA
      T-128              PC,XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RELAX TECH.        MCA-SCSI                             PROG'D I/O
      T-200              MCA
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      RMT SYSTEMS        ISA-ST412(MFM)   2HD       B
      RMT2001-F2H2       XT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-SCSI         2HD  1024 B  1/2    PROG'D I/O
      ST01               PC,XT,AT               16  C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-SCSI         2HD  1024 B  1/2    PROG'D I/O
      ST02               PC,XT,AT         2FD   16  C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-IDE(XT)      2HD  1024 B  1/2    POWER CONNECTOR
      ST05X              XT                     16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-IDE(AT)      2HD  1024    1/2    POWER CONNECTOR
      ST07A              AT                     16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-IDE(AT)      2HD  1024    1/2    POWER CONNECTOR
      ST08A              AT               2FD   16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-ST412(MFM)   2HD  1024 B  1/2    POWER CONNECTOR
      ST11M              PC,XT,AT               16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 19
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      SEAGATE TECH.      ISA-ST412(RLL)   2HD  1024 B  1/2    POWER CONNECTOR
      ST11R              PC,XT,AT               16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-ST412(MFM)   2HD  1024 B  1/2    POWER CONNECTOR
      ST21M              AT         1:1         16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-ST412(RLL)   2HD  1024 B  1/2    POWER CONNECTOR
      ST21R              AT         1:1         16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-ST412(MFM)   2HD  1024 B  1/2    POWER CONNECTOR
      ST22M              AT               2FD   16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SEAGATE TECH.      ISA-ST412(RLL)   2HD  1024 B  1/2    POWER CONNECTOR
      ST22R              AT               2FD   16      XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SILICON VALLEY     ISA-IDE(AT)      2HD          1/2    POWER CONNECTOR
      ADP20              AT                             XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SILICON VALLEY     ISA-IDE(AT)      2HD          1/2    POWER CONNECTOR
      ADP20F             AT               2FD           XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SILICON VALLEY     ISA-IDE(XT)      2HD       B  1/2    POWER CONNECTOR
      ADP50              XT                             XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SILICON VALLEY     ISA-IDE(AT)      2HD       B  1/2
      CADP60             AT               4FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SILICON VALLEY     ISA-SCSI         7HD       B  1/2    HOST ADAPTER
      GOLD-MINE 1100     PC,XT,AT         2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES
      OMTI 20C
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES
      OMTI 20D
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   SCSI-RLL
      OMTI 3127A-2D
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI         7HD                 HOST ADAPTER
      OMTI 510HAX        PC,XT,AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI (OCS)                       HOST ADAPTER
      OMTI 512-HA3
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI         7HD                 HOST ADAPTER
      OMTI 512-HA7
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD
      OMTI 5520A         XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 20
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD
      OMTI 5526          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(RLL)   2HD          1/2
      OMTI 5527A         XT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD
      OMTI 6510          XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI         7HD       B  FULL   P'D I/O or DMA
      OMTI 810           AT                         C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI         7HD       B  FULL   P'D I/O or DMA
      OMTI 812           AT                         C   XT    EXTERNAL CONN.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD          1/2
      OMTI 8120          AT         1:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(RLL)   2HD          1/2
      OMTI 8127          AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD  2048    1/2
      OMTI 8130          AT         2:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD  2048 B  1/2
      OMTI 8151          AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(RLL)   2HD  2048 B  1/2
      OMTI 8157          AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI         7HD       B  FULL   P'D I/O or DMA
      OMTI 820                            2FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-SCSI         7HD       B  FULL   P'D I/O or DMA
      OMTI 822           AT               2FD       C   XT    EXTERNAL CONN.
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD  2048    1/2
      OMTI 8230          AT         2:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(RLL)   2HD  2048    FULL
      OMTI 8247          AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(MFM)   2HD  2048 B  1/2
      OMTI 8250          AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(RLL)   2HD  2048 B  1/2
      OMTI 8257          AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD
      OMTI 8620          AT         1:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 21
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      SMS TECHNOLOGIES   ISA-ESDI         2HD
      OMTI 8627          AT         1:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ST412(RLL)   2HD
      OMTI 8627A         AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD  2048 B  FULL   32K CACHE
      OMTI 8630          AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD  2048 B  FULL   32K CACHE
      OMTI 8631          AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD  2048 B  FULL   32K CACHE
      OMTI 8640          AT         1:1   2FD   16      XT    15Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD  2048 B  FULL   32K CACHE
      OMTI 8641          AT         1:1         16      XT    15Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SMS TECHNOLOGIES   ISA-ESDI         2HD       B  FULL   32K CACHE
      OMTI 8650          AT         1:1   2FD           XT    24Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SOTA               ISA-FLOPPY                    1/2    2 PARALLEL
      FLOPPY I/O +       PC,XT            4FD           XT    2 SERIAL PORTS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SPECIALTY DEV.     ISA-ESDI         2HD  2048 B  FULL   .5-4MB CACHE
      400 (ESDI)         AT         1:1   2FD   16      AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SPECIALTY DEV.     ISA-IDE(AT)      2HD       B  FULL   .5-4MB CACHE
      400 (IDE)          AT         1:1   2FD           AT    64KB BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SPECIALTY DEV.     ISA-ST412(MFM)   2HD  2048 B  FULL   .5-4MB CACHE
      400 (MFM)          AT         1:1   2FD   16      AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SPECIALTY DEV.     ISA-ST412(RLL)   2HD  2048 B  FULL   .5-4MB CACHE
      400 (RLL)          AT         1:1   2FD   16      AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      SPECIALTY DEV.     ISA-SCSI-2       2HD       B  FULL   .5-4MB CACHE
      400 (SCSI)         AT               2FD           AT    32KB BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      STB SYSTEMS        ISA-IDE(AT)      2HD
      POWERDRIVE IDE     AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      STB SYSTEMS        ISA-ST412(MFM)   2HD                 32K CACHE, OPT.
      POWERDRIVE MFM     AT               2FD                 2-SER,1-P PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      STB SYSTEMS        ISA-ST412(RLL)   2HD                 32K CACHE, OPT.
      POWERDRIVE RLL     AT               2FD                 2-SER,1-P PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      STORAGE PLUS       ISA-SCSI         7HD       B  3/4    PROG'D I/O
      SCSI-AT            AT               2FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 22
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      STORAGE RESEARCH   ISA-SCSI         7HD       B  1/2    PROG'D I/O
      SR-9               PC,XT,AT         2FD           XT    1 SPEED FLOPPYS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      TEGA TECHNOLOGIES  ISA-SCSI         7HD       B  1/2    PROG'D I/O
      SM-911S            PC,XT,AT         2FD           XT    1 SPEED FLOPPYS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      TRANTOR SYSTEMS    ISA-SCSI         7HD       *  1/2    *OPTIONAL, DMA
      T100               PC,XT,AT                   C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      TRANTOR SYSTEMS    ISA-SCSI         7HD       B  1/2    DMA
      T128               AT                         C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      TRANTOR SYSTEMS    ISA-SCSI         7HD       B  1/2    DMA
      T128F              AT               4FD       C   XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      TRANTOR SYSTEMS    MCA-SCSI         7HD       B  1/2
      T228               MCA                        C   MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      TRANTOR SYSTEMS    LPT1-LPT1/SCSI   7HD                 CONNECTS TO
      T338               PRINTER                              PRINTER PORT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ULTRASTOR          ISA-ESDI         2HD  4096 B  FULL   .5-16MB CACHE
      ULTRA 12C          AT         1:1   3FD   16  C   XT    20Mb/SEC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ULTRASTOR          ISA-ESDI         2HD  4096 B  3/4    32KB CACHE
      ULTRA 12F          AT         1:1   3FD   16  C   XT    24Mb/SEC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ULTRASTOR          ISA-SCSI                             512K CACHE, DMA
      ULTRA 14C          AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ULTRASTOR          ISA-SCSI                             64K CACHE, DMA
      ULTRA 14F          AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ULTRASTOR          EISA-ESDI        2HD  4096 B  FULL   .5-4MB CACHE
      ULTRA 22C          EISA       1:1         16  C   AT    24Mb/SEC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      ULTRASTOR          EISA-SCSI        7HD       B  FULL   64KB CACHE
      ULTRA 24F          EISA             3FD       C   AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    SCSI-ESDI        2HD                 DOES NOT
      ADSI-D215S         NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    CPU-ST412(MFM)   2HD                 DOES NOT
      WD1001-WAH         NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  1024 B  1/2    POWER CONNECTOR
      WD1002-27X         PC,XT,AT               16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  1024 B  1/2    SUPERBIOS
      WD1002A-27X        PC,XT,AT               16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 23
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      WESTERN DIGITAL    ISA-FLOPPY                 *  1/2    *OPT#1=2F,#2=4F
      WD1002A-FOX        XT,AT            *FD           XT    #4=#2&BIOS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  1024 B  1/2    POWER CONNECTOR
      WD1002A-WX1        PC,XT,AT               16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    SASI-ST412(MFM)  2HD                 DOES NOT
      WD1002S-SHD        NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048    FULL
      WD1003-RA2         AT         3:1   2FD   16      AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048    FULL   COMPAQ SETTINGS
      WD1003-RAH         AT         3:1         16      AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  2048 B  FULL
      WD1003-WA2         AT         3:1   2FD   16      AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  2048           COMPAQ SETTINGS
      WD1003-WAH         AT         3:1         16
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD
      WD1003A-RA2        AT         2:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    SCSI-ST412(MFM)  2HD                 DOES NOT
      WD1003A-SCS        NONE                                 PLUG INTO BUS
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  2048    FULL
      WD1003A-WA2        AT         3:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD          3/4
      WD1003S-RA2        AT         2:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD          3/4    COMPAQ SETTINGS
      WD1003S-RAH        AT         2:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD          3/4
      WD1003S-WA2        AT         2:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD          3/4    COMPAQ SETTINGS
      WD1003S-WAH        AT         2:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  1024    3/4    OPTIONAL 2KB
      WD1003V-MM1        AT         2:1         16      XT    TRACK BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  1024    3/4    OPTIONAL 2KB
      WD1003V-MM2        AT         2:1   2FD   16      XT    TRACK BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048 *  3/4    OPTIONAL 2KB
      WD1003V-SR1        AT         2:1         16      XT    TRACK BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 24
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048 *  3/4    OPTIONAL 2KB
      WD1003V-SR2        AT         2:1   2FD   16      XT    TRACK BUFFER
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  1024 B  1/2    POWER CONNECTOR
      WD1004-27X         XT,AT      4:1         16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  1024 B  1/2
      WD1004A-27X        PC,XT      4:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  1024 B  1/2    POWER CONNECTOR
      WD1004A-WX1        PC,XT      3:1         16  C   XT    ON BOARD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD
      WD1005-WAH         AT         2:1                 XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD
      WD1006-RA2         AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048 *         COMPAQ SETTINGS
      WD1006-RAH         AT         1:1         16      XT    *OPTIONAL
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD
      WD1006-WA2         AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  2048           COMPAQ SETTINGS
      WD1006-WAH         AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    MCA-ST412(MFM)   2HD  2048 B  FULL   8/32K CACHE
      WD1006V-MC1        MCA        1:1         16      MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    MCA-ST412(RLL)   2HD  2048 B  FULL
      WD1006V-MCR        MCA        1:1         16      MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  2048    3/4    CACHE
      WD1006V-MM1        AT         1:1         16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  2048    3/4    CACHE
      WD1006V-MM2        AT         1:1   2FD   16      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048 *  3/4    *BIOS OPTION
      WD1006V-SR1        AT         1:1         16      XT    CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(RLL)   2HD  2048 *  3/4    *BIOS OPTION
      WD1006V-SR2        AT         1:1   2FD   16      XT    CACHE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD          3/4
      WD1007-WA2         AT         1:1   2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD          3/4
      WD1007-WAH         AT         1:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 25
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      WESTERN DIGITAL    ISA-ESDI         2HD       *  3/4    *BIOS OPTION
      WD1007A-WA2        AT         1:1   2FD           XT    10Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD       *         *BIOS OPTION
      WD1007A-WA4        AT         1:1   2FD           XT    CACHE, 1P,1S
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD       *  3/4    *BIOS OPTION
      WD1007A-WAH        AT         1:1                 XT    10Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD       *         *BIOS OPTION
      WD1007A-WAH2       AT         1:1   2FD           XT    10Mbps
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    MCA-ESDI         2HD          FULL   32KB CACHE
      WD1007V-MC1        MCA        1:1                 MC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD       *  3/4    32KB CACHE
      WD1007V-SE1        AT         1:1                 XT    *OPTIONAL
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD       *  3/4    32KB CACHE
      WD1007V-SE2        AT         1:1   2FD           XT    *OPTIONAL
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD  2048 *  FULL   64K CACHE
      WD1009V-MM1        AT         1:1         16      XT    20Mbps, *OPTION
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ESDI         2HD  2048 *  FULL   64K CACHE
      WD1009V-MM2        AT         1:1   2FD   16      XT    20Mbps, *OPTION
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-SCSI         7HD       B  FULL   BUS MASTERING
      WD7000-AX,ASC      AT         1:1   2FD       C   AT    (DOS ONLY)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-SCSI         7HD       B  FULL   BUS MASTERING
      WD7000-FASST2      AT         1:1   2FD       C   AT    W/SOFTWARE
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    EISA-SCSI        7HD                 BUS MASTERING
      WD7000EX-FASST     EISA       1:1
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    MCA-SCSI         7HD          FULL   HOST ADAPTER
      WD7000MX-FASST     MCA        1:1                 MC    (WD7000-MSC)
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-IDE(AT)      2HD                 HOST ADAPTER
      WDAT140R           AT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-IDE(AT)      2HD                 HOST ADAPTER
      WDAT240R           AT               2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-IDE(AT)      2HD                 HOST ADAPTER
      WDAT440R           AT               2FD                 1 PAR, 1 SERIAL
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-SCSI         7HD       B  1/2    PROG'D I/O, DMA
      WDATXT-FASST       XT,AT                      C   XT    & BLIND I/O
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      Ч


      MANUFACTURER       INTERFACES       HDs  CYLs B  LGN.           PAGE 26
      MODEL NUMBER       BUS SUPT. INTLV  FDs  HEAD C  HGT.   COMMENTS
      ммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм

      WESTERN DIGITAL    ISA-ST412(MFM)   2HD          3/4    CACHE
      WDSPEEDKIT         AT         1:1   2FD           XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  1024 B  1/2    NO JUMPERS
      WDXT-GEN           PC,XT                   8      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-ST412(MFM)   2HD  1024 B  1/2
      WDXT-GEN2          XT,AT                   8      XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-IDE(XT)      1HD                 HOST ADAPTER
      WDXT140R           XT                             XT
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      WESTERN DIGITAL    ISA-IDE(XT)      1HD                 HOST ADAPTER
      WDXT150R           XT                             XT    W/PWR CONNECTOR
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      XEBEC              ISA-ST412(MFM)   2HD                 CONTROLLER
      S1210              PC,XT                                FOR IBM PC
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      XEBEC              SCSI-ST412(MFM)  2HD
      S1410              SCSI
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      XEBEC              ISA-ST412(MFM)   2HD
      S1412              PC,XT            2FD
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд
      XEBEC              ISA-ST412(MFM)
      S1421
      ддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд



       

      иммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╩
      ╨     DRIVE CONTROLLER ABBREVIATIONS            THEREF42          ╨╠
      гддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╤╠
      ╨  INTLV .... INTERLEAVE              B ....... BIOS ON BOARD     ╨╠
      ╨  HDs ...... HARD DRIVES SUPT'D.     C ....... CORESIDENT OK     ╨╠
      ╨  FDs ...... FLOPPY DRIVES           LGN ..... CARD LENGTH       ╨╠
      ╨  CYLs ..... MAX. CYLINDER SUPT.     BUS SUPT  BUS TYPES SUPT'D. ╨╠
      ╨  HEAD ..... MAX. HEADS SUPT'D                                   ╨╠
      ╨                                                                 ╨╠
      гддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╤╠
      ╨    Copyright 1989,1991 F.Robert Falbo, all rights reserved.     ╨╠
      гддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╤╠
      ╨   The User is granted permission to distribute this Listing     ╨╠
      ╨   and it's related documentation provided that it is not        ╨╠
      ╨   altered as to content or credit, and it is provided without   ╨╠
      ╨   purpose of monetary gain.                                     ╨╠
      ╨                                                                 ╨╠
      ╨                        ╝╝ DISCLAIMER ╞╞                         ╨╠
      ╨   I have strived to make this Listing as accurate as I can, but ╨╠
      ╨   I realize that mistakes do happen, and so should you.  You    ╨╠
      ╨   should consider this Listing as a starting point.  I suggest  ╨╠
      ╨   that you use the Manufacturer's Directory to obtain additional╨╠
      ╨   information directly before you finalize any decision.  My    ╨╠
      ╨   Liability shall be limited to only my embarrasment and an     ╨╠
      ╨   appology for any inconvienience caused.                       ╨╠
      гддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╤╠
      ╨   The Author may be reached on KADET PCBoard BBS (315)245-3815, ╨╠
      ╨   or ULYSSES SYSTEMS RBBS (315)339-5591 (FIDONET 1:260/501).    ╨╠
      ╨   You may also try the Metrolink/Rime "Hardware" & "Harddisk"   ╨╠
      ╨   conferences, or the FidoNet "HDConf" & "SCSI-ONE" conferences.╨╠
      гддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддддд╤╠
      ╨                         ╝╝ PAYMENT ╞╞                           ╨╠
      ╨                                                                 ╨╠
      ╨   Just kidding!  TheRef(tm) shall remain a "freebie" as long as ╨╠
      ╨   these fingers can type.  Is it the best it can be?  I doubt   ╨╠
      ╨   it, but YOU can help too!  If you know the specs for a disk,  ╨╠
      ╨   or controller that's not listed, or have some information you ╨╠
      ╨   feel should be in the DOC file, send it to me at the address  ╨╠
      ╨   below, and if I include it, you'll get listed in the "Credits"╨╠
      ╨   page as a Contributor. (Wow!...International Recognition!) <g>╨╠
      ╨                                                                 ╨╠
      ╨   Mail all correspondence to:      F. Robert Falbo              ╨╠
      ╨                                    (THEREF42)                   ╨╠
      ╨                                    38 Northwinds Manor          ╨╠
      ╨                                    Rome, NY  USA  13440-7314    ╨╠
      хммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммммм╪╠
       ╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠╠

      Ч
