@echo off
if '%1'=='+' goto noinit
echo + >_temp_.dob
echo # >_temp_.dow
echo /* This file was automatically generated by Ghostscript (gsconfig.bat). */ >_temp_.dh
echo /* See gconfig.c for documentation. */ >>_temp_.dh
echo /* */ >_temp_.dop
echo + >_temp_.dlb
echogs @echo off >_temp_.bat
goto top
:noinit
shift
:top
if '%1'=='' goto done
if '%1'=='+' goto nofin
copy /b _temp_.bat+%1 >nul
shift
goto top
:done
command /c _temp_.bat >nul
sort <_temp_.dob | uniq >obj.tr
sort <_temp_.dow | uniq >objw.tr
sort <_temp_.dop | uniq >>_temp_.dh
if exist lib.tr erase lib.tr
rename _temp_.dlb lib.tr
if exist gconfig.h erase gconfig.h
rename _temp_.dh gconfig.h
erase _temp_.d*
erase _temp_*.bat
:nofin
