@echo off
echogs @echo off >%1.dev
echo rem This file was automatically generated by Ghostscript (gssetmod). >>%1.dev
if exist %1.d_f erase %1.d_f
if exist %1.d_n erase %1.d_n
if exist %1.d_o erase %1.d_o
if exist %1.d_v erase %1.d_v
if exist %1.d_w erase %1.d_w
echo if exist %1.d_n copy /b _temp_.dh+%1.d_n >>%1.dev
echo if exist %1.d_o copy /b _temp_.dob+%1.d_o >>%1.dev
echo if exist %1.d_v copy /b _temp_.dop+%1.d_v >>%1.dev
echo if exist %1.d_w copy /b _temp_.dow+%1.d_w >>%1.dev
gsaddmod %1 -obj %2 %3 %4 %5 %6 %7 %8 %9
