.TH anytopnm 1 "27 July 1990"
.IX anytopnm
.SH NAME
anytopnm - attempt to convert an unknown type of image file to a portable anymap
.SH SYNOPSIS
.B anytopnm
.I file
.SH DESCRIPTION
Uses the
.I file
program, possibly augmented by the magic numbers file
included with PBMPLUS, to try to figure out what type of image file it is.
.IX "magic numbers"
If that fails (very few image formats have magic numbers),
looks at the filename extension.
If that fails, punts.
.PP
The type of the output file depends on the input file.
.SH "SEE ALSO"
pnmfile(1), pnm(5), file(1)
.SH BUGS
It's a script.
Scripts are not portable to non-Unix environments.
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
