.TH pnm 5 "27 September 1991"
.SH NAME
pnm - portable anymap file format
.SH DESCRIPTION
The
.I pnm
programs operate on portable bitmaps, graymaps, and pixmaps, produced by the
.I pbm, pgm,
and
.I ppm
segments.  There is no file format associated with
.I pnm
itself.
.SH "SEE ALSO"
anytopnm(1), rasttopnm(1), tifftopnm(1), xwdtopnm(1),
pnmtops(1), pnmtorast(1), pnmtotiff(1), pnmtoxwd(1),
pnmarith(1), pnmcat(1), pnmconvol(1), pnmcrop(1), pnmcut(1),
pnmdepth(1), pnmenlarge(1), pnmfile(1), pnmflip(1), pnmgamma(1),
pnmindex(1), pnminvert(1), pnmmargin(1), pnmnoraw(1), pnmpaste(1),
pnmrotate(1), pnmscale(1), pnmshear(1), pnmsmooth(1), pnmtile(1),
ppm(5), pgm(5), pbm(5)
.SH AUTHOR
Copyright (C) 1989, 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
