.TH pnmcat 1 "12 March 1989"
.IX pnmcat
.SH NAME
pnmcat - concatenate portable anymaps
.SH SYNOPSIS
.B pnmcat
.RB [ -white | -black ]
.BR -leftright | -lr
.RB [ -jtop | -jbottom ]
.I pnmfile pnmfile
.RI ...
.br
.B pnmcat
.RB [ -white | -black ]
.BR -topbottom | -tb
.RB [ -jleft | -jright ]
.I pnmfile pnmfile
.RI ...
.SH DESCRIPTION
Reads portable anymaps as input.
Concatenates them either left to right or top to bottom, and produces a
portable anymap as output.
.IX concatenation
.SH OPTIONS
.PP
If the anymaps are not all the same height (left-right) or width (top-bottom),
the smaller ones have to be justified with the largest.
By default, they get centered, but you can specify one side or the other
with one of the -j* flags.
So,
.B -topbottom -jleft
would stack the anymaps on top of each other, flush with the left edge.
.PP
The
.B -white
and
.B -black
flags specify what color to use to fill in the extra space
when doing this justification.
If neither is specified, the program makes a guess.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
