.TH pnmenlarge 1 "26 February 1989"
.IX pnmenlarge
.SH NAME
pnmenlarge - read a portable anymap and enlarge it N times
.SH SYNOPSIS
.B pnmenlarge
.I N
.RI [ pnmfile ]
.SH DESCRIPTION
Reads a portable anymap as input.
Replicates its pixels
.I N
times, and produces a portable anymap as output.
.IX enlarging
.PP
.I pnmenlarge
can only enlarge by integer factors.
The slower but more general
.I pnmscale
.IX pnmscale
can enlarge or reduce by arbitrary
factors, and
.I pbmreduce
.IX pbmreduce
can reduce by integer factors, but only for bitmaps.
.PP
If you enlarge by a factor of 3 or more, you should probably add a
.I pnmsmooth
.IX pnmsmooth
step; otherwise, you can see the original pixels in the resulting image.
.SH "SEE ALSO"
pbmreduce(1), pnmscale(1), pnmsmooth(1), pnm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
