.TH pnmindex 1 "9 January 1991"
.IX pnmindex
.SH NAME
pnmindex - build a visual index of a bunch of anymaps
.SH SYNOPSIS
.B pnmindex
.RB [ -size
.IR N ]
.RB [ -across
.IR N ]
.RB [ -colors
.IR N ]
.RB [ -black ]
.I pnmfile
.RI ...
.SH DESCRIPTION
This script makes small versions of a bunch of anymaps, adds
labels, and concatenates them together into a collage.
.IX index
.IX collage
.SH OPTIONS
.TP
.B -size
Controls how big each image becomes; the default is 100x100.
.TP
.B -across
Controls how many images are in each row; the default is 6.
.TP
.B -colors
Controls how many colors the final index gets quantized
to, if quantization is necessary; the default is 256.
.TP
.B -black
Controls the color of the padding between the images;
normally it's white and the labels are black lettering on white background,
but the
.B -black
flag reverses this.
.SH "SEE ALSO"
pnmscale(1), pnmcat(1), pbmtext(1), ppmquant(1), pnm(5)
.SH BUGS
It's very slow.
.PP
It's a csh script.
Csh scripts are not portable to System V.
Scripts in general are not portable to non-Unix environments.
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
