.TH pnmpaste 1 "21 February 1991"
.IX pnmpaste
.SH NAME
pnmpaste - paste a rectangle into a portable anymap
.SH SYNOPSIS
.B pnmpaste
.RB [ -replace | -or | -and
.RB | -xor ]
.I frompnmfile x y
.RI [ intopnmfile ]
.SH DESCRIPTION
Reads two portable anymaps as input.
Inserts the first anymap into the second at the specified location,
and produces a portable anymap the same size as the second as output.
.IX paste
If the second anymap is not specified, it is read from stdin.
The
.I x
and
.I y
can be negative, in which case they are interpreted
relative to the right and bottom of the anymap, respectively.
.PP
This tool is most useful in combination with
.IR pnmcut .
.IX pnmcut
For instance, if you want to edit a small segment of a large
image, and your image editor cannot edit the
large image, you can cut out the segment you are interested in,
edit it, and then paste it back in.
.PP
Another useful companion tool is
.IR pbmmask .
.IX pnmmask
.OPTIONS
.PP
The optional flag specifies the operation to use when doing the paste.
The default is
.BR -replace .
The other, logical operations are only allowed if both input images
are bitmaps.
.IX "logical operations"
These operations act as if white is TRUE and black is FALSE.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnmcut(1), pnminvert(1), pnmarith(1), pnm(5), pbmmask(1)
.SH AUTHOR
Copyright (C) 1989, 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
