.TH pnmscale 1 "12 January 1991"
.IX pnmscale
.SH NAME
pnmscale - scale a portable anymap
.SH SYNOPSIS
.B pnmscale
.I s
.RI [ pnmfile ]
.br
.B pnmscale
.BR -xsize | -width | -ysize |
.BR -height
.I s
.RI [ pnmfile ]
.br
.B pnmscale
.BR -xscale | -yscale
.I s
.RI [ pnmfile ]
.br
.B pnmscale
.BR -xscale | -xsize | -width
.I s
.BR -yscale | -ysize | -height
.I s
.RI [ pnmfile ]
.br
.B pnmscale -xysize
.I x y
.RI [ pnmfile ]
.SH DESCRIPTION
Reads a portable anymap as input.
Scales it by the specified factor or factors and produces a portable
anymap as output.
.IX shrinking
.IX enlarging
If the input file is in color, the output will be too,
otherwise it will be grayscale.
You can both enlarge (scale factor > 1) and reduce (scale factor < 1).
.PP
You can specify one dimension as a pixel size, and the other dimension
will be scaled correspondingly.
.PP
You can specify one dimension as a scale, and the other dimension
will not be scaled.
.PP
You can specify different sizes or scales for each axis.
.PP
Or, you can use the special
.B -xysize
flag, which fits the image into
the specified size without changing the aspect ratio.
.PP
All flags can be abbreviated to their shortest unique prefix.
.PP
If you enlarge by a factor of 3 or more, you should probably add a
.I pnmsmooth
.IX pnmsmooth
step; otherwise, you can see the original pixels in the resulting image.
.SH "SEE ALSO"
pbmreduce(1), pnmenlarge(1), pnmsmooth(1), pnm(5)
.SH AUTHOR
Copyright (C) 1989, 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
