.TH pnmshear 1 "12 January 1991"
.IX pnmshear
.SH NAME
pnmshear - shear a portable anymap by some angle
.SH SYNOPSIS
.B pnmshear
.RB [ -noantialias ]
.I angle
.RI [ pnmfile ]
.SH DESCRIPTION
Reads a portable anymap as input.
Shears it by the specified angle and produces a portable
anymap as output.
.IX shearing
If the input file is in color, the output will be too,
otherwise it will be grayscale.
The angle is in degrees (floating point), and measures this:
.nf
    +-------+  +-------+
    |       |  |\\       \\
    |  OLD  |  | \\  NEW  \\
    |       |  |an\\       \\
    +-------+  |gle+-------+
.fi
If the angle is negative, it shears the other way:
.nf
    +-------+  |-an+-------+
    |       |  |gl/       /
    |  OLD  |  |e/  NEW  /
    |       |  |/       /
    +-------+  +-------+
.fi
The angle should not get too close to 90 or -90, or the resulting
anymap will be unreasonably wide.
.PP
The shearing is implemented by looping over the source pixels and distributing
fractions to each of the destination pixels.
This has an "anti-aliasing" effect - it avoids jagged edges and similar
artifacts.
.IX anti-aliasing
However, it also means that the original colors or gray levels in the image
are modified.
If you need to keep precisely the same set of colors, you can use
the
.B -noantialias
flag.  This does the shearing by moving pixels without changing their values.
If you want anti-aliasing and don't care about the precise colors, but
still need a limited *number* of colors, you can run the result through
.IR ppmquant .
.IX ppmquant
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnmrotate(1), pnmflip(1), pnm(5), ppmquant(1)
.SH AUTHOR
Copyright (C) 1989, 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
