.TH pnmtops 1 "26 October 1991"
.IX pnmtops
.SH NAME
pnmtops - convert portable anymap to PostScript
.SH SYNOPSIS
.B pnmtops
.RB [ -scale
.IR s ]
.RB [ -turn | -noturn ]
.RB [ -rle | -runlength ]
.RB [ -dpi
.IR n ]
.RB [ -width
.IR n ]
.RB [ -height
.IR n ]
.RI [ pnmfile ]
.SH DESCRIPTION
Reads a portable anymap as input.
Produces Encapsulated PostScript as output.
.IX PostScript
.PP
If the input file is in color (PPM), a color PostScript file gets
written.
Some PostScript interpreters can't handle color PostScript.
If you have one of these you will need to run your image through
.I ppmtopgm
first.
.PP
Note that there is no pstopnm
tool - this transformation is one-way, because a pstopnm tool would
be a full-fledged PostScript interpreter, which is beyond the scope
of this package.
However, see the
.I psidtopgm
tool, which can read grayscale non-runlength PostScript image data.
Also, if you're willing to install the fairly large GhostScript package,
it comes with a pstoppm script.
.SH OPTIONS
.PP
The
.B -scale
flag controls the scale of the result.  The default scale is 1,
which on a 300 dpi printer such as the Apple LaserWriter makes
the output look about the same size as the input would if it was displayed
on a typical 72 dpi screen.
To get one PNM pixel per 300 dpi printer pixel, use "-scale 0.25".
.PP
The
.B -turn
and
.B -noturn
flags control whether the image gets turned 90 degrees.
Normally, if an image is wider than it is tall, it gets turned
automatically to better fit the page.
If the
.B -turn
flag is specified, it will be turned no matter what its shape; and if the
.B -noturn
flag is specified, it will
.I not
be turned no matter what its shape.
.PP
The
.B -rle
or
.B -runlength
flag specifies run-length compression.  This may save
time if the host-to-printer link is slow; but normally the printer's processing
time dominates, so
.B -rle
makes things slower.
.PP
The
.B -dpi
flag lets you specify the dots per inch of your output device.
The default is 300 dpi.
In theory PostScript is device-independent and you don't have to
worry about this, but in practice its raster rendering can have
unsightly bands if the device pixels and the image pixels aren't
in sync.
.PP
The
.B -width
and
.B -height
flags let you specify the size of the page.
The default is 8.5 inches by 11 inches.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnm(5), psidtopgm(1)
.SH AUTHOR
Copyright (C) 1989, 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
