
					Yggdrasil Computing, Incorporated
    ALPHA				Post Office Box 8418
    TEST				Berkeley, California 94707-8418
    RELEASE				United States
					(510) 528-3209, fax: (510) 528-8508




	Welcome to the Yggdrasil Linux/GNU/X CDROM distribution
		    (installed on hard disk).



The following user names have been installed:

	guest	is an unprivileged user account for exploring
		Linux and the X window system.

	 root	is the superuser account for system administration.


