.\" man page for dvips
.TH DVIPS 1 "16 July 1987"
.SH NAME
.ds PS P\s-2OST\s+2S\s-2CRIPT\s+2
.ds TX T\\v'0.2m'\\h'-1p'E\\v'-0.2m'\\h'-1p'X
dvips \- convert a TeX dvi file to PostScript commands
.SH SYNOPSIS
.B dvips
[
.B -n
.I num
]
[
.B -p
.I num
]
[
.B -o
.I file
]
[
.B -h
.I file
]
[
.B -c
.I num
]
[
.B -q
]
[
.B -f
]
[
.B -r
]
[
.B -?
]
[
.B -d
.I num
]
.I dvifile
.br
.SH DESCRIPTION
.B dvips
is a program that takes a
.I dvi
file produced by TeX and converts it to PostScript commands that can
be fed to a PostScript printer for printing.
The dvi file may be specified without the
.I .dvi
extension.
.SH OPTIONS
The
.I dvifile
argument is mandatory.
All the rest are optional.
Optional arguments are:
.IP "\fB-n\fP \fInum\fP"
.I num
pages will be printed out.
.IP "\fB-p\fP \fInum\fP"
The first page printed will be the one numbered
.I num.
.IP "\fB-o\fP \fIname\fP"
The output will be sent to file
.I name.
.IP "\fB-h\fP \fIname\fP"
Use file
.I name
as the header file rather than the default.
.IP "\fB-c\fP \fInum\fP"
Generate
.I num
copies.
.IP "\fB-q\fP"
Run in quiet mode.
.IP "\fP-f\fP"
Run as a filter.
Read the dvi file from standard input and write the PostScript to
standard output.
.IP "\fB-r\fP"
Reverse order the pages.
Normally, page one will be printed first.
.IP "\fB-?\fP"
Print out the banner identifying the program.
.IP "\fB-d\fP \fInum\fP"
Set the debug flag.
Usually should not be used by normal users.
This will only work if
.B dvips
has been compiled with the DEBUG option.
See the file
.I debug.h
in the sources to see what the values of
.I num
can be.
.P
The
.B dvips
program also recognizes two environment variables, 
.B TEXFONTS
(to search for tfm files, like TeX) and
.B TEXPKS
(to search for pk files.)
.SH "CONFIG FILE OPTIONS"
The config file can be used to set many of the options to configure
.B dvips
for a particualr site.
These will probably be set by the installer so normal users can skip
this section.
The options are:
.IP "\fBm\fP \fInum\fP"
.I num is the memory available in the printer
.IP "\fBo\fP \fIname\fP"
The default output file is set to
.I name
.IP "\fBt\fP \fIpath\fP"
The path to search for the tfm files is
.I path.
.IP "\fp\fP \fIpath\fP"
The path to search for the font files is
.I path.
The TEXFONTS environment variable will override this.
.IP "\fBr\fP"
Default to reversing the pages.
.IP "\fBd\fP \fIfont mappedFont j\fP"
The font named
.I font
is treated as a resident font and is mapped to the font named
.I mappedFont.
I have no idea what the
.I j
parameter means.
.IP "\fBq\fP"
Run in quiet mode by default.
.IP "\fBf\fP"
Run as a filter by default.
.IP "\fBh\fP \fIname\fP"
Add
.I name
as a header file to be downloaded at the beginning.
.SH "THE \\*(TX \\\\special COMMAND"
This program supports use of the \\special command in \*(TX
to include special \*(PS code for graphics, etc.  Specifying
``\\special{psfile=foo.ps}'' in the \*(TX source will result in the contents
of file ``foo.ps'' (assumed to contain \*(PS code) being copied 
into the output at that point.  For most included graphics, the
user's (0,0) point will be set to the point of the \\special command
with x and y coordinates increasing up and to the right and in units
of \*(PS points (1/72 inch) \(em thus you must explicitly leave space
above the \\special command for most graphics.  For graphics produced by 
Apple Macintoshes (i.e., MacDraw, MacPaint, etc.), the top left corner of 
the drawing will be at the point of the \\special command; in this case you 
must leave the required space below the \\special.

The \\special string can contain any number of the following 
``keyword=value'' pairs, separated by blanks:

.ta 0.2i 1.1i 2.2i
.B
	Keyword	Value	Type
.br
	psfile	string	specifies a \*(PS file to include
.br
	hsize	dimension	specifies maximum horizontal size
(for clipping)
.br
	vsize	dimension	specifies maximum vertical size (for clipping)
.br
	hoffset	dimension	specifies amount to shift right
.br
	voffset	dimension	specifies amount to shift up (or down, for Macintosh
drawings)
.br
	hscale	number	specifies a scale factor in x-dimension
.br
	vscale	number	specifies a scale factor in y-dimension

Dimensions are given in \*(PS points (72 per inch).  For example,

.ce 1
\\special{psfile=foo.ps hoffset=72 hscale=0.9 vscale=0.9}

will shift the graphics produced by file ``foo.ps'' right by 1" and will draw
it at 0.9 normal size.  Hsize and vsize are given relative to the (0,0)
point of the drawing and are unaffected by offsets and scales.  Offsets are
given relative to the point of the \\special command, and are unaffected by
scales.

If Macintosh drawings are to be included, the Macintosh LaserPrep file
must be downloaded to the printer, either permanently or as another
header file in addition to the standard ``tex.pro'' header file.
.SH FILES
These are usually system dependent, but look at:
.br
.ta 3i
the PS prologue	/usr/local/lib/tex/tex.pro
.br
the prologue for PS fonts	/usr/local/lib/tex/tex.pro
.br
the tfm files	/usr/local/lib/tex/fonts/*tfm
.br
the font files	/usr/local/lib/tex/fonts/*pk
.SH "SEE ALSO"
tex(1), dvi2ps(1), latex(1), lpr(1)
.SH BUGS
Rejects any file with the string "IBM" in it.
This is considered to be a feature by some.
.SH AUTHORS
Tomas Rokicki <rokicki@sushi.stanford.edu>, Dorab Patel,
Dick Grunwald, and Caleb Hess.
