.TH fstopgm 1 "06 April 89"
.IX fstopgm
.SH NAME
fstopgm - convert a Usenix FaceSaver(tm) file into a portable graymap
.SH SYNOPSIS
.B fstopgm
.RI [ fsfile ]
.SH DESCRIPTION
Reads a Usenix FaceSaver(tm) file as input.
.IX FaceSaver
Produces a portable graymap as output.
.PP
FaceSaver(tm) files sometimes have rectangular pixels.
While
.I fstopgm
won't re-scale them into square pixels for you,
it will give you the precise
.I pnmscale
command that will do the job.
Because of this, reading a FaceSaver(tm) image is a two-step process.
First you do:
.nf
  fstopgm > /dev/null
.fi
This will tell you whether you need to use
.I pnmscale.
Then use one of the following pipelines:
.nf
  fstopgm | pgmnorm
  fstopgm | pnmscale -whatever | pgmnorm
.fi
To go to PBM, you want something more like one of these:
.nf
  fstopgm | pnmenlarge 3 | pgmnorm | pgmtopbm
  fstopgm | pnmenlarge 3 | pnmscale <whatever> | pgmnorm | pgmtopbm
.fi
You want to enlarge when going to a bitmap because otherwise you lose
information; but enlarging by more than 3 does not look good.
.PP
FaceSaver is a registered trademark of Metron Computerware Ltd. of
Oakland, CA.
.SH "SEE ALSO"
pgmtofs(1), pgm(5), pgmnorm(1), pnmenlarge(1), pnmscale(1), pgmtopbm(1)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
