.TH pgmbentley 1 "11 January 1991"
.IX pgmbentley
.SH NAME
pgmbentley - Bentleyize a portable graymap
.SH SYNOPSIS
.B pgmbentley
.RI [ pgmfile ]
.SH DESCRIPTION
Reads a portable graymap as input.
Performs The Bentley Effect, and writes a portable graymap as output.
.IX "Bentley Effect"
.PP
The Bentley Effect is described in "Beyond Photography" by Holzmann,
chapter 4, photo 4.
It's a vertical smearing based on brightness.
.SH "SEE ALSO"
pgmoil(1), ppmrelief(1), pgm(5)
.SH AUTHOR
Copyright (C) 1990 by Wilson Bent (whb@hoh-2.att.com)
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
