.TH pgmoil 1 "11 January 1991"
.IX pgmoil
.SH NAME
pgmoil - turn a portable graymap into an oil painting
.SH SYNOPSIS
.B pgmoil
.RB [ -n
.IR N ]
.RI [ pgmfile ]
.SH DESCRIPTION
Reads a portable graymap as input.
Does an "oil transfer", and writes a portable graymap as output.
.IX "oil transfer"
.PP
The oil transfer is described in "Beyond Photography" by Holzmann,
chapter 4, photo 7.
It's a sort of localized smearing.
.SH OPTIONS
.PP
The optional
.B -n
flag controls the size of the area smeared.  The default value is 3.
.SH BUGS
Takes a long time to run.
.SH "SEE ALSO"
pgmbentley(1), ppmrelief(1), pgm(5)
.SH AUTHOR
Copyright (C) 1990 by Wilson Bent (whb@hoh-2.att.com)
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
