.TH pgmramp 1 "24 November 1989"
.IX pgmramp
.SH NAME
pgmramp - generate a grayscale ramp
.SH SYNOPSIS
.B pgmramp
.BR -lr | -tb
|
.BR -rectangle | -ellipse
.I width height
.SH DESCRIPTION
Generates a graymap of the specified size containing a black-to-white ramp.
.IX "generating graymaps"
These ramps are useful for multiplying with other images, using the
.I pnmarith
tool.
.IX pnmarith
.SH OPTIONS
.TP
.B -lr
A left to right ramp.
.TP
.B -tb
A top to bottom ramp.
.TP
.B -rectangle
A rectangular ramp.
.TP
.B -ellipse
An elliptical ramp.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnmarith(1), pgm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
