.TH pgmtofs 1 "18 May 1990"
.IX pgmtofs
.SH NAME
pgmtofs - convert portable graymap to Usenix FaceSaver(tm) format
.SH SYNOPSIS
.B pgmtofs
.RI [ pgmfile ]
.SH DESCRIPTION
Reads a portable graymap as input.
Produces Usenix FaceSaver(tm) format as output.
.IX FaceSaver
.PP
FaceSaver is a registered trademark of Metron Computerware Ltd. of
Oakland, CA.
.SH "SEE ALSO"
fstopgm(1), pgm(5)
.SH AUTHOR
Copyright (C) 1991 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
