.TH pgmtopbm 1 "26 July 1988"
.IX pgmtopbm
.SH NAME
pgmtopbm - convert a portable graymap into a portable bitmap
.SH SYNOPSIS
.B pgmtopbm
.RB [ -floyd | -fs | -threshold
.RB | -dither8 | -d8 | -cluster3
.RB | -c3 | -cluster4 | -c4
.RB | -cluster8 | -c8 ]
.RB [ -value
.IR val ]
.RI [ pgmfile ]
.SH DESCRIPTION
Reads a portable graymap as input.
Produces a portable bitmap as output.
.IX halftoning
.PP
Note that there is no pbmtopgm converter, because any pgm program can
read pbm files automagically.
.SH OPTIONS
.PP
The default quantization method is boustrophedonic Floyd-Steinberg error
diffusion
.RB ( -floyd
or
.BR -fs ).
.IX Floyd-Steinberg
.IX "error diffusion"
Also available are simple thresholding
.RB ( -threshold );
.IX thresholding
Bayer's ordered dither
.RB ( -dither8 )
with a 16x16 matrix; and three different sizes of 45-degree clustered-dot dither
.RB  ( -cluster3 ,
.BR -cluster4 ,
.BR -cluster8 ).
.IX dithering
.PP
Floyd-Steinberg will almost always give the best looking results; however,
looking good is not always what you want.
For instance, thresholding can be used in a pipeline with the
.I pnmconvol
.IX pnmconvol
tool, for tasks like edge and peak detection.
And clustered-dot dithering gives a newspaper-ish look, a useful special effect.
.PP
The
.B -value
flag alters the thresholding value for Floyd-Steinberg and
simple thresholding.
It should be a real number between 0 and 1.
Above 0.5 means darker images; below 0.5 means lighter.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH REFERENCES
The only reference you need for this stuff is "Digital Halftoning" by
Robert Ulichney, MIT Press, ISBN 0-262-21009-6.
.SH "SEE ALSO"
pbmreduce(1), pgm(5), pbm(5), pnmconvol(1)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
