.TH psidtopgm 1 "02 August 89"
.IX psidtopgm
.SH NAME
psidtopgm - convert PostScript "image" data into a portable graymap
.SH SYNOPSIS
.B psidtopgm
.I width height bits/sample
.RI [ imagedata ]
.SH DESCRIPTION
Reads the "image" data from a PostScript file as input.
.IX PostScript
Produces a portable graymap as output.
.PP
This is a very simple and limited program, and is here only because
so many people have asked for it.
To use it you have to
.B manually
extract the readhexstring data portion from your PostScript file, and then
give the width, height, and bits/sample on the command line.
Before you attempt this, you should
.B at least
read the description of the "image" operator in the PostScript Language
Reference Manual.
.PP
It would probably not be too hard to write a script that uses this filter
to read a specific variety of PostScript image, but the variation is too
great to make a general-purpose reader.
Unless, of course, you want to write a full-fledged PostScript interpreter...
.SH "SEE ALSO"
pnmtops(1), pgm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
