.TH rawtopgm 1 "15 December 89"
.IX rawtopgm
.SH NAME
rawtopgm - convert raw grayscale bytes into a portable graymap
.SH SYNOPSIS
.B rawtopgm
.RB [ -headerskip
.IR N ]
.RB [ -rowskip
.IR N ]
.I width height
.RI [ imagedata ]
.SH DESCRIPTION
Reads raw grayscale bytes as input.
.IX "raw grayscale"
Produces a portable graymap as output.
The input file is just grayscale bytes.
You have to specify the width and height on the command line,
since the program obviously can't get them from the file.
The maxval is assumed to be 255.
If the resulting image is upside down, run it through
.B "pnmflip -tb" .
.IX pnmflip
.SH OPTIONS
.TP
.B -headerskip
If the file has a header, you can use this flag to
skip over it.
.TP
.B -rowskip
If there is padding at the ends of the rows, you can skip it with this flag.
Note that rowskip can be a real number.
Amazingly, I once had an image with 0.376 bytes of padding per row.
This turned out to be due to a file-transfer problem, but I was still
able to read the image.
.SH "SEE ALSO"
pgm(5), rawtoppm(1), pnmflip(1)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
