.TH CRON 8
.SH NAME
cron \- clock daemon
.SH SYNOPSIS
\fBcron\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "/usr/bin/cron" "Use absolute path in \fI/etc/rc\fR"
.SH DESCRIPTION
.PP
\fICron\fR is clock daemon.  It is typically started up by including the
command \fI/usr/bin/cron\fR in the \fI/etc/rc\fR file.  
Once started, \fIcron\fR puts itself
in the background, so no & is needed.  It runs forever, sleeping most of
the time.  Once a minute it wakes up and examines \fI/usr/lib/crontab\fR to see
if there is any work to do.  If there is, the work is done.  The entries of
\fI/usr/lib/crontab\fR contain 6 elements each.  Some examples follow:
.PP
.nf
.ta 0.10i 0.40i 0.70i 1.0i 1.3i 1.8i 4.0i
\fB	Min	Hr	Dat	Mo	Day	Command\fR
	\0*	\0*	\0*	\0*	\0*	/usr/bin/date >/dev/log   #print date every minute
	\00	\0*	\0*	\0*	\0*	/usr/bin/date >/dev/log   #print date on the hour
	30	\04	\0*	\0*	1-5	/bin/backup /dev/fd1      #do backup Mon-Fri at 0430
	30	19	\0*	\0*	1,3,5	/etc/backup /dev/fd1      #Mon, Wed, Fri at 1930
	\00	\09	25	12	\0*	/usr/bin/sing >/dev/log   #Xmas morning at 0900 only
.fi
.SH "SEE ALSO"
.BR at (1).
