.TH INODES 8
.SH NAME
inodes \- print i-node information
.SH SYNOPSIS
\fBinodes\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "inodes" "Print information about file names typed in"
.EX "cd /dev; ls | inodes" "Print information about the special files"
.SH DESCRIPTION
.PP
\fIInodes\fR expects a list of file names on \fIstdin\fR, one file name
per line.
For each file named, the file type, mode, uid, gid, checksum, length,
and name is printed.
The checksum is the same as used by \fIcrc\fR.
This program provides a way to see the sizes of the block special
files in \fI/dev\fR, as shown in the second example above.
