.TH READCLOCK 8
.SH NAME
readclock \- read the real time clock [IBM PC/AT and AMIGA]
.SH SYNOPSIS
\fBreadclock\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "date \`/usr/bin/readclock\` </dev/tty" "Useful in \fI/etc/rc\fR"
.SH DESCRIPTION
.PP
\fIReadclock\fR reads the AT's real time clock and prints the result in 
a form useful to date, namely, MMDDYYhhmmss.  
If the clock does not exist (e.g., on a
PC), it outputs \&'\-q\&' to query the user for the time.  
The example given above
can be put in \fI/etc/rc\fR to load the real time when the system is booted.
.SH "SEE ALSO"
.BR date (1).
